### ISSUE TITLE
fc-deploy 组件 remove 期望支持 cli

### ISSUE THREAD

**Issue by wss-git** [devsapp/fc#106]

**Comment by wss-git** [comment]
![Uploading image.png…]()

**Comment by wss-git** [comment]
![image](https://user-images.githubusercontent.com/56686088/125788125-71a5f98a-83c3-45f7-bb37-5290c7605e88.png)

**Comment by rsonghuster** [comment]
s cli fc remove --region <> --service-name <> -a <密钥别名，默认 default>
