### ISSUE TITLE
端云联调， 因为一段时间断网， 代理容器退出， ca 容器热更新终端卡住

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#107]
![image](https://user-images.githubusercontent.com/10919599/125786747-d4eb6e73-3217-461e-9c6b-10016fc81a8a.png)

这个时候应该 ca 容器退出， terminal 显示错误详情， 而不是卡住状态

**Comment by git-qfzhang** [comment]
已经在端云联调组件的 0.0.4 版本中修复
