### ISSUE TITLE
s build 功能优化

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#113]
比如我的 codeuri 如下：
![image](https://user-images.githubusercontent.com/10919599/126146089-a6f5730c-5e9c-4a3a-ad47-81e6fe313686.png)

这个时候， 我每次需要  s build -d， 然后再去 s local invoke 或者  s deploy

但是可能这个 s build 时间会很长， 假设我 requirements.txt 有较多的 python 库或者较大的库， 我希望有一个参数可以 skip 掉这个 install dependency 的过程， 当然， 能做到自动检测效果更好

**Comment by git-qfzhang** [comment]
这里需要参考下 fun build 是如何进行缓存机制实现的。

**Comment by git-qfzhang** [comment]
这里可以对比上次的依赖清单与本次的依赖清单是否一致，如果一致则跳过安装依赖步骤

**Comment by rsonghuster** [comment]
同时， 针对  python nodejs 这种编译型语言的场景， s deploy 的时候， 最好将 src copy 到交付物那边目录， 而不是重新执行下  s build 命令

**Comment by rsonghuster** [comment]
#95

build-link 功能有了以后， 实现 funfile 效果优先级就不高了， 理由如下：

针对编译型语言， 比如 java, 本身每次就需要编译， 只要优化好 maven 编译速度和提前下载好依赖的库即可

对于解释型语言， s build 就是安装依赖， 只要依赖不变， 不需要每次都执行 s build 命令
