### ISSUE TITLE
init java 函数build 失败

### ISSUE THREAD

**Issue by wss-git** [devsapp/fc#120]
使用 s init 或者 fun init 的 java 函数通过 build --use-docker 会变异失败

**Comment by wss-git** [comment]
在 pom.xml  的开头加一句 

<?xml version="1.0" encoding="UTF-8"?>

**Comment by wss-git** [comment]
java11
`````
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>example</groupId>
  <artifactId>java11</artifactId>
  <packaging>jar</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>java11</name>

  <dependencies>
    <dependency>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-clean-plugin</artifactId>
      <version>2.5</version>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.aliyun.fc.runtime</groupId>
      <artifactId>fc-java-core</artifactId>
      <version>1.3.0</version>
    </dependency>
  </dependencies>

  <properties>
    <maven.compiler.target>1.8</maven.compiler.target>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.test.skip>true</maven.test.skip>
  </properties>
</project>

`````

**Comment by git-qfzhang** [comment]
> java11
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
>   <modelVersion>4.0.0</modelVersion>
>   <groupId>example</groupId>
>   <artifactId>java11</artifactId>
>   <packaging>jar</packaging>
>   <version>1.0-SNAPSHOT</version>
>   <name>java11</name>
> 
>   <dependencies>
>     <dependency>
>       <groupId>org.apache.maven.plugins</groupId>
>       <artifactId>maven-clean-plugin</artifactId>
>       <version>2.5</version>
>     </dependency>
>     <dependency>
>       <groupId>junit</groupId>
>       <artifactId>junit</artifactId>
>       <version>3.8.1</version>
>       <scope>test</scope>
>     </dependency>
>     <dependency>
>       <groupId>com.aliyun.fc.runtime</groupId>
>       <artifactId>fc-java-core</artifactId>
>       <version>1.3.0</version>
>     </dependency>
>   </dependencies>
> 
>   <properties>
>     <maven.compiler.target>1.8</maven.compiler.target>
>     <maven.compiler.source>1.8</maven.compiler.source>
>     <maven.test.skip>true</maven.test.skip>
>   </properties>
> </project>
> ```

我这边尝试了不行。

**Comment by rsonghuster** [comment]
你这边编译失败是报什么错， 我这边就是一直在等待.....  很慢

build-1.9.17 从改成 build-1.9.19 就好了， 建议 fc-build 使用的 build 镜像版本统一改成 19.19
