### ISSUE TITLE
.fcignore 有bug

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#128]
![image](https://user-images.githubusercontent.com/10919599/126605835-0196b501-e041-4c34-90e6-ade744f18200.png)

如上图所示， 把依赖的 python 包 上传到 nas，然后本地部署函数的时候， 想 skip 掉这个， 但是 skip 不掉

**Comment by wss-git** [comment]
@git-qfzhang  这个建议将设计改一下，可以将 ignore 文件随 codeUri 生效， 不以 yaml 生效

理由：随yaml 生效的 build 不生效，s 通过-t 指定yaml的时候 ignore 应该也会失败

**Comment by git-qfzhang** [comment]
> @git-qfzhang 这个建议将设计改一下，可以将 ignore 文件随 codeUri 生效， 不以 yaml 生效
> 
> 理由：随yaml 生效的 build 不生效，s 通过-t 指定yaml的时候 ignore 应该也会失败

这里看起来的确是需要放在 codeUri 下，但是理由是因为在 s.yml 中一个函数对应一个独立的 serverless devs 的 project，而 .fcignore 是组件相关的，因此不能放在全局下面，这样如果一个 s.yml 中有多个函数时，每个函数应该都有一个 .fcignore ，这样更加合理
