### ISSUE TITLE
s [command] -t ./${path}/s.yml 时，state 保存路径不符合预期

### ISSUE THREAD

**Issue by git-qfzhang** [devsapp/fc#134]
s [command] -t ./${path}/s.yml 这种方式执行时，若调用了 core.setState 方法，则生成的 .s/***.json 文件会在当前指令执行路径下，不会在 s.yml 对应的路径下生成。

**Comment by xsahxl** [comment]
已修复： https://github.com/Serverless-Devs/core/commit/f929ac2ce682372243d2a2930f411829d28970f4
