### ISSUE TITLE
s init 希望模板里面有各种语言的 custom-container hello world 级别的版本

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#149]
![image](https://user-images.githubusercontent.com/10919599/127744221-9a85bc38-935d-4e02-9923-857e2bee92af.png)

如截图没有， 复杂点的 web 单体应用虽然是 custom-container， 但是是利用抽象层次更高 express 组件等

https://github.com/awesome-fc/custom-container-docs

对应这个，应该需要做到  s init 中

custom runtime 同理： https://github.com/awesome-fc/fc-custom-demo/tree/use-s

**Comment by rsonghuster** [comment]
#220

**Comment by rsonghuster** [comment]
```bash
# c++ 例子
s init start-fc-custom-container-http-cpp -d start-cc-http-cpp
s init start-fc-custom-container-event-cpp -d start-cc-event-cpp

# python
s init start-fc-custom-container-event-python3.9 -d start-cc-py39

# nodejs
s init start-fc-custom-container-event-nodejs14 -d start-cc-nodejs14

# springboot
s init start-fc-custom-container-http-springboot -d start-cc-http-springboot

# asp.netcore
s init start-fc-custom-container-http-aspdotnetcore -d start-cc-http-aspdotnetcore
```

**Comment by rsonghuster** [comment]
custom runtime 示例：

`s init start-fc-custom-samples -d start-fc-custom-samples`

![image](https://user-images.githubusercontent.com/10919599/130597032-8aca588e-588b-4cb6-ac32-74310d30fa32.png)

**Comment by wss-git** [comment]
s 相关的问题后面都有 dankun 大佬这边安排

**Comment by rsonghuster** [comment]
#185  s init 最好做成可配置化， 不依赖 S 的升级
