### ISSUE TITLE
s build 之后的产物上传到 nas

### ISSUE THREAD

**Issue by wss-git** [devsapp/fc#151]
- 产物文件放置路径过深，用户不知道怎么上传到 nas
- nas 上传 没有本地和远端映射关系，s deploy 需要手动写 .fcignore

**Comment by rsonghuster** [comment]
这里有个例子：  https://github.com/awesome-fc/cat-dog-classify

1. 产物文件放置路径过深，用户不知道怎么上传到 nas,  本质是 s build 命令之后， 交付物在哪里？ 这个应该是 build 文档要说清楚， 比如新的 build 文档： https://github.com/devsapp/fc/blob/build-docs/docs/Usage/build/build.md
2. nas 上传 没有本地和远端映射关系；  我觉的就没有默认的映射关系更好， 就想之前的 fun nas sync， 谁知道哪个传到哪里了

```
s nas upload -r .s/build/artifacts/cat-dog/classify/.s/python /mnt/auto/python
s nas upload -r src/model /mnt/auto/model
```

这种， 我觉的很清楚了
