### ISSUE TITLE
s build 命令，介绍这个命令的文档要更加仔细和 humanreadable

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#152]
- 有图介绍 build 的原理， 定义好源码和代码交付物， 以及目录结构是怎么样的， 后续的 local invoke, debug， deploy 针对的都是交付物

- 根据每个语言， 单独有一个文档介绍示例， 不要太笼统归结成一个大文章

**Comment by hanxie-crypto** [comment]
这个建议比较好， 对于新人来说，尤其是传统架构过来的同学需要理解他的代码部分怎么被构建上传的。我来写写nodejs 的吧

**Comment by rsonghuster** [comment]
这个我先给个初稿

**Comment by rsonghuster** [comment]
https://github.com/devsapp/fc/blob/build-docs/docs/Usage/build/build.md

**Comment by rsonghuster** [comment]
https://help.aliyun.com/document_detail/300455.html  已经有最新的官方文档了
