### ISSUE TITLE
s deploy --push-registry acr-internet  支持的不够好

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#154]
![image](https://user-images.githubusercontent.com/10919599/127811584-7ab43282-0693-4af3-a502-4366bb7b7cb6.png)

s deploy --push-registry acr-internet --use-local -y

比如我 yml 中虽然写的是 vpc 内网地址， 但是 s deploy push 的应该自动 tag 一个 非 vpc 的 tag， 然后自动push 上去， 而不是报错

![image](https://user-images.githubusercontent.com/10919599/127811698-e76c085c-f0e7-41db-ad48-f05c001580bd.png)

**Comment by rsonghuster** [comment]
是我使用不对， 如下图， 两个 region 必须相同

![image](https://user-images.githubusercontent.com/10919599/129340739-6838ff1e-12d1-4b2a-9ca4-42353fb233e4.png)

**Comment by git-qfzhang** [comment]
https://github.com/devsapp/fc-deploy/pull/86

**Comment by rsonghuster** [comment]
经过验收， 已经  OK 了
