### ISSUE TITLE
【fa-core】错误引导：所有依赖 docker 的功能都需要检查 docker 是否正常运行

### ISSUE THREAD

**Issue by git-qfzhang** [devsapp/fc#155]

**Comment by rsonghuster** [comment]
直接告诉用户这个命令需要安装 docker， 然后给出 docker 安装下载链接 ： https://help.aliyun.com/document_detail/195474.html#title-k00-2wj-8uf
或者 
https://github.com/devsapp/fc/blob/main/docs/Getting-started/Install-tutorial.md

建议还是给出 github 的连接， 因为文档的编号发生变化的可能性大些

**Comment by rsonghuster** [comment]
报错  cannot connect docker deamon 对于小白用户体验确实太差了

**Comment by git-qfzhang** [comment]
放到 fc-common 组件中，https://github.com/devsapp/fc-common/pull/1

**Comment by rsonghuster** [comment]
#262 类似， 提示信息做友好点
