### ISSUE TITLE
s invoke -e 参数是 json 的时候， 中间不能有空格， 否则会截断

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#159]
![image](https://user-images.githubusercontent.com/10919599/127967004-fb0b2aaa-13eb-430b-83d4-624c6f342109.png)

![image](https://user-images.githubusercontent.com/10919599/127967016-71f0bad5-f1ac-49ac-bd61-4d04fbacd470.png)

s invoke -e 参数是 json 的时候， 中间不能有空格， 否则会截断

**Comment by anycodes** [comment]
这个是命令行的规范了吧？这不是工具的问题哈。可以考虑用双引号转义

**Comment by rsonghuster** [comment]
但是双引号转义体验也太差了吧， event 是 json 字符串很正常啊

**Comment by anycodes** [comment]
@wss-git 

这里需要进行处理一下：https://github.com/devsapp/fc-remote-invoke/blob/653a70dfc0798348b8d409469388050c26b894a8/src/index.ts#L51
