### ISSUE TITLE
local invoke 执行会卡死

### ISSUE THREAD

**Issue by wss-git** [devsapp/fc#163]
## 复现步骤
1. 执行下面这段代码
````
const { loadComponent } = require('@serverless-devs/core');

async function abc(component){
  await loadComponent(component);
}

abc('fc'); // abc('devsapp/fc'); 
````
2. 卡在一直 download success（部署到线上没有问题）
![image](https://user-images.githubusercontent.com/56686088/128158104-b66dc8b2-70c8-41ac-8cd4-83d7a3700a25.png)

**Comment by rsonghuster** [comment]
在函数中实现使用 s ， 理由是啥

**Comment by rsonghuster** [comment]
@wss-git 反馈已经 fix
