### ISSUE TITLE
fc-transform 转换问题

### ISSUE THREAD

**Issue by git-qfzhang** [devsapp/fc#172]
转换过程中，如果在 template.yml 中 function 属性存在 CAPort 属性，在利用 fc-transform 转换后会将 CAPort 转换成 cAPort ，但是预期是 caPort。

**Comment by wss-git** [comment]
https://github.com/devsapp/fc-transform/commit/29cdf8c719bf8365e79a20c0c1932cbf01243f0d 已修复
