### ISSUE TITLE
S deploy 只有 nasconfig 为 auto 的时候， 会自动帮忙创建 nas 目录

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#176]
![image](https://user-images.githubusercontent.com/10919599/128531151-baeea515-0b45-41ae-b14a-c3939a5f0693.png)

当 s deploy nas config 不是 auto 的时候， 配置了 nas dir， 不是应该自动帮用户创建这个nas dir 呢？

不然会部署成功，但是调用会失败， 出错是不能 access 到 nas 节点， 根本看不出来错误， 当然 nas 挂载就没有具体的出错信息。。。， 是不是尽量避免更好

**Comment by git-qfzhang** [comment]
nas 组件需要做如下两个操作：

1.  暴露出确保 nasDir 存在的接口
2.  删除确保目录存在的辅助函数接口
