### ISSUE TITLE
端云联调支持 nas

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#178]
![image](https://user-images.githubusercontent.com/10919599/128586895-b490f95e-7a10-46e9-a272-233cd931171d.png)

可以尝试让本地的 ca 挂载 nas，需要做到如下两点：

1.  镜像需要安装 nfs-common
2. 启动本地ca 容器的时候需要特权模式

**Comment by rsonghuster** [comment]
1. 工作项 rsonghuster 完成 fc-docker 的改造
2. qfzhang 来完成和评估下

**Comment by rsonghuster** [comment]
fc-docker 1.9.19 已经build 和 push 完成了

**Comment by rsonghuster** [comment]
mount -t nfs -o vers=3,nolock,proto=tcp,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport 0777f491ea-fyy72.cn-hangzhou.nas.aliyuncs.com:/ /mnt/auto

**Comment by git-qfzhang** [comment]
mount -t nfs -o vers=3,nolock,proto=tcp,roresvport xxx.cn-shanghai.nas.aliyuncs.com:/ /mnt/auto

**Comment by JasonLamv-t** [comment]
> mount -t nfs -o vers=3,nolock,proto=tcp,roresvport xxx.cn-shanghai.nas.aliyuncs.com:/ /mnt/auto

我用上面这个指令会报参数错误，下面这个指令可以
`mount -t nfs -o vers=3,nolock,proto=tcp,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport 2db4949ea4-onv41.cn-shenzhen.nas.aliyuncs.com:/ /mnt/auto`
