### ISSUE TITLE
s proxied clean 建议改成 cleanup

### ISSUE THREAD

**Issue by hryang** [devsapp/fc#183]
cleanup 和 setup 对应，且 cleanup 更符合英语语法。在很多测试框架中，都是 setup/cleanup 的命名。

**Comment by rsonghuster** [comment]
readme 也要记得同时更新

**Comment by git-qfzhang** [comment]
Fix: https://github.com/devsapp/fc-proxied-invoke/pull/16

**Comment by git-qfzhang** [comment]
Fix： https://github.com/devsapp/fc/pull/222/files
