### ISSUE TITLE
fc-deploy .fcignore 在 codeUri 中时会失效

### ISSUE THREAD

**Issue by git-qfzhang** [devsapp/fc#196]

**Comment by rsonghuster** [comment]
我好像使用没有失效， 比如这个例子： https://github.com/devsapp/start-puppeteer/blob/master/src/nodejs12/src/.fcignore

**Comment by git-qfzhang** [comment]
build 后会不会失效需要进行验证

**Comment by rsonghuster** [comment]
> build 后会不会失效需要进行验证

我上面的例子， 就是 build 以后， 将 .fcignore copy 到 build 目录里面， 然后是生效的
