### ISSUE TITLE
S 有关 service role 操作优化建议

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#197]
目前我们在控制台层面上实现，如果用户没有FCDefaultrole，  就弹出让用户授予创建 FCDefaultrole， role 的 policy 如下

```bash
{
    "Version": "1",
    "Statement": [
        {
            "Action": [
                "vpc:DescribeVSwitchAttributes"
            ],
            "Resource": "*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "ecs:CreateNetworkInterface",
                "ecs:DeleteNetworkInterface",
                "ecs:DescribeNetworkInterfaces",
                "ecs:CreateNetworkInterfacePermission",
                "ecs:DescribeNetworkInterfacePermissions",
                "ecs:DeleteNetworkInterfacePermission"
            ],
            "Resource": "*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "log:PostLogStoreLogs"
            ],
            "Resource": "*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "cr:GetRepository",
                "cr:GetRepositoryTag",
                "cr:GetAuthorizationToken",
                "cr:PullRepository",
                "cr:GetRepoTagManifest",
                "cr:GetArtifactTag",
                "cr:GetInstanceVpcEndpoint"
            ],
            "Resource": "*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "fc:InvokeFunction",
                "mns:SendMessage",
                "mns:PublishMessage",
                "eventbridge:PutEvents",
                "mq:PUB",
                "mq:OnsInstanceBaseInfo"
            ],
            "Resource": "*",
            "Effect": "Allow"
        }
    ]
}
```
1.  在控制台场景中， 当用户创建一个新的函数， 默认使用这个 role， 不管函数收集日志， vpc 函数， nas 函数， 或者 custom container 函数都没有什么问题

2. 在 S 很多场景， 如果用户写了 logconfig：auto，  nasconfig:auto， 或者使用了 custom container 函数， 理论上都是可以直接使用这个 role， 而不需要用户去创建新的 role， 毕竟创建 role， 对很多企业客户， 权限是很大的， 除非用户使用想使用函数入参中 context 做 sts 访问其他云服务， 比如：https://github.com/devsapp/ffmpeg-app/blob/master/src/s.yaml#L14， 这种情况下， 才考虑给用户创建新的 role

**Comment by rsonghuster** [comment]
![image](https://user-images.githubusercontent.com/10919599/129331965-15615952-4d81-4285-9cd3-65a2f71bc3b6.png)

**Comment by anycodes** [comment]
- 优先使用用户配置的
- 其次使用fcdefaultrole
- 最后尝试帮助用户创建

**Comment by wss-git** [comment]
@rsonghuster @anycodes  权限后面这个去做是否可以

1. 如果用户配置了 role，那就直接使用用户配置的（和之前逻辑相同）
2. 用户没有配置 role，那就去尝试获取一下 fcdefaultrole 是否存在
  - 如果返回存在，则直接复用。存在的问题：如果直接复用的话，如果策略的权限不足怎么办？
  - 如果返回不存在，则创建。然后创建的策略信息是沿用之前的，还是使用这个 issue 的策略？
  - 如果返回错误 403，则直接使用这 role（fcdefaultrole）尝试去创建服务

**Comment by rsonghuster** [comment]
## 1. 如果返回存在，则直接复用。存在的问题：如果直接复用的话，如果策略的权限不足怎么办？
fcdefaultrole 对于跑任何类型的函数， 都不会存在策略权限不足的情况。  
唯一策略的权限不足就是用户自己本身的函数使用context.creds. 比如访问 oss， 这个时候， 用户必须在 yml 中设置具体的 role, 或者增加 oss 的 policy， 这种情况不和我们现在这个问题冲突

##  2 和 3
帮用户尝试创建， 如果用户配置的ak 权限不够：
- 提示把控制台连接让这个用户交给 cto 或者 运维主管登录控制台完成 fcdefaultrole 的授权
- 提示临时给 ak 增加 ramfull 权限， 完成这个指令后， 可撤销

**Comment by wss-git** [comment]
https://github.com/devsapp/fc-deploy/pull/85
