### ISSUE TITLE
s build 支持 custom build script

### ISSUE THREAD

**Issue by hryang** [devsapp/fc#200]
很多大型的项目，都有自己的 build script。比如流行的 AI 框架 PyTorch，推理部分的框架是 [TorchServe](https://github.com/pytorch/serve)。该项目提供了相关的脚本，只需要执行 `./build_image.sh` 再配合不同的参数就可以方便的生成 cpu/gpu 等不同环境的镜像，具体可参考[项目文档](https://github.com/pytorch/serve/blob/master/docker/README.md)。

今天的 s build 在支持 custom container 的时候，强行要求用户提供对应的 Dockerfile，然后根据 Dockerfile 来 build 镜像。但对于 TorchServe 这样的大型项目，这种方式不能很好的和项目内置的镜像生成方式集成。比如一个 TorchServe 的用户，要在 FC 上运行，是没有办法很顺畅的用 s build，s local invoke 在本地构建和调试好镜像后，再 deploy 到 FC 上。

理想的用户体验是 s build 提供一个选项，能够调用用户传入的自定义 build 脚本，完成镜像的构建。再 s local start/invoke 调试完成，再把镜像推到 ACR 上去。这样整个过程都能在 s 中闭环，和原有项目的体验无缝集成。

**Comment by rsonghuster** [comment]
目前有一个 workaround 的做法，如下图

![image](https://user-images.githubusercontent.com/10919599/130399488-4deefb0c-182f-41f9-aaca-29316aa3b584.png)

**Comment by heimanba** [comment]
新的build能力已经支持,文档地址
https://docs.serverless-devs.com/fc/command/build
