### ISSUE TITLE
s proxied invoke 支持非 9000 端口

### ISSUE THREAD

**Issue by hryang** [devsapp/fc#201]
如果 custom container 使用非 9000 端口，执行 s proxied setup 会收到如下错误：

Message:  Proxied invoke only support caPort: 9000 for custom-container/custom runtime.Please change it temporarily and retry.

为什么要有这个限制？FC 目前都支持任意端口，这里有这个限制是有问题的。

**Comment by rsonghuster** [comment]
https://github.com/devsapp/fc/issues/119  这个 issue 在跟踪， 已经完成部分， 代理容器部分完成， 工具侧预计下周会发布新版本修复

**Comment by git-qfzhang** [comment]
Fix: https://github.com/devsapp/fc-proxied-invoke/pull/17
