### ISSUE TITLE
针对 custom container  s deploy -h 提示不足

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#202]
![image](https://user-images.githubusercontent.com/10919599/129449235-276c11b2-ed90-45dc-82d1-0c6b142e0783.png)

![image](https://user-images.githubusercontent.com/10919599/129449243-d98fc52b-ca76-479c-9af0-34045ea5eb97.png)

针对 custom container  s deploy -h 提示不足，应该把自动推送 acr 镜像的能力在 help 中也提示出来

**Comment by rsonghuster** [comment]
或者说，针对 custom container 这个 runtime，  s deploy 的时候， 镜像就直接 push 到 acr

**Comment by git-qfzhang** [comment]
Related to Issue #208
