### ISSUE TITLE
更加用户友好的 s local start 端口不正确导致请求 hang 的错误信息

### ISSUE THREAD

**Issue by hryang** [devsapp/fc#203]
使用 custom container，镜像是 registry.cn-hangzhou.aliyuncs.com/yhr-work/torchserve ，这是使用 pytorch 深度学习推理框架的镜像。镜像在构建时 expose 8080 等端口。我在 s.yaml 中故意把 caPort 错误地设成 9000，无论是本地和线上，请求都是不通的，但本地和错误信息都对问题调查没有帮助。

执行 s local start auto 启动本地调试实例后，通过 curl http://localhost:xxxx/ping 对该 web 应用发起调用，最后会出现 socket hang up 的错误。
![image](https://user-images.githubusercontent.com/626967/129479700-fa871b4c-7439-4380-a5bc-35288f8e9444.png)

上图所示的 s local 的错误信息输出（红字部分），建议进行如下的优化：
1. 错误信息的头部加上标识信息，表示这是 s local 输出的信息。这在混杂了实例应用本身的输出信息时更容易区分。
2. 如果是 socket hang up 的错误，是否能加上提示信息。比如“Please make sure your container expose port is the same as caPort in s.yaml. “。如果用户提供了 Dockerfile，我们应该可以查找 expose 关键词，和 caPort 对比。再加上更详细的的错误信息。比如 “Your Dockerfile expose port X, but caPort is Y.  ”

**Comment by wss-git** [comment]
已做优化提示
![image](https://user-images.githubusercontent.com/56686088/158752307-1637f206-c56f-4045-9816-2c198359f3c5.png)
