### ISSUE TITLE
s build 容器镜像时不需要 --use-docker 参数

### ISSUE THREAD

**Issue by hryang** [devsapp/fc#204]
当 runtime 类型是 custom container 时，使用 s build 容器镜像还要求用户加上 --use-docker 参数没有意义。

**Comment by rsonghuster** [comment]
![image](https://user-images.githubusercontent.com/10919599/131312891-94265e33-f934-4647-8e9e-a0d362a22f90.png)

这个看起来目前还没有 fix

**Comment by rsonghuster** [comment]
已经验收， OK
