### ISSUE TITLE
s proxied invoke 支持自定义域名

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#206]
rt:
s proxied invoke 支持自定义域名

**Comment by git-qfzhang** [comment]
目标函数配置了自定义域名，那么辅助函数需要配置 auto custom domain，然后 `s invoke` 时传入具体的 auto 生成的域名，就能支持自定义域名的调用。

**Comment by rsonghuster** [comment]
经过测试， 验收， 是已经支持 ok 了
