### ISSUE TITLE
s deploy 自动 push 镜像到仓库

### ISSUE THREAD

**Issue by hryang** [devsapp/fc#208]
在使用 custom container 时，用户要将本地镜像更新到云端镜像仓库，需要使用 s deploy --push-registry-acr-internet 这个参数。这里的体验有两个问题：
1. 大部分用户习惯了 s deploy 其他资源，但是镜像的 deploy 需要加一个其他参数，体验是割裂的。
2. 这个参数名字中带有 acr，其他云的镜像仓库未必叫 acr。

在讨论优化方案之前，先对齐一点：今天基于 s.yaml 原生的 deploy 方式并不是 IaC。比如 s deploy 并不删除资源。不管这种设计是否正确，看起来我们已经改不了这个行为了，因为兼容性的问题不好解决。

基于上面的行为，看起来 s deploy 自动判断是否要更新镜像看起来是可以做到的：
1. 检查本地是否有镜像，以及 checksum 是否和云端一致。
2. 如果不一致，自动更新镜像。
3. 如果一致，则不更新镜像。

这个逻辑和 FC 资源处理逻辑是类似的。

**Comment by git-qfzhang** [comment]
> 在使用 custom container 时，用户要将本地镜像更新到云端镜像仓库，需要使用 s deploy --push-registry-acr-internet 这个参数。这里的体验有两个问题：
> 
> 1. 大部分用户习惯了 s deploy 其他资源，但是镜像的 deploy 需要加一个其他参数，体验是割裂的。
> 2. 这个参数名字中带有 acr，其他云的镜像仓库未必叫 acr。
> 
> 在讨论优化方案之前，先对齐一点：今天基于 s.yaml 原生的 deploy 方式并不是 IaC。比如 s deploy 并不删除资源。不管这种设计是否正确，看起来我们已经改不了这个行为了，因为兼容性的问题不好解决。
> 
> 基于上面的行为，看起来 s deploy 自动判断是否要更新镜像看起来是可以做到的：
> 
> 1. 检查本地是否有镜像，以及 checksum 是否和云端一致。
> 2. 如果不一致，自动更新镜像。
> 3. 如果一致，则不更新镜像。
> 
> 这个逻辑和 FC 资源处理逻辑是类似的。

我认为这里默认推送镜像是没问题的，但是不需要去比对线上和线下镜像的 sha256 值，因为 docker 自身就有检测机制，所以这里是不需要做这层检测的

**Comment by git-qfzhang** [comment]
Fix: https://github.com/devsapp/fc-deploy/pull/84

**Comment by rsonghuster** [comment]
s deploy 自动 push 镜像到仓库已经完成
