### ISSUE TITLE
s init django 的例子在深圳有问题

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#213]
https://github.com/devsapp/start-django/blob/master/src/s.yaml#L13
暂时改成杭州， 可以部署， 如果是深圳， 出现如下错误：

![image](https://user-images.githubusercontent.com/10919599/129854216-0f4e4336-cb03-4702-8292-d53aadeeb32b.png)

**Comment by wss-git** [comment]
我这边没有复现，是使用 s init devsapp/start-django  然后再部署吗？  不过看起来是服务权限不够

**Comment by wss-git** [comment]
如果可以再帮忙跑一下呗

**Comment by rsonghuster** [comment]
目前是：
-  fc-demo 这个账号在 杭州、 上海没有问题
-  其他账号在深圳没有问题

**Comment by rsonghuster** [comment]
问题定位清楚， 是 fc-demo 这个账号在深圳 region 没有默认被关闭支持 public acr image 的能力
