### ISSUE TITLE
s build 需要有不依赖 docker deamon 完成 build 的能力 

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#214]
s build 需要支持 buildkit 的能力， 云原生大环境下，  很多都是跑在容器内， 比如 cicd 集成了 S,  但是不能执行 s build 完成 fc 的构建， 能支持的场景将会大大减少

https://github.com/moby/buildkit

**Comment by git-qfzhang** [comment]
最新版本已经支持。https://github.com/devsapp/fc-build/pull/14
