### ISSUE TITLE
s deploy 出现 serviceName 限制错误， 和 FC 限制说的 128 不匹配

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#218]
![image](https://user-images.githubusercontent.com/10919599/130019749-b0aec4cb-dbbd-4a02-814b-0c8a27896db5.png)

s deploy 出现 serviceName 限制错误， 和 FC 限制说的 128 不匹配

**Comment by rsonghuster** [comment]
![image](https://user-images.githubusercontent.com/10919599/130019860-65afe3a1-434c-4665-b659-fe83a4b01735.png)

**Comment by git-qfzhang** [comment]
生成 auto 配置时，在资源名称长度限制内，更改命名规则为 ${serviceName 前 6 位}-${定长hash(serviceName)}-${region} 。
主要涉及的产品有：
sls
nas
vpc
ram

**Comment by wss-git** [comment]
${serviceName 前 6 位}-${定长hash(serviceName+uid)}-${region}

**Comment by rsonghuster** [comment]
https://qastack.cn/programming/4567089/hash-function-that-produces-short-hashes

hash 可以考虑这个方案

**Comment by wss-git** [comment]
https://github.com/devsapp/fc-deploy/pull/85
