### ISSUE TITLE
s layer publish 之后的产物不能开箱即用

### ISSUE THREAD

**Issue by wss-git** [devsapp/fc#225]
### 场景1(nodejs)：文件目录结构如下：
|- index.js
|- package.json
|- node_modules

按照习惯，我们会直接执行 s layer publish --code ./node_modules， 这个时候我们是可以上传成功的，但是此时是不可直接使用的状态，必须增加一个 NODE_PATH 为 /opt 的环境变量才可以使用

经过查看[文档](https://help.aliyun.com/document_detail/193057.html)， 我们预期的目录结构必须是下面这个，然后执行 s layer publish --code ./<外层文件夹名称> ，这个时候才能直接使用这个 layer 目录
|- index.js
|- package.json
|- <外层文件夹名称>/nodejs/node_modules

### 场景2(python): 这个和场景一极其类似，文档中是这样描述的
<b>系统部署层时，会将/opt/python或/opt/python/lib/python{}.{}/site-packages添加到Python的sys.path内</b>

###  layer 衍生出来的其他问题
如果用户配置了 NODE_PATH，此时用户配置了layer，其实他的寻找 layer 路径一般都是不对的

综上所述，大家有一个好的想法吗？目前虽然使用的用户比较少，但是这个功能感觉在后期可能会承担一个比较重要的位置，所以希望能够在优化一下

**Comment by rsonghuster** [comment]
这个我理解是各自语言的行为， 可以参考下 s build 的做法呢？  

- 比如 python

![image](https://user-images.githubusercontent.com/10919599/130248772-7a7fdd91-2fb3-4426-b84f-d282ef583d28.png)

s build 之后， 在交付物目录中， 也是有 python  或者 python/lib/python{}.{}/site-packages 目录的

- nodejs 确实奇怪， 按道理应该就是 node_modules， 但是既然 nodejs runtime 的实现采用了这个目录结构，那我们是不是应该尝试兼容下

**Comment by wss-git** [comment]
后面改造，可以将这个考虑进去：  https://github.com/devsapp/fc/issues/224
