### ISSUE TITLE
nas 增量部署

### ISSUE THREAD

**Issue by wss-git** [devsapp/fc#233]
实现思路：创建一个缓存文件，记录文件路径，以及hash值；和上次做判断，如果修改了则修改

问题： 删除了文件怎么办...

**Comment by git-qfzhang** [comment]
增量同步的机制也类似， 我是在客户端生成一个 _files 文件，记录所有上传文件的路径和md5信息，然后再下次上传的时候，从服务端去取一下上次上传的_files文件信息，然后对比一下，忽略那些没有改动的文件，将修改的文件上传就可以啦，这样速度会快非常多。

**Comment by git-qfzhang** [comment]
这个 _files 文件是json数据格式  :)    选 hasha 做hash就可以。 最好使用 `hasha.fromFile(filePath, { algorithm: 'md5' })` ， 这样和OSS object的etag是一致的

**Comment by wss-git** [comment]
https://github.com/devsapp/fc/issues/629
