### ISSUE TITLE
build 性能优化

### ISSUE THREAD

**Issue by git-qfzhang** [devsapp/fc#235]
性能优化有如下两点：

1. 对于源代码部分，将 codeUri 复制到 build 目录时，以同步的方式进行复制，每次只复制新增的文件/改动的文件，同时要保证 codeUri 中的内容与 build 目录中源码内容保持一致，即若 codeUri 中删除了文件 a，则 build 目录中也需要将其删除。
2.  对于依赖部分，目前基于 nodejs 的 package.json 安装依赖的部分以及基于 python 的 requirements.txt 安装依赖的部分没有缓存机制，导致在每次 build 时，即便 package.json/requirements.txt 内容没有更改，也会重复安装依赖，这部分缓存机制需要调研，了解 fun 为什么当时没有做这部分，而对于 apt 包有缓存机制。

**Comment by wss-git** [comment]
1. 代码的复制和依赖的复制都是依赖 '@alicloud/fc-builders' 做的 https://github.com/devsapp/fc-build/blob/master/src/utils/builder.ts#L174-L183 ，我们如果要做修改，需要再看看这块代码 或着重新发一个包

**Comment by git-qfzhang** [comment]
> 1. 代码的复制和依赖的复制都是依赖 '@alicloud/fc-builders' 做的 https://github.com/devsapp/fc-build/blob/master/src/utils/builder.ts#L174-L183 ，我们如果要做修改，需要再看看这块代码 或着重新发一个包

这里应该是要改造 fc-builder 了。@alicloud/fc-builders 会将 build 目录删除吗，还是说这个动作是 fc-build 组件做的？

**Comment by rsonghuster** [comment]
请参考  #189  各自语言安装依赖包和 apt-get 的安装速度已经优化完毕， 使用  fc-docker 1.9.20  版本即可， 后续需要做的事情， 就是  package.json   requirements.txt  composer.json 没有变化的时候做缓存机制， 类似 funfile 的效果

**Comment by rsonghuster** [comment]
build-link 功能有了以后， 实现 funfile 效果优先级就不高了， 理由如下：

- 针对编译型语言， 比如 java,  本身每次就需要编译， 只要优化好 maven 编译速度和提前下载好依赖的库即可

- 对于解释型语言， s build 就是安装依赖， 只要依赖不变， 不需要每次都执行 s build 命令
