### ISSUE TITLE
S 工具中所有的辅助函数尽量复用 FCDefaultRole

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#237]
https://github.com/devsapp/fc/issues/197  这个 issue 完成后，所有的辅助函数都尽量复用 FCDefaultRole

- 端云联调辅助函数

- nas 辅助函数

- 远程调试辅助函数

- 其他场景， 比如之前的一些 web 框架组件， 是不是https://github.com/devsapp/fc/issues/197  这个完成， 自动就解决了这个创建  role 的 问题

**Comment by wss-git** [comment]
- 所有的辅助函数都尽量复用 FCDefaultRole

其他两个不知道，但是 nas 辅助函数和正常的函数使用同一个角色就可以了

**Comment by wss-git** [comment]
@git-qfzhang 看看 端云联调 和远程调试呢

**Comment by git-qfzhang** [comment]
远程调试没有辅助函数，端云辅助函数可以复用这部分使用 role 的方案

**Comment by git-qfzhang** [comment]
只要辅助函数使用了 fc-deploy 组件进行部署，那么就已经复用了 AliyunFcDefaultRole

**Comment by rsonghuster** [comment]
目前看起来有已经完成的组件有：

- 端云联调

- 压测组件

- Power Tunning 组件
