### ISSUE TITLE
s yaml 规范中不支持表格存储触发器

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#238]
https://github.com/alibaba/funcraft/blob/master/docs/specs/2018-04-03-zh-cn.md#tablestore

表格存储触发器， 已经和FC 进行双向集成， 和 oss 触发器类似， 这个开发代价应该较小些

**Comment by git-qfzhang** [comment]
https://github.com/devsapp/fc/commit/c5e6272aa5587271dde30f362535340521be9f72

**Comment by git-qfzhang** [comment]
已经集成，文档正在 review 阶段： https://github.com/devsapp/fc/pull/318

**Comment by rsonghuster** [comment]
已经完成
