### ISSUE TITLE
nas 相关的命令辅助函数优化

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#250]
![image](https://user-images.githubusercontent.com/10919599/131092948-d0a138ae-7543-4b68-9a03-06656d6a860a.png)

nas 相关的命令， 不需要每次都强制更新辅助函数， 体验有点差， 可以通过代码包的 md5 或者自己设置版本标签， 决定是否更新函数

**Comment by wss-git** [comment]
现在流程如下（未发布）：
- 如果 deploy 或者 init 指令: 确保 nas dir，部署辅助函数
- 如果是 upload/download：确保 nas dir 存在、辅助函数存在，并且配置是最新的
- 如果是 ls/command 确保辅助函数存在，并且配置是最新的

**Comment by rsonghuster** [comment]
已经发布
