### ISSUE TITLE
S  custom container 相关的示例， 可以去除 policy 相关了

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#252]
#197 这个优化之后，custom container 相关的示例， 可以去除 policy 相关了， 不需要依赖 s 配置的 ak 要有 ram full access， 如下

![image](https://user-images.githubusercontent.com/10919599/131106396-f04dc68e-99c4-41b1-9c91-587e43806ecb.png)

目前已知的有：

-  custom container 大客户解决方案示例  +  hello world 入门   西流

- web framework 框架统一改一下吧，  守帅

**Comment by wss-git** [comment]
对于部署 web framework ，统一使用的是透传到fc部署，对于权限部分不需要做修改

**Comment by rsonghuster** [comment]
我指的是 yml 中不需要写：

![image](https://user-images.githubusercontent.com/10919599/131298328-6fd1cb39-567f-4e98-9dfd-c28a1ed90430.png)

不然的话， 会需要 ram create role 权限去创建一个 role

**Comment by rsonghuster** [comment]
custom container 大客户解决方案示例 + hello world  已经完成
