### ISSUE TITLE
build，local invoke,   proxied invoke  都需要支持 layer 

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#253]
目前 layer 只是支持 deploy,   但是实际上 layer 是跟整个函数的开发调试都是息息相关的，因此  build，local invoke,   proxied invoke  都需要支持 layer

**Comment by rsonghuster** [comment]
目前 layer 这个功能只支持 nodejs 和 python， 计划11月份支持其他语言

等后端支持了 nodejs, python, java， php ， 工具再统一搞吧

**Comment by wss-git** [comment]
https://github.com/devsapp/fc-layer/pull/9/files 
https://github.com/devsapp/fc-local-invoke/pull/45

**Comment by wss-git** [comment]
已支持

**Comment by chnyangjie** [comment]
> 已支持

请问在哪个版本会正式发布？
