### ISSUE TITLE
s.yml文件中，关于代码包大于50M小于100M该怎么上传

### ISSUE THREAD

**Issue by liulang0817** [devsapp/fc#259]
![image](https://user-images.githubusercontent.com/38310830/131479247-ffb1053b-7e16-4d18-83f1-531aeb0ec4e0.png)
这个s.yml文件中的bucket属性和osskey属性该怎么填，需要详细说明下

**Comment by liulang0817** [comment]
> 这是文档缺失问题，需要补充如下几种代码包规格情况下的部署文档：
> 
> 1. (50M, 100M]
>    
>    * 手动传输代码包到 oss，然后手动将 s.yml 中的 `ossBucket` 和 `ossKey` 填充
>    * 指定 s.yml 中的 `codeUri` 和 `ossBucket` 字段，后者需要填写一个已存在的 bucket
> 2. 大于 100M
>    
>    * 将 nasConfig 配置为 auto，然后基于 nas 指令将大文件（可能是训练集/依赖包）传输到 nas 指定位置，然后配置相应的环境变量到 s.yml 中的函数配置中，然后部署函数，可以基于 .fcignore 文件来忽略传输到 nas 上的文件
>    * 基于 layer 指令创建 layer ，然后将 layer 的配置填充到 s.yml 中的函数配置中，最后部署函数
>    * 将非 custom-container 的函数转换成 custom-container，这需要对代码进行一定的改造，并新增 dockerfile，然后创建这个函数
大佬6666，在fun 工具中使用nasConfig：auto会自动配置环境变量，那在s工具中会自动配置环境变量吗？

**Comment by liulang0817** [comment]
大佬6666，在fun工具中配置nasConfig：auto会自动配置环境变量，那使用s工具不会自动配置环境变量了吗？

**Comment by whaohan** [comment]
大代码包部署示例：

猫狗分类：https://github.com/awesome-fc/cat-dog-classify
情绪识别：https://developer.aliyun.com/article/785367
