### ISSUE TITLE
【fc-core】build 增加环境检测

### ISSUE THREAD

**Issue by git-qfzhang** [devsapp/fc#262]
build 在不使用 docker 时会依赖本机环境进行构建，但是当用户环境未准备好时，报错信息对用户不友好，例如在构建 python 项目时，若没有安装 pip，则会出现如下报错：

![image](https://user-images.githubusercontent.com/52195264/131507318-88d22cc9-91db-43ae-bb71-dbb138b24dfc.png)

期望在进行构建前检测增加环境检测动作，若环境没准备好，则对用户进行友好的提示。包括执行 `s build -d` 时，若本地环境中的 docker 未正常运行，也需要进行友好的提示。

**Comment by git-qfzhang** [comment]
这些检测最好抽象出来一个个方法，这样方便其他组件复用

**Comment by rsonghuster** [comment]
如果 runtime 是 python3,  但是本地环境是python2.7,  这个时候它也可以是可以有  pip 的命令行工具的。 这个时候， 其实不应该只是单独检测 pip， python 的版本， 应该也是需要简单检测下的， 至少  2  和 3 两个大版本需要区分

**Comment by git-qfzhang** [comment]
优先支持如下几种环境检测：

1. nodejs
2. python
3. docker
4. java

**Comment by git-qfzhang** [comment]
将该能力放到 [fc-common 组件](https://github.com/devsapp/fc-common) 中

[mr](https://github.com/devsapp/fc-common/pull/1)

**Comment by git-qfzhang** [comment]
待 fc 组件集成

**Comment by rsonghuster** [comment]
后续集成一个重要的组件集成， 然后把 pr diff 贴在这里， 再列出来其他需要接入的子组件列表

**Comment by wss-git** [comment]
s build 如果需要使用本地环境，需要检测一下  已经完成 待发布

**Comment by wss-git** [comment]
build 使用本地环境检测机制已经发布
