### ISSUE TITLE
deploy/remove trigger 时，支持指定多个 trigger

### ISSUE THREAD

**Issue by git-qfzhang** [devsapp/fc#268]
目前 deploy/remove trigger 时，只支持指定单个目标 trigger，期望支持指定多个 trigger

**Comment by git-qfzhang** [comment]
目前 sdk 底座已经支持

**Comment by rsonghuster** [comment]
> 目前 sdk 底座已经支持

sdk 底座已经支持，pulumi 底座不支持？  是这个意思吗
