### ISSUE TITLE
基于自定义 endpoint 的 fcClient 获取能力组件化

### ISSUE THREAD

**Issue by git-qfzhang** [devsapp/fc#270]
fc 系列的一些组件需要基于用户自定义 endpoint 去获取 fcClient ，这需要对每一个组件进行一次相同的适配，才能使得 fc 系列的功能支持自定义 endpoint，而如果自定义 endpoint 的配置策略有变化，那么每个组件都需要进行修改，因此需要将这部分能力抽出来，用组件来承载，从而来避免重复的组件适配工作。

**Comment by git-qfzhang** [comment]
https://github.com/devsapp/fc-common

**Comment by git-qfzhang** [comment]
待 fc 系列组件集成

**Comment by rsonghuster** [comment]
#331

**Comment by rsonghuster** [comment]
已经有 issue 跟踪
