### ISSUE TITLE
将部署辅助函数的逻辑集成到 fc-common 组件中

### ISSUE THREAD

**Issue by git-qfzhang** [devsapp/fc#279]
部署辅助函数的通用逻辑：

1. 基于 AliyunFcDefaultRole 部署函数
2. 若部署失败且 AliyunFcDefaultRole 不存在，则尝试创建 AliyunFcDefaultRole
3. 基于 AliyunFcDefaultRole 部署函数

部署的流程是：

1. 尝试创建操作
2. 若创建失败且线上已经存在则更新函数（是否增加版本控制来避免无效的更新操作，版本控制对于 event 函数如何做？是否能够通过函数创建时间来做？）

**Comment by git-qfzhang** [comment]
nas 和 stress 辅助函数部署需要基于 fc-deploy 进行，这样具有 role 的处理逻辑

**Comment by git-qfzhang** [comment]
nas 和 stress 辅助函数部署需要基于 fc-deploy 进行，这样具有 role 的处理逻辑

**Comment by rsonghuster** [comment]
@git-qfzhang 目前这个进展是什么？

**Comment by wss-git** [comment]
现在的辅助函数都基于 fc-deploy 组件， fc-deploy 已经具有了 role 的处理逻辑
