### ISSUE TITLE
Typo? `tarnsform` or `transfrom` or `transform` ?

### ISSUE THREAD

**Issue by DevDengChao** [devsapp/fc#280]
`transform` 这个单词在仓库中出现了多种变体, 并且在多个文件中都有出现, 以至于我不太确定这到底是由于误拼导致的还是本意就是如此. 🤣 

(刚刚在翻阅源码, 并且有[进行中的 PR ](https://github.com/devsapp/fc/pull/276)待处理, 一时半会儿不知道是不是该修改这些错字...

**Comment by git-qfzhang** [comment]
> `transform` 这个单词在仓库中出现了多种变体, 并且在多个文件中都有出现, 以至于我不太确定这到底是由于误拼导致的还是本意就是如此. 🤣

能麻烦贴一下变体的示例，并表达你的问题吗，这个用了有什么问题

**Comment by DevDengChao** [comment]
> 能麻烦贴一下变体的示例
+ https://github.com/devsapp/fc/search?q=tarnsform
+ https://github.com/devsapp/fc/search?q=transfrom

> 表达你的问题
仓库里可能出现了错误拼写的单词.

> 这个用了有什么问题
单纯从功能性上来讲, 错误拼写的单词并不影响用户正常使用各个功能.

**Comment by git-qfzhang** [comment]
> > 麻烦贴一下变体的示例
> 
> * https://github.com/devsapp/fc/search?q=tarnsform
> * https://github.com/devsapp/fc/search?q=transfrom
> 
> > 表达你的问题
> 
> 仓库里 (可能) 出现了错误拼写的单词.
> 
> > 这个用了有什么问题
> 
> 单纯从功能性上来讲没有任何问题, 毕竟错误拼写的单词并不影响用户正常使用各个功能.

看起来是拼写错误😂，应该统一为 transfrom

**Comment by DevDengChao** [comment]
> 应该统一为 transfrom

那我就在 https://github.com/devsapp/fc/pull/276 里继续提交了啊.
