### ISSUE TITLE
s local invoke python 环境上面额外打印null

### ISSUE THREAD

**Issue by anycodes** [devsapp/fc#281]
s local invoke python 环境上面这个问题，
python 初始化函数什么都没做，s.yaml 带上初始化函数就会凭空多一个null，initializer 去掉就没有
已经排除自身函数打印

测试环境：上海地区，本地测试的，没有部署上线，python3 环境 使用的 s 工具

![image](https://user-images.githubusercontent.com/21079031/131969976-0a241176-1f7f-4a41-a10e-2fdc619b694a.png)

来自群用户@李相龙

**Comment by anycodes** [comment]
1. 线上的话，会不会也打印这个null
2. 如果线上不会打印这个null，那么开发者工具的local模式也不应该，因为这里要尽可能的和线上保持一致性

**Comment by liulang0817** [comment]
![image](https://user-images.githubusercontent.com/38310830/131970907-83ea132c-d26a-435a-82b5-0549d91ea1ec.png)
测试确实有null

**Comment by liulang0817** [comment]
![image](https://user-images.githubusercontent.com/38310830/131973319-ee892f58-9e11-4b89-8f1e-2d233e6f9537.png)
![image](https://user-images.githubusercontent.com/38310830/131973304-70c4ced3-6abe-4e27-bedf-0f9ea415ea93.png)
我部署到线上了，这个return没有打印，本地执行确实打印了，不知道这个是工具问题还是其他啥问题

**Comment by rsonghuster** [comment]
这个其他 runtime 也有类似问题吗

**Comment by wss-git** [comment]
有的，例如 node
`````
exports.initializer = (context, callback) => {
    callback(null, '==== initializer ====');
}
````
