### ISSUE TITLE
build .funignore 也会生效

### ISSUE THREAD

**Issue by wss-git** [devsapp/fc#283]

**Comment by rsonghuster** [comment]
这个不是兼容fun 的吗？ 这个会有什么问题吗？

**Comment by DevDengChao** [comment]
我这边用 2.0.80 版的 `s` 测试发现 `s build` 会受 `.funignore` 里的规则影响, `s deploy` 会受 `.fcignore` 影响 🤣

**Comment by rsonghuster** [comment]
> 我这边用 2.0.80 版的 `s` 测试发现 `s build` 会受 `.funignore` 里的规则影响, `s deploy` 会受 `.fcignore` 影响 🤣

 s deploy 受 .funignore 影响吗？

**Comment by DevDengChao** [comment]
> > 我这边用 2.0.80 版的 `s` 测试发现 `s build` 会受 `.funignore` 里的规则影响, `s deploy` 会受 `.fcignore` 影响 🤣
> 
> s deploy 受 .funignore 影响吗？

刚刚测试了一下, `s deploy` 不受 `.funignore` 影响. ( s 2.0.82 )

**Comment by DevDengChao** [comment]
突然觉得保留这个 **特性** 也挺好 🤣 , 两个 ignore 文件分别对应两个阶段需要忽略的文件集, 构建过程根据 `.funignore` 忽略掉构建时不需要的各种说明文档啥的, 然后部署过程根据 `.fcignore` 忽略掉构建过程遗留下来的 `.fcignore`, `s.yaml`, `yarn.lock` 啥的.
