### ISSUE TITLE
nas command指令的使用方法与权限问题

### ISSUE THREAD

**Issue by raykie** [devsapp/fc#289]
首先，根据[nas指令操作文档](https://github.com/devsapp/fc/blob/main/docs/Usage/nas.md)，`s exec -- nas command ls -a nas:///mnt/auto1/folder`这条指令会报错`The path of nas was not found in [ls -a nas:///mnt/auto/]`。

当我改成`s exec -- nas command nas:///mnt/auto/ ls`，报错permission denied。在控制台查看挂载点，显示为默认权限组。

**截图**
![image](https://user-images.githubusercontent.com/51851458/132168535-bf287c25-334e-4387-97d3-75269d98a4d6.png)
![image](https://user-images.githubusercontent.com/51851458/132168550-52038323-8650-4ef3-9510-fd2e51fb1e33.png)
![image](https://user-images.githubusercontent.com/51851458/132168578-7206ba57-f8e9-48e7-a278-a0653c013422.png)

**OS**
centOS 7

**Comment by wss-git** [comment]
s exec -- nas command ls -a nas:///mnt/auto1/folder这条指令会报错The path of nas was not found in [ls -a nas:///mnt/auto/]。

yaml  nasConfig 里面的 fcDir 是否有包含 /mnt/auto1/folder 路径， 这个错误说没有找到这个目录的映射。 如果 nasConfig 配置的 auto，fcDir 默认是 /mnt/auto

**Comment by wss-git** [comment]
/mnt/auto/ ls , 这种写法还不支持哈，会报错没有权限的

**Comment by raykie** [comment]
@wss-git 我的nasConfig是用的auto，但还是找不到/mnt/auto，这个需要在s.yaml里额外配置吗
![image](https://user-images.githubusercontent.com/51851458/132829892-05eee60e-054e-47b5-950a-5554025672d3.png)

![image](https://user-images.githubusercontent.com/51851458/132829849-78ad5fda-1c5e-4455-87f5-d94ef68cf1f2.png)

![image](https://user-images.githubusercontent.com/51851458/132829972-f5d82526-ca83-4659-91e5-7344cf15ad37.png)

**Comment by wss-git** [comment]
1. 之前的写法 -a， 是属于系统指令，解析的时候会将后面所有的参数导致丢失【这个暂时没有办法解】

2. s nas command 'ls -al nas:///mnt/auto'，如果加上  ''  看来是不支持非 nas:// 的写法 , 'ls -al nas:///mnt/auto' 会导致这个参数解析有些问题，这个之前没有考虑到【这个写法后头看看怎么解决，或者标明不支持】


可以换成这四种写法：

s nas command 'ls -al nas:///mnt/auto'  或者 s exec -- nas command 'ls -al nas:///mnt/auto' 

s nas command ls -al /mnt/auto 或者 s exec -- nas command ls -al /mnt/auto

**Comment by raykie** [comment]
实践后表明后两种写法可以成功查看
![image](https://user-images.githubusercontent.com/51851458/132839448-2277044c-7c06-4b38-9de7-e29c8ed68826.png)
