### ISSUE TITLE
没有s.yml文件执行命令会出现如下报错

### ISSUE THREAD

**Issue by liulang0817** [devsapp/fc#304]
![image](https://user-images.githubusercontent.com/38310830/133040219-0026fd2c-cc0f-4546-8d0b-7fed05177418.png)
当目录下没有s.yml文件时会出现如图所示的报错，没理解这个报错是什么意思。
发现我的目录下有一个template.yml文件，删除这个文件后执行正常了，看着是执行s build -h是走了template.yml文件，但是我理解不应该走template.yml，就算没有s.yml文件也是应该报一个不是s.yml项目错误
![image](https://user-images.githubusercontent.com/38310830/133040135-abb9bce1-0fe4-4976-b61a-0ec46182c37a.png)

**Comment by xsahxl** [comment]
![image](https://user-images.githubusercontent.com/21330840/133045049-9051f47c-7e89-4991-9de3-e547b8183a0a.png)
这种yaml文件是不符合规范的。具体可以看下 https://www.serverless-devs.com/docs/yaml，可以对报错进行优化。
后续s需判断yaml文件里的内容来判断是否为s项目，以是否存在 edition 字段作为判断依据

**Comment by xsahxl** [comment]
代码排查后发现，已有方法 检查 yaml文件是否符合s规范，旧版本检查 Component, Provider, Properties字段, 新版本检查component，props字段。只是有些case没有加这个逻辑，后续会加这个逻辑

**Comment by xsahxl** [comment]
fix https://github.com/Serverless-Devs/Serverless-Devs/commit/7a8e4c9afd48f04d04476c4adf77bca8f388eb4e

**Comment by xsahxl** [comment]
fix #https://github.com/Serverless-Devs/Serverless-Devs/commit/e2a9177f22906425992c30e3ed69b7b573f89af6
