### ISSUE TITLE
s build 错误不提示

### ISSUE THREAD

**Issue by git-qfzhang** [devsapp/fc#305]
s build -d 在安装依赖时，若出现错误，则不会提示，并出现 undefined 字样：

![image](https://user-images.githubusercontent.com/52195264/133069426-9433e37f-adc6-4d42-adc9-6de68a15d1d8.png)

复现步骤：

1. s init 一个 python 的 hello world 项目
2. 在项目中新增 requirements.txt，内容如下：
```
ssl
```
3. 执行 `s build -d`

**Comment by rsonghuster** [comment]
已经验收， 确实没有这个错误了
