### ISSUE TITLE
nas 组件上传文件可能存在的问题

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#306]
nas 组件上传文件， 我们自己实现了分片上传的优化， 但是依赖了一个假定， 就是每个分片一直调用的都是辅助函数的同一个实例。 当使用同一个主账号的两个开发者同时执行 nas 组件上传， 应该是有问题的。

1. 直接设置复制函数的最大实例数目为1， 保证正确性， 但是某个时刻， 最多只有一个上传任务执行
2. 多个辅助函数，当调用默认的辅助函数(最大实例数目已经设置为1)出现 429 限流， 是不是应该新建一个辅助函数， 完成并发上传的任务

**Comment by wss-git** [comment]
上传文件是直接上传到 nas 的，除非是两个开发着者同时上传同一个文件，所以这个问题一般是不会存在的
