### ISSUE TITLE
工具报错 includes of undefined

### ISSUE THREAD

**Issue by wss-git** [devsapp/fc#307]
![image](https://user-images.githubusercontent.com/56686088/133363218-25261a6a-1b9c-4ffd-bc0c-5b190d6e4c0f.png)
![image](https://user-images.githubusercontent.com/56686088/133363244-01a42d35-2348-40d9-97d1-124f421d7800.png)

复现步骤：
await new Promise((resolve, reject) => reject(''))
原因：
理解应该是这个原因，因为异常了，但是 catch 的异常是字符串 并不是个对象

![Uploading image.png…]()

**Comment by xsahxl** [comment]
s在2.0.85版本后完善了error逻辑，此问题也顺便修复了。
