### ISSUE TITLE
fc-deploy auto role 的生成策略

### ISSUE THREAD

**Issue by git-qfzhang** [devsapp/fc#308]
目前 role 的生成策略是：

1. 对于未填写 role 但是服务/函数/触发器需要相关权限的，例如服务配置了 vpc，此时 fc-deploy 会自动为用户配置 `AliyunFCDefaultRole`
2. 对于填写了 role，且格式为：
```
role:
    name: string;
    policies?: Array<string | CustomPolicyConfig>;
```
fc-deploy 会在用户定义的 policy 的基础上，基于服务/函数/触发器配置，列出需要的相关权限，并追加到这个 role 的 policy 中，然后创建这个 role。
3. 对于填写了完整 role arn 配置，不做任何处理

对于第一种情况，部署完成后，fc-deploy 会将 role 缓存在本地，下次部署时，若用户仍未指定 role，则仍然会使用这个 role，这样会产生一个问题，即用户在下次部署时，若将需要权限的配置项都删除了，此时无需使用 role，就不需要使用这个 role 了，因此在使用缓存 role 时，需要判断此时的配置是否需要 role。

**Comment by rsonghuster** [comment]
已经完成发布
