### ISSUE TITLE
deploy 时应该为全量更新

### ISSUE THREAD

**Issue by git-qfzhang** [devsapp/fc#310]
目前 deploy 时不是全量更新，例如首次部署服务 A 时为其配置了 role；二次开发完成后，将 s.yml 中的 role 字段删除，再部署后，预期行为应该是线上服务的这个 role 配置会被删除，而实际行为是这个 role 仍然存在

**Comment by rsonghuster** [comment]
这个新的 fc-deploy 解决了这个问题吗
