### ISSUE TITLE
s build --use-local 应该能支持 apt-get.list

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#311]
s build --use-local 应该能支持 apt-get.list,   可以先检查本地是不是 debian/ubantu 系的 linux 系统， 如果是， 应该可以支持 s build --use-local

**Comment by wss-git** [comment]
// await this._exec(['sudo', 'apt-get', 'install', '-y', '-d', `-o=dir::cache=${this.cacheDir}`, ...pkgName, '--reinstall', '--no-install-recommends']);

**Comment by wss-git** [comment]
现支持了浏览器的 apt-get.list 功能
