### ISSUE TITLE
针对测试集群，  s config 的设置问题

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#331]
目前全局 endpoint 的设置是全局的， 依赖 fc-default 组件， 对于新用户来说， 路径不是很友好， 首先他需要知道组件的概念， 其次他要知道 fc-default 组件， 最后 ~/.s/access.yaml 中也没有最后设置的东西， 非常不符合用户的预期

1. 直接在 access 里面支持 endpoint 字段， 之前是有规划的， 集成到 fc-common 中， 但是还没有完成
2. 测试集群 s deploy 和 s start 生成和使用的 http trigger 的 url 是测试域名的版本

**Comment by rsonghuster** [comment]
压测组件和 eval 探测组件， 辅助函数也要考虑自定义 endpoint 的问题， 确保内部用户跟公有云用户体验一致

**Comment by rsonghuster** [comment]
#157

**Comment by rsonghuster** [comment]
目前压测组件和 eval 组件都已经支持了， 但是是通过 fc-default 实现的， MR: 
https://github.com/devsapp/fc-eval/pull/33/files

**Comment by rsonghuster** [comment]
最后的用户体验是什么呢？

1. 可以兼容原来的体验

> 可以通过 fc-default 设置， 取消

2. 直接 s config 某个 alias 里面直接有 endpoint？

**Comment by wss-git** [comment]
fc-default 设置的方式已经支持，s config 在这个位置讨论中 https://github.com/devsapp/fc/issues/543
