### ISSUE TITLE
s build 中的错误信息优化

### ISSUE THREAD

**Issue by hryang** [devsapp/fc#333]
将 s.yaml 中的 image 属性置空，执行 s build，报如下错误：
Error: Function/CustomContainer/Image required.

这个错误其实不是很易懂。是否改成下面的形式会更好？
Error: function::customContainer::image atttribute value is empty in the  configuration file.

主要有几点考虑：
1. function, customContainer, image 和 s.yaml 中的名字保持一致
2. function::customContainer::image 这种模式更容易让用户知道三者是递进关系的属性。用 / 分隔容易让用户觉得这是3个并列的属性。
3. 错误信息中提到 configuration file，用户能更容易理解这是 s.yaml 中的问题。

**Comment by rsonghuster** [comment]
s 工具错误信息统一优化
