### ISSUE TITLE
help 信息说明文档

### ISSUE THREAD

**Issue by git-qfzhang** [devsapp/fc#336]
如果当前路径中有 s.yml 且其中 component 字段是 devsapp/fc （或者 fc），执行 s build -h 会输出 build 相关的内容
否则，执行 s cli fc build -h 会输出 build 相关内容。

那么我们是不是应该说清楚，当前目录不是 s project（包含 s.yaml) ，没有 build 的帮助信息。绝大多数情况下，用户不会关注这是 s 的命令还是组件的命令。

**Comment by rsonghuster** [comment]
@heimanba 麻烦一起看下
