### ISSUE TITLE
fun2fc 没有处理policies

### ISSUE THREAD

**Issue by wanghq** [devsapp/fc#34]
1. 没有处理policies。
2. 为什么convert后需要定义两次service？虽然这两个service配置一样。
3. 通常版本使用version，好像使用edition的很少。

![image](https://user-images.githubusercontent.com/321684/122451657-43b86c00-cf5d-11eb-8c92-3673d0024702.png)

**Comment by git-qfzhang** [comment]
1. 添加 policy 的格式为：
```shell
role:
  name: ***
  policies:
    - ***
    - ***
```
2. convert 操作是指？如果部署两个函数，目前必须写两次服务配置，可以将服务配置作为 s.yml 中的全局变量使用，具体使用可以参考 https://github.com/Serverless-Devs/docs/blob/master/en/yaml.md#yaml-specifications, 目前没有具体的案例，后面会提供
3.  @anycodes  麻烦回复下这个问题

**Comment by anycodes** [comment]
这个是转换的时候出现了问题，这里我一会也看一下。

**Comment by git-qfzhang** [comment]
看起来是我们的 fc-transform 组件将 fun 的 template.yml 转换为 s.yml 时 policy 没有转换过来，这个会紧急修复一下。

**Comment by anycodes** [comment]
已经处理上面的两个问题，请检查
