### ISSUE TITLE
start-wordpress、start-zblog 这些 php 应用会出现 502 的问题

### ISSUE THREAD

**Issue by git-qfzhang** [devsapp/fc#347]
### 问题描述

基于 start-wordpress 等模版部署应用后，访问返回的域名，会出现 502 的报错，这是因为 php-fpm 的启动速度较慢，而拉起函数容器的时间限制是 35s，无法保证在这个时间内将 php-fpm 启动成功，因此只能将 php-fpm 的启动时间分摊到函数执行上，导致前几次访问会出现 502 问题，等到 php-fpm 启动成功后就能成功访问。

### 解决方法

现在拉起函数容器的时间限制已经延长到 2 分钟，在 ECS 上已经全量上线，但是在神龙上还没上线，得等到神龙也全量上线后才能更新启动脚本，确保在启动脚本中将 PHP-fpm 启动成功，然后再启动 ngnix。

**Comment by rsonghuster** [comment]
https://github.com/devsapp/start-web-framework/tree/master/web-framework/php

最新的 custom runtime 版本已经解决了
