### ISSUE TITLE
fc-http-java 模板访问出错

### ISSUE THREAD

**Issue by hryang** [devsapp/fc#348]
执行 s init ，选择 fc-http-java 模板，部署成功后，调用 custom domain 的 endpoint，返回如下错误

![图片](https://user-images.githubusercontent.com/626967/136950275-4f9f9cdc-f782-4144-8b3b-1fe9607d815a.png)

**Comment by rsonghuster** [comment]
![image](https://user-images.githubusercontent.com/10919599/136951849-821c46db-8103-4742-8839-ad27a6992f9f.png)

core 新引入的问题， 丹坤会 fix

**Comment by wss-git** [comment]
已经在新版本做了判断，只有js的框架才会自动部署
