### ISSUE TITLE
deploy部署速度优化

### ISSUE THREAD

**Issue by anycodes** [devsapp/fc#36]
1. 部署时可以检查域名状态，如果域名已经ready，可以不用重新部署和验证。

**Comment by anycodes** [comment]
2. s.yaml同个服务，多个函数。

**Comment by anycodes** [comment]
3. 串行部署->并行部署， 如果不存在依赖情况，可以存在并行模式部署；

**Comment by anycodes** [comment]
> 3. 串行部署->并行部署， 如果不存在依赖情况，可以存在并行模式部署；

可以之后再做。先讨论

**Comment by wss-git** [comment]
域名部署已经合入到相关组件 https://github.com/devsapp/fc-deploy/pull/59
