### ISSUE TITLE
build image 支持 build kit 的的问题

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#361]
1. https://github.com/devsapp/fc-build/blob/a5904e3c603f3af9351218fc840b8fd112851b03/src/utils/builder.ts#L107  addr 最好不仅仅是 localhost

2. buildkit 模式，一般是 build 和 push 是不能分开的， 比如：

```
buildctl  --frontend=dockerfile.v0 --local context=. --local dockerfile=. --output type=image,name=registry.cn-hangzhou.aliyuncs.com/rsong/python:buildkit,push=true
```

**Comment by wss-git** [comment]
重复 issue 612
