### ISSUE TITLE
s invoke 多请求头

### ISSUE THREAD

**Issue by robinsonnie** [devsapp/fc#374]
* $ s invoke -e '{"method":"GET","headers":{"App-Run-Mode":"train"}}'
   * ok
 
* $ s invoke -e '{"method":"GET","headers":[{"App-Run-Mode":"inference"},{"App-Inference-Url":"https://ndptest.oss-cn-shanghai.aliyuncs.com/16339359979_6d742660b8_n.jpg"}]}'
   * 不工作，是不是不支持s invoke时多请求头设置

**Comment by wss-git** [comment]
后面关于错误会优化，https://github.com/Serverless-Devs/Serverless-Devs/issues/285
