### ISSUE TITLE
压测出现以下问题

### ISSUE THREAD

**Issue by jingyan070** [devsapp/fc#375]
[root@iZbp180k0vbjx91bee86q6Z /]# s cli fc stress start --function-type http --payload '{}' --region cn-shanghai --access default
[2021-10-25T17:07:53.747] [INFO ] [FC-STRESS] - Reading payload content...
[2021-10-25T17:07:53.793] [INFO ] [FC-STRESS] - Using stress options: 
numUser: 6
spawnRate: 10
2021-10-25 17:47:28 重新连接成功!
Last login: Mon Oct 25 17:47:27 2021 from 118.31.243.46

Welcome to Alibaba Cloud Elastic Compute Service !

User Tips:
For better compatibility, Alibaba Cloud Linux 2 manages network settings via
network-scripts by default instead of former systemd-networkd.
More details please refer to:
https://help.aliyun.com/knowledge_detail/182049.html

11 package(s) needed for security, out of 30 available
Run "yum update" to apply all updates.
[root@iZbp180k0vbjx91bee86q6Z ~]# s cli fc stress start --function-type http --payload "hello world" --region cn-shanghai --access default[2021-10-25T17:47:53.751] [INFO ] [FC-STRESS] - Reading payload content...
[2021-10-25T17:47:53.842] [INFO ] [FC-STRESS] - Using stress options: 
numUser: 6
spawnRate: 10
runningTime: 30
functionType: http
invocationType: Sync

[2021-10-25T17:47:53.843] [INFO ] [FC-STRESS] - Preparing helper reource for stress test.
(node:31782) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
✔ Stress test complete.
✖ Failed to execute:

TraceId:     00163e1b35051635155274532
Environment: @serverless-devs/s: 2.0.86, @serverless-devs/core: 0.1.7, linux-x64, node-v14.17.4
Documents:   https://www.serverless-devs.com
Discussions: https://github.com/Serverless-Devs/Serverless-Devs/discussions
Issues:      https://github.com/Serverless-Devs/Serverless-Devs/issues

ERROR:
Error: Invalid format of payload.

Please copy traceId: 00163e1b35051635155274532 and join Dingding group: 33947367 for consultation.
You can run 's clean --cache' to prune Serverless devs.
And run again with the '--debug' option or 's -h' to get more logs.

**Comment by wss-git** [comment]
问题已经排查到，你所组件的问题，已经转到内部处理
