### ISSUE TITLE
.funignore 在构建非自定义运行时的函数时不工作

### ISSUE THREAD

**Issue by DevDengChao** [devsapp/fc#379]
### 用户场景:

当使用 TypeScript 编写 NodeJS 函数时, 需要先使用 tsc 进行构建, 然后通过 s build 将与构建无关的文档排除, 最后再通过 s deploy 发布到云端.

### 遇到的问题:

由于 .funignore 在构建非自定义运行时的函数时不工作, 因此没法充分利用构建阶段和部署阶段分别忽略不同文件的功能.

### 涉及的软件版本:

s 2.0.90

### 参考:
+ 聆听: https://connect.console.aliyun.com/connect/detail/365631
+ 样本工程: https://github.com/DevDengChao/aliyun-fc-issues/tree/master/serverless-devs/.funignore-not-works-when-not-targeting-custom-runtime
+ [build .funignore 也会生效 #283](https://github.com/devsapp/fc/issues/283)

**Comment by heimanba** [comment]
.funignore是fun时代的历史产物哈，建议使用 .signore
