### ISSUE TITLE
s local start 针对有 custom domain 的默认行为

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#381]
s local start 针对有 custom domain 的时候， 默认行为是  s local start auto

**Comment by wss-git** [comment]
针对 local start 交互：
1. 如果不存在 customDomains 配置，一定使用 fc 的系统路径
2. 存在 customDomains 配置
2.1. 指定 --custom-domain <domainName> 使用此域名路径
2.2. 未指定 --custom-domain <domainName>；如果 customDomains 仅有一个，直接使用此域名路径；如果存在多个则交互选择
2.3. 如果使用域名路径，使用 --custom-domain system 或者选择时候选择 system

**Comment by wss-git** [comment]
已发布
