### ISSUE TITLE
【fc-core】s local start 不应该生成 随机端口

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#382]
对于 custom runtime 和 custom container， s local start 不应该生成随机端口， 而是和 caPort 一样的端口

**Comment by heimanba** [comment]
caport是容器暴露的端口，使用时候会显示端口被占用。使用在没有被占用的情况下使用 caport + 1这样的默认端口

**Comment by wss-git** [comment]
最终交互：
1. 针对 custom 和 镜像函数：默认使用 caport + 1 的固定端口，其他函数是随机一个端口。
2. 可以指定 --server-port 9090 指定端口
