### ISSUE TITLE
权限专项

### ISSUE THREAD

**Issue by anycodes** [devsapp/fc#39]
针对权限问题，专项处理Issue

**Comment by anycodes** [comment]
1. 写清楚每个功能的权限要求
    - Deploy需要那些基础权限
    - Deploy带有不同的auto需要那些权限
    - Deploy不同的触发器需要哪些权限
    - Remove操作需要哪些权限
    - Info操作需要哪些权限
    - Sync操作需要哪些权限
    - Invoke操作需要哪些权限
2. 某些设计权限问题，可以考虑尝试进行
    - 在对权限进行检查时，是不是必须行为？如果这一步骤失败了，没有权限查询等，是不是可以尝试try catch，然后尝试下一步？
    - 在创建某些资源，处理某些资源之前，先进行权限的创建，升级，这个步骤是不是必须的？如果没权限升级操作，是不是可以try catch，然后继续尝试；
3. 相关权限报错，是不是可以进一步友善一些？例如检测到用户缺少A权限，是不是可以告诉用户如何添加A权限，可以提供一个文章，文档等，引导用户去创建？

**Comment by anycodes** [comment]
![image](https://user-images.githubusercontent.com/21079031/123591065-1ce01c80-d81e-11eb-87be-ddfaf219374e.png)

**Comment by wss-git** [comment]
文档已经产出 https://github.com/devsapp/fc/blob/main/docs/Others/authority/command.md
