### ISSUE TITLE
`s deploy -h` 命令输出的帮助文档与实际效果不一致

### ISSUE THREAD

**Issue by DevDengChao** [devsapp/fc#392]
预期效果: 
![image](https://user-images.githubusercontent.com/16363180/139645128-7682686a-c3c0-418b-b3ba-0c65aef9af83.png)

实际效果:
![image](https://user-images.githubusercontent.com/16363180/139645031-728bb37f-3087-41c8-9b7e-04fb1c861d3d.png)

**Comment by wss-git** [comment]
ls -al 执行的目录看看呢？是不是没有 s.yaml，或者 yaml 文件中的 component 字段不是 devsapp/fc

**Comment by DevDengChao** [comment]
确实是因为没有找到默认的 s.yaml 的问题, 使用 -t 参数指定文件名后就可以了.

不过, 即便是 -h 指令也需要指定 template 文件后才能运行么...

**Comment by wss-git** [comment]
不会吧，应该是你的执行目录下没有 s.yaml  或者 s.yaml 这个文件

**Comment by DevDengChao** [comment]
> 不会吧，应该是你的执行目录下没有 s.yaml 或者 s.yaml 这个文件

🤣 是我这边的问题, 因为需要区分集成测试环境和生成环境, 所以我把 s.yaml 文件重命名了, 使用了不同的文件名.
