### ISSUE TITLE
deploy.md 文档缺少 `--use-local` 相关的使用说明

### ISSUE THREAD

**Issue by DevDengChao** [devsapp/fc#393]
https://github.com/devsapp/fc/blob/main/docs/Usage/deploy.md

**Comment by DevDengChao** [comment]
由于使用了默认的 `s deploy` 指令,  出现过几次 ci 成功运行后, 本地的 html 文件改动并没有被部署到 FC 上, 刚刚加上 `--use-local` 参数后成功将 html 文件上的改动部署到线上了.

**Comment by wss-git** [comment]
https://github.com/devsapp/fc/blob/main/docs/Usage/deploy.md
