### ISSUE TITLE
关于`fun2s`的相关说明

### ISSUE THREAD

**Issue by anycodes** [devsapp/fc#400]
1. 需要默认读取用户`region`；
2. 现在写的默认是`s.yaml`，但是今天在某个时候生成了` s.yml`，需要排查一下业务逻辑；
3. 相关操作文档参考：https://github.com/devsapp/fc/blob/jiangyu-docs/docs/command/fun2s.md

**Comment by wss-git** [comment]
理论上是不会出现问题的，是不是指定了target这个参数： s cli fc fun2s --region cn-shenzhen --target ./s.yml

**Comment by wss-git** [comment]
未复现
