### ISSUE TITLE
关于`info`的相关说明

### ISSUE THREAD

**Issue by anycodes** [devsapp/fc#401]
info命令理论上没有太大的变化，但是需要在返回的时候增加region字段，详情可以参考文档：https://github.com/devsapp/fc/blob/jiangyu-docs/docs/command/info.md

请注意文档相关的准确性和一致性。

**Comment by wss-git** [comment]
已发布
![image](https://user-images.githubusercontent.com/56686088/140454470-113ea965-76d0-4e5c-8b6c-91f4429af41a.png)
