### ISSUE TITLE
s remove service A，却抛出 B 和 C 资源删除失败的错误

### ISSUE THREAD

**Issue by hryang** [devsapp/fc#402]
我在上海区域有3个 service，mall-admin, mall-portal, mall-search，当我执行 s remove service --service-name mall-admin --region cn-shanghai 时，出现下面的错误：
![图片](https://user-images.githubusercontent.com/626967/140016705-a86d85d9-aaf0-4b69-8faf-e69dad122c7c.png)

我的命令只和 mall-admin 相关，为啥需要显示 mall-search，mall-portal 的内容？

相关 trace id：00163e304ed01635919963626

**Comment by rsonghuster** [comment]
你的 yaml 能贴下吗

**Comment by rsonghuster** [comment]
如果单纯删除某个 service,  可以使用 cli 模式

`s cli fc remove -h`
