### ISSUE TITLE
s build &  local invoke 需要支持下 go runtime 

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#403]
s build &  local invoke 需要支持下 go runtime

**Comment by rsonghuster** [comment]
build --use-docker  暂时先不支持， 理论上来说，go 开发者，本地都安装  golang

### mac & linux 用户可以使用如下命令完成编译：

```
GOOS=linux GOARCH=amd64 go build -o target
```

### windows 用户使用如下命令完成编译：

```
SET GOOS=linux 
SET GOARCH=amd64
go build -o target
```

**Comment by rsonghuster** [comment]
https://github.com/aliyun/fc-docker  有关 go runtime 的增加， 由落泥or快帆去完成

**Comment by rsonghuster** [comment]
暂时不考虑支持 go， 直接 actions 来完成  https://github.com/devsapp/start-fc

**Comment by wss-git** [comment]
和产品沟通， go build 后序不需要支持  但是需要补充文档 

Ref https://github.com/devsapp/fc/issues/869
