### ISSUE TITLE
s init 示例增加 go runtime

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#404]
s init 示例增加 go runtime

**Comment by rsonghuster** [comment]
luoni  先把 go 示例提 pr 到这个 repo https://github.com/devsapp/start-fc

**Comment by wss-git** [comment]
https://github.com/devsapp/start-fc/blob/master/event-function/fc-event-golang1.x/src/s.yaml  看到已经合并进去了

**Comment by rsonghuster** [comment]
暂时不支持 local invoke
