### ISSUE TITLE
logConfig 为 auto 的时候， 出现 no access

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#406]
使用的是主账号， 第一次 deploy 的时候， 出现   no permission to access logstore x in logproject y，第二次就OK 了

应该是日志服务资源的创建是异步的， 需要多次 retry get， 看看是不是真的成功创建

**Comment by wss-git** [comment]
这个问题之前和千风也讨论过，但是日志接口没有这个状态的返回，只能去创建重试机制（已经增加了）；

而且还有比较奇怪的地方，如果日志仓库没有创建成功，那么为什么可以开通索引呢？是日志那边有什么特殊处理，还是我们的接口有啥问题呢？

**Comment by wss-git** [comment]
![image](https://user-images.githubusercontent.com/56686088/140040449-19901505-e35a-4525-9478-ed5aae8951df.png)

在部署时候重试机制是：
日志如果有问题是（重试 12 次 每次3s） * 2，
其他问题就是仅仅是重试2次，每次1s
