### ISSUE TITLE
s sync 有 bug 

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#408]
![image](https://user-images.githubusercontent.com/10919599/140030615-7b71436b-bd33-4778-91f9-d06417f55ae4.png)

![image](https://user-images.githubusercontent.com/10919599/140030628-06512b53-bc51-4b5f-bc37-58e254e11e0a.png)

s sync 没有同步公网访问这个， 控制台导出可能也有相同的问题

**Comment by gongjl88** [comment]
控制台也有相关问题，已修复！

**Comment by rsonghuster** [comment]
> 控制台也有相关问题，已修复！

控制台这个是已经发布上线了吗？ 还是处于预发

**Comment by wss-git** [comment]
> > 也有磨损的相关问题，已修复！
> 
> 这是已经发布了吗？

已经发布了
