### ISSUE TITLE
关于 deploy 配置不生效

### ISSUE THREAD

**Issue by wss-git** [devsapp/fc#41]
复现步骤：
1. s deploy
2. rm -rf .s
3. 再次 s deploy， 有交互就回车 【会选择使用线上配置】
4. 修改 yaml 
     I. s deploy   yaml 不生效
     II. s deploy  --use-local.  yaml 生效

**Comment by wss-git** [comment]
#42

**Comment by git-qfzhang** [comment]
https://github.com/devsapp/fc-deploy/pull/60
