### ISSUE TITLE
s deploy --use-remote 命令的体验优化

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#410]
在很多开发场景， 可能会存在这个流程：

1.  s init 一个项目， 开发
2. s deploy 成功， 发现 service 配置有点不对， 不太熟悉 yaml 语法， 直接登录控制台白屏化修正为自己的想要的配置， 发现 work 了
3.  本地可能再进行了一些开发， s deploy， 这个时候， s 工具感知了本地 s.yaml 的配置和线上的已有的配置有差异， 会让用户选择是 use local 还是 use remote
4. 这个时候， 我选择了 remote,  这个时候其实线上啥也没有变化， 但是对于用户来说， 其实这个时候， 他想要的是使用本地的代码，但是配置可能是想要线上的， 这个时候你可能会使用如下命令:

```bash
s deploy --type code --use-local
```

但是你本地的 s.yaml 一日不和线上一致， 每次执行 s deploy 都会弹出这个提示

所以建议这边的体验是这样的：

用户选择了 use-remote， 可以提醒他使用 s xxx sync 或者 s sync同步线上的配置到本地

目前的 sync 的用户体验是这样的

![image](https://user-images.githubusercontent.com/10919599/140033856-d6d1c9dc-0546-4894-85ce-b757659d542a.png)

建议 s sync 增加一个 target 字段， 比如  s sync --type config --target s.yaml， 然后弹出提示， 用户选择 y ，则覆盖本地的 s.yaml

**Comment by hryang** [comment]
为啥还需要用户执行 s sync 啊？就在 deploy 的时候给用户下面的选项，让他自己选：
--use-local
--use-remote
--use-remote-and-update-local-config（可以再命名，意思大概就是这样）
如果选了3，就更新 s.yaml 吧。这里的更新是只更新相关的资源配置，其他资源不受影响。

**Comment by anycodes** [comment]
我推荐，这一部分先不进行优化，等我这两天把细节梳理完成，在统一进行优化
