### ISSUE TITLE
优化: fc打包后需要将 src的目录 ignore掉

### ISSUE THREAD

**Issue by heimanba** [devsapp/fc#413]
需要在 .signore 加上`src`源码文件
![image](https://user-images.githubusercontent.com/5129967/140252767-57dd8c81-d2d4-4493-845f-3f0dc1966549.png)

**Comment by heimanba** [comment]
![image](https://user-images.githubusercontent.com/5129967/140253877-8242f6e4-e934-480c-950a-8aaaad1ab21b.png)

**Comment by wss-git** [comment]
这个在发布工程中慢慢忽略掉，部分已经已经忽略
