### ISSUE TITLE
eval 文档完善

### ISSUE THREAD

**Issue by anycodes** [devsapp/fc#417]
请相关同学完善该文档内容：https://github.com/devsapp/fc/blob/jiangyu-docs/docs/command/eval.md

详细内容包括：
1. 文档中的参数描述
2. 文档中的权限配置
3. 文档中的结果解释

**Comment by rsonghuster** [comment]
这个事情我来完成吧， 先解决掉这两个 https://github.com/devsapp/fc-eval/issues  先， 可能参数有点小变化

**Comment by anycodes** [comment]
> 这个事情我来完成吧， 先解决掉这两个 https://github.com/devsapp/fc-eval/issues 先， 可能参数有点小变化

OK，变动之后也请更新到文档中，感谢
