### ISSUE TITLE
关于部署提醒的逻辑

### ISSUE THREAD

**Issue by anycodes** [devsapp/fc#42]
![image](https://user-images.githubusercontent.com/21079031/123610590-4eafae00-d833-11eb-949e-dc8cab4c0593.png)

（这是一张极丑的，且不规范的流程图，可以先看一下）

**Comment by wss-git** [comment]
沿用之前的逻辑感觉也没有太大的问题，但是需要提示用户我没有使用 yaml 的配置，类似 s cli fc-default 组件的提示

**Comment by git-qfzhang** [comment]
有状态是指是否用 fc 组件部署过，每次部署记录本次部署的配置信息。
这样在每次部署前，都检查上一次部署的配置信息与当前线上信息进行比较，基于比较结果进行后续逻辑

**Comment by git-qfzhang** [comment]
保留 --use-local 参数，该参数会强制使用线下配置覆盖线上。
删除 --use-remote 参数。
