### ISSUE TITLE
Power tuning 支持导入 postman 数据，进行压测和推荐

### ISSUE THREAD

**Issue by hryang** [devsapp/fc#421]
当前 Power tuning 的压测程序要求用户在启动压测时传入 payload 数据，这意味着整个压测产生的 request 都是相同的。这对于 Event function 这类简单的事件处理逻辑是 OK 的，但是并不适用于 Web 应用。在 Web 应用场景下，用户通常是根据场景来进行压测。比如一个电商应用，压测场景是用户登录，然后查看商品，下单，查看订单。因此，PTS 这样的专业压测服务都支持场景化的压测。

![image.png](https://cdn.nlark.com/yuque/0/2021/png/995498/1636422735018-cc9bdcaf-550b-4fc1-ba9a-f4766b3127c3.png?x-oss-process=image%2Fresize%2Cw_1500%2Climit_0)

Power tuning 要在 Web 应用场景下被用起来，需要支持用户自定义压测程序。Power tuning 的逻辑主要分为三部分：

1. 准备压测程序；
2. 控制压测程序的压力，逐步施压，测试应用在不同实例并发度和实例规格下的性能表现。根据预设的指标（流控错误，OOM/异常，期望延时）来决定下一阶段负载压力；
3. 收集指标，绘制图表

其中，我们希望 1 是用户来准备，用户可以提交压测实例的逻辑，也可以使用 PTS 压测，这样 power tuning 才能覆盖 Web 应用场景。

要满足上述的要求，power tuning 需要将压测、指标收集和分析解耦。由于压测逻辑是场景化，用户自己提供的，因此我们需要定义用户交付压测逻辑的形式。主要分为以下两种：

* 用户以代码包或者容器镜像交付压测逻辑。Power tuning 工具根据代码包和容器镜像创建对应的压测函数，自己控制压力

* 用户以服务的方式交付压测逻辑。用户自己创建压测服务，形式不限，可以是函数，容器，VM或者 PTS 等云服务

Power tuning **要能控制压测的起停，要能控制压测的目标**。这意味着如果用户自己实现压测服务，必须要实现起停和控制压测目标的 API 才能和 power tuning 交互。对很多用户来说，这个路径有点长。**我们最好能提供一个更简洁的形态，一方面和用户现有的 Web 应用测试习惯契合，另一方面仍然是易于理解和上手的**。我觉得 power tuning 和压测的结合有3个形态：

1. 用户通过命令行参数或者文件指定 request 参数，power tuning 生成负载进行压测，主要覆盖简单数据处理场景
2. 用户通过 postman 等流行工具，生成测试请求，导出为文件。Power tuning 可以 import postman 文件，生成负载进行压测，主要覆盖 Web 应用场景
3. 用户使用 PTS 等专业的压测服务，power tuning 可以和 PTS 交互，进行压测和分析。主要覆盖复杂的 Web 应用和微服务场景

其中 2 是 1 的延续，对 Postman 等流行工具提供了更好的支持，更符合用户习惯，而且整个体验是简单、顺滑的，我们应该提供。场景3我们还没有想清楚，以后再考虑实现。

**Comment by rsonghuster** [comment]
对于 2 有个疑问： postman 的 json 文件， 从我这边观察来看， 只是简单的罗列了所有 api， 如下图：
![image](https://user-images.githubusercontent.com/10919599/140934107-c99a25d1-b724-4614-9bbe-7e71045c8799.png)

而对于你展示的 PTS 相关场景， 其实是需要用户定义的场景， 比如第一步登录调用 login api，拿到 token 或者 cookie 后续才能调用查看商品信息等api,  即有前置条件的约束的。 对于 postman 这种直接的 json 文件并不能实现这种约束条件， 如果只是单纯调用 API，   登录以后的后续的 api 的探测估计全是 invalid token 这种结果， 并没有真正实现探测场景

**Comment by hryang** [comment]
测试需要登录的 API 是很常见的需求，postman 支持填入 cookie 或者 token 的。
https://segmentfault.com/a/1190000021901761

**Comment by rsonghuster** [comment]
目前有简易的 V1 版本：  https://github.com/devsapp/fc/blob/main/docs/zh/command/eval.md
