### ISSUE TITLE
s logs 帮助命令中，--type 参数的含义解释不清晰

### ISSUE THREAD

**Issue by hryang** [devsapp/fc#427]
如图所示
![图片](https://user-images.githubusercontent.com/626967/141687479-4445fa60-4774-4758-98a0-dba1f104d287.png)

type 参数的说明看不懂，应该说明有哪些 type，分别是什么含义。

**Comment by wss-git** [comment]
理论上这个 --type 不需要了  keyword 包含了这个字段，下个版本将这个字段去掉。

之前也仅仅支持过滤出来 faild 的请求日志

**Comment by heimanba** [comment]
新版的帮助文档已经发布

![image](https://user-images.githubusercontent.com/5129967/147445070-5090ba9c-9fd9-455e-b6bd-344955801c80.png)
