### ISSUE TITLE
s plan能力

### ISSUE THREAD

**Issue by lowkeyrd** [devsapp/fc#451]
类似Terraform plan，s remove时可以调用plan方法，一次性给出本次操作的影响。
不一定做到terraform plan 那么通用，但应该针对fc，把资源变化的影响面解释的更好。

现在的情况是，每次部署时会检查线上存在同名的service或者function，如果存在提示用户选择使用local还是remote。
这个体验不是太好：
1. 没有给出线上和本地的差异，只是判断是否存在同名资源
2. 我即使什么都没修改，重复执行s deploy时都会给出这个提示，被中断的体验就不是太好
![image](https://user-images.githubusercontent.com/5763215/141792392-c5317e0c-c449-4909-bd05-0e1ecee6d448.png)

增加单独的s plan命令，会把这个问题轻松化解，无论s deploy、s remove还是应用中心发布 都给出livediff，这个体验会做的非常一致

**Comment by anycodes** [comment]
我觉得这个功能是可以有的，我们可以讨论设计一下。

**Comment by anycodes** [comment]
- 文档地址：https://github.com/devsapp/fc/blob/jiangyu-docs/docs/command/plan.md
- 预期完成时间：2021年11月18日

完善流程：
1. fork项目到自己仓库
2. 对`jiangyu-docs`分支下面的对应的文档内容进行完善
3. 提pr到仓库的`jiangyu-docs`，指定`anycodes` /  `service@52exe.cn`来review，并在群里告知

完善内容：
1. 文档的参数描述
2. 权限相关的描述

其他：有任何问题，请随时与 江昱 / Anycodes 联系
