### ISSUE TITLE
serverless devs 支持 custom dns 参数

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#455]
serverless devs 支持 custom dns 参数

```
"customDNS":{
  "nameServers":[
    "8.8.8.8",
    "114.114.114.114"
  ],
  "searches":[
    "default.svc.cluster-domain.example",
    "svc.cluster-domain-jqDgWvOo.example cluster-domain.example"
  ],
  "dnsOptions":[
    {
      "name":"edns",
      "value":""
    },
    {
      "name":"ndots",
      "value":"5"
    }
  ]
}
```

以上参数加入到 create/update function接口当中。

![image](https://user-images.githubusercontent.com/10919599/142007637-908223a1-4672-4b98-96dc-e72be7371602.png)

同理 fc-api 组件可能也需要

**Comment by wss-git** [comment]
fc-base-sdk https://github.com/devsapp/fc-base-sdk/pull/22
fc-deploy https://github.com/devsapp/fc-deploy/pull/133
fc-info https://github.com/devsapp/fc-info/pull/22
fc-sync https://github.com/devsapp/fc-sync/pull/16

**Comment by rsonghuster** [comment]
MR 已经 review 完毕

**Comment by wss-git** [comment]
已发布
