### ISSUE TITLE
FC组件报错信息统计

### ISSUE THREAD

**Issue by anycodes** [devsapp/fc#46]
为了提升用户的整体使用体验，我们会针对一些报错信息进行特殊处理。现在征集所有用户的使用时出现的报错信息，我们会有针对性的进行整理

**Comment by anycodes** [comment]
![image](https://user-images.githubusercontent.com/21079031/123900725-2f806000-d99c-11eb-9f1d-ba83ebfd57e9.png)

这种错误要捕捉到，告知用户：

没有开通函数计算，需要去`https://fc.console.aliyun.com/`进行开通

**Comment by anycodes** [comment]
![image](https://user-images.githubusercontent.com/21079031/123900789-4f178880-d99c-11eb-9cf9-d8ab090ede22.png)
在用密钥的时候，这里要确定几个事情：
1. 需要密钥再用，不需要不要获取，例如build等操作就不要获取用户密钥
2. 获取用户密钥之后，如果使用先检查一下，必备字段是否OK，如果不OK，像图中所示，提醒用户添加密钥信息，例如s config add

**Comment by wss-git** [comment]
![image](https://user-images.githubusercontent.com/56686088/129999310-7d7c83ad-e39e-4b31-a1ea-10a4346ce925.png)

**Comment by wss-git** [comment]
Message:  Code: USER_NOT_EXIST, Message: user is not exist.   子账号推镜像报错

**Comment by wss-git** [comment]
Message:  Code: AUTHENTICATION_FAILED, Message: user jurisdiction error.  子账号推镜像权限不足

**Comment by wss-git** [comment]
Message:  POST /services failed with 400. requestid: 9dfd5c20-d29f-48a0-964f-b97d17d7f481, message: MountDir exceeds the maximum allowed length (max: 64, actual: '/mnt/2be9f484c0-vfu95-cn-shenzhen/mnt/auto/testnas/ss/ss/ssss/sss/sss/ssss/sss/sss/ss').

**Comment by heimanba** [comment]
已经实现所有的错误搜集到sls,后面沉淀大盘数据。同时沉淀推荐场景
