### ISSUE TITLE
s deploy 更新函数的时候， 同步生效

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#460]
![image](https://user-images.githubusercontent.com/10919599/142006415-612982cb-25be-4013-a264-180767f4789a.png)

参考控制台上的做法， s deploy 更新函数的时候， 同步生效， 这个 s deploy 成功后， 立马 s invoke， 就不会调用到老的函数 cache 了

**Comment by wss-git** [comment]
是在修改的函数时候新增一个请求头吗？

**Comment by rsonghuster** [comment]
> 是在修改的函数时候新增一个请求头吗？

是的

**Comment by wss-git** [comment]
看了前端的交互貌似不是部署，是调用的时候携带的
