### ISSUE TITLE
nodejs14支持？

### ISSUE THREAD

**Issue by cloudfun** [devsapp/fc#464]
yaml配置什么时候可以支持阿里云的nodejs14运行时？

**Comment by rsonghuster** [comment]
deploy， invoke 等默认就是支持的

build 和 local invoke 暂时不支持

**Comment by rsonghuster** [comment]
现在针对  1.10.0 版本， 已经有 nodejs14 的镜像了， 可以考虑支持  build 和  local invoke 了

同时  s init 应该也需要增加下 14 的 case
