### ISSUE TITLE
.fcignore codeUri为'./'根目录时候无法忽略文件

### ISSUE THREAD

**Issue by heimanba** [devsapp/fc#467]
![image](https://user-images.githubusercontent.com/5129967/142423413-5e7eafd9-1810-48dd-8ab3-f21b6ae4c149.png)

![image](https://user-images.githubusercontent.com/5129967/142423529-dd7f547b-eb0b-43c7-b158-8386e5caf838.png)

**Comment by wss-git** [comment]
ignore npm 包不支持 ['./dir', 'dir/**/filename'] 这两种写法，待解决

**Comment by wss-git** [comment]
https://github.com/devsapp/fc-deploy/pull/160

**Comment by wss-git** [comment]
已修复
