### ISSUE TITLE
压测和探测功能，辅助函数更新优化

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#479]
压测和探测功能， 辅助函数变化讨论：

nas 辅助函数和具体的 service 绑定， 所以给每个用户的每个 service 创建一个没有什么问题， 但是对于压测和辅助， 想有如下变化：

1. 用户只有一个辅助函数， 函数逻辑只是返回用户的能调用函数的权限的  sts 加密密文(公钥加密)
2. 真正的压测函数或者探测的函数（私钥解密）， 在 devs 账号下面

理由是函数逻辑的控制权在我们这边：
- 用户的辅助函数特别简单， 万年不变， 看后面的评论， 辅助函数可完全去掉
- 函数设置多少内存规格， 多长的 timeout 是我们自己去决定的。 比如现在用户默认的压测函数是10分钟， 假设压测超过 10 分钟呢？ 比如 power tunning 想支持很多 newman 并行任务， 内存不够
- 函数出 bug 了， 有调用异常了， 日志在我们这边， 我们可以快速查问题
- 比如像压测报告 html 这种， 可以自己上传到我们自己的 oss， 然后给用户一个打开的 url 地址体验更好
- 比如压测辅助函数代码包有12M， 第一次使用， 用户下载再创建函数， 需要较长的等待时间

**Comment by rsonghuster** [comment]
压测指令不需要指令 function-type 参数， 也在这里一起解决掉吧

**Comment by rsonghuster** [comment]
这里可以完全取消辅助函数， 采用如下方案：

1. 本地直接生成相关的 header, https://github.com/aliyun/fc-nodejs-sdk/blob/master/lib/client.js#L146,  然后直接把这个 header 传给中心化的函数（我们自己账号下面的）

2. 我们自己函数， 直接根据 header， 发起 http 请求调用 FC， 从而没有鉴权的影响

建议将这块功能 common 化。 而且 nas 辅助函数这种特殊情况， 其他的方案采用如下方案

**Comment by rsonghuster** [comment]
这里可以完全取消辅助函数， 采用如下方案：

1. 本地直接生成相关的 header, https://github.com/aliyun/fc-nodejs-sdk/blob/master/lib/client.js#L146,  然后直接把这个 header 传给中心化的函数（我们自己账号下面的）

2. 我们自己函数， 直接根据 header， 发起 http 请求调用 FC， 从而没有鉴权的影响

建议将这块功能 common 化。 而且 nas 辅助函数这种特殊情况， 其他的方案采用如下方案

**Comment by hryang** [comment]
我觉得最大的问题是压测是一个资源消耗型的服务，serverless devs 目前没有考虑付费，所以压测函数属于我们自己的账户不太合理。下面列出来的问题，都是可以解决的。

- 函数设置多少内存规格， 多长的 timeout 是我们自己去决定的。 比如现在用户默认的压测函数是10分钟， 假设压测超过 10 分钟呢？ 
  - YHR：什么情况下用户需要更长的压测时间？如果需要，他不能自己配置吗？
- 比如 power tunning 想支持很多 newman 并行任务， 内存不够。函数出 bug 了， 有调用异常了， 日志在我们这边， 我们可以快速查问题。比如像压测报告 html 这种， 可以自己上传到我们自己的 oss， 然后给用户一个打开的 url 地址体验更好。
  - YHR：函数出问题确实是个问题。我们是否考虑让用户提供日志。今天客户端程序都运行在用户自己的机器上，出问题也需要依靠用户提供信息处理。
- 比如压测辅助函数代码包有12M， 第一次使用， 用户下载再创建函数， 需要较长的等待时间
  - YHR：12 MB 不是很大。这种事情用户只做一次，应该还好吧。未来我们是不是可以把这种代码包变成 layer，可以方便的引用。

**Comment by rsonghuster** [comment]
#### 1. 什么情况下用户需要更长的压测时间？如果需要，他不能自己配置吗？
1. 不知道， 只是真的有， 用户跑了 10 分钟，然后我们返回 timeout, 没有压测报告， 体感很差
2. 我们本来就想他们无感知的， 所以不想让他配置

#### 2. 今天客户端程序都运行在用户自己的机器上，出问题也需要依靠用户提供信息处理。
后面我们 s 客户端工具， 会自动收集上传错误， 依赖用户提供日志和信息， 是一个十分低效的操作

#### 3. 12 MB 不是很大。这种事情用户只做一次，应该还好吧。未来我们是不是可以把这种代码包变成 layer，可以方便的引用。

1. 我想的是：
-  i. 我们会有更多的 workshop, workshop 就是昨天一样， 什么都是初始化状态; 
- ii. 将来我们提供其他的功能代码包更大你呢；
-  iii: 辅助函数本身也处于迭代状态， 更新一次， 用户使用就会触发一次

2. 未来我们是不是可以把这种代码包变成 layer，可以方便的引用。 这个可行， 不过需要这个 layer 是我们官方的， 可以直接引用， 本质上这个辅助函数不大， 是依赖包大， 如果依赖包是大家可以引用的 layer， 确实没有问题， 但是反过来想， 这个本身不也是把这个事情交给平台去托管了吗？

#### 3. 为什么想直接在一个执行环境里面支持 newman 并行？

实现更加简单， 探测理论上更加精准， 同时我们消耗的计算资源更少

- 1.  newman 本身可以支持 lib 模式， 不一定是 cli 启动， https://github.com/postmanlabs/newman#using-newman-as-a-library
- 2. 在一个程序里面支持发起我们指定的并发， 总归是简单很多， 数据汇总也简单很多
- 3. 如果实现在用户账户下面， 并发太大， 超过默认的 300 限制怎么办， 影响了线上运行的函数资源的弹性扩容怎么办， 不确定性太多
- 4. 您的函数， 怎么知道能准确知道并发执行了多少了 newman 命令的实例，目前看起来， 只能是异步调用这个函数多少次， 估算 FC 会尽最大的努力达到这个并发

**Comment by hryang** [comment]
1. 超时这个问题，即使把压测程序移到我们自己的账户下，也会有问题。如果用户被测的函数有问题，响应很慢，跑完整个压测程序也是有问题的。如果超时了，但是我们仍然可以根据已经产生的数据绘制图表，但是告诉用户整个测试没有跑完，这个体验是比较好的。
2. s 客户端会自动收集上传错误，那么压测的问题可以和工具其他问题采用同样的方式解决。不是挺好的吗。
3. ”但是反过来想， 这个本身不也是把这个事情交给平台去托管了吗？“ - 不是平台托管不行，而是一个 tradeoff 吧。如果我们把压测做到了自己的服务里，等于自己做了一个简化版 PTS。成本，资源管理是一个很麻烦的事情。
4. "如果实现在用户账户下面， 并发太大， 超过默认的 300 限制怎么办， 影响了线上运行的函数资源的弹性扩容怎么办， 不确定性太多" - 咱们不是 PTS 这样是在压测一个服务，咱们只是压测一个实例。压测单个实例不需要太多的并发度，而且我们可以考虑大一点的实例规格来跑压测程序吧。我反而觉得我们需要限制压测函数的并发度，防止一些 bug，导致压测失控，用了太多的实例。
5. “实现更加简单， 探测理论上更加精准， 同时我们消耗的计算资源更少” - 我理解实现应该和在我们还是用户账户无关啊？为什么在我们自己的账户下就可以做得更精准，消耗的资源更少？
6. “怎么知道能准确知道并发执行了多少了 newman 命令的实例，目前看起来， 只能是异步调用这个函数多少次” - 我们需要关心准确并发执行了多少实例吗？只要能把目标函数压到极限就行了吧。

**Comment by rsonghuster** [comment]
#### 1. 超时这个问题，即使把压测程序移到我们自己的账户下，也会有问题
不会， 使用性能型实例，默认 2h， 实在不行， 单独给我们自己的函数调整到 6h

#### 2. 如果超时了，但是我们仍然可以根据已经产生的数据绘制图表?
有点难， 这个需要深入了解 localcust 压测库， 自己去改；  或者你看到用户的参数， 时间超过了 10 分钟， 自动改成比如9.5min

#### 3. s 客户端会自动收集上传错误
这个是 s 底层统一做的，我们不想每个辅助函数都要做这样一件事情， 而且辅助函数可能是不同的 runtime,  代码复用都难

#### 4.  压测单个实例不需要太多的并发度，而且我们可以考虑大一点的实例规格来跑压测程序吧。我反而觉得我们需要限制压测函数的并发度，防止一些 bug，导致压测失控，用了太多的实例。

是的， 所以想一个执行环境里面并发 newman

#### 5. “实现更加简单， 探测理论上更加精准， 同时我们消耗的计算资源更少” - 我理解实现应该和在我们还是用户账户无关啊？为什么在我们自己的账户下就可以做得更精准，消耗的资源更少？

这个问题跟是不是实现在我们的账户还是用户账户下面无关， 这是另外一个问题， 即对应4， 为什么不采用你之前说的那个 master 函数，并发调用 worker 函数（跑 newman 命令）的方案

#### 6. “怎么知道能准确知道并发执行了多少了 newman 命令的实例，目前看起来， 只能是异步调用这个函数多少次” - 我们需要关心准确并发执行了多少实例吗？只要能把目标函数压到极限就行了吧。

是的， 但是你至少有一个估计， 怎么才能把目标函数压到极限吧。 这个估计的值， 就是你要并发的 newman 执行数目

**Comment by hryang** [comment]
1. “不会， 使用性能型实例，默认 2h， 实在不行， 单独给我们自己的函数调整到 6h”
很难想象，一个只需要生成 API 请求，而且只压测一个实例，每次压测需要 2h。

2. “是的， 但是你至少有一个估计， 怎么才能把目标函数压到极限吧。 这个估计的值， 就是你要并发的 newman 执行数目”
那看起来不需要太准确的值，异步调用应该完全没问题啊。

总的来看，除了问题调查比较复杂，其他看起来都不是 blocking 的问题。

**Comment by rsonghuster** [comment]
1. 用户会不会压2h 那是他的事情， 但是能不能支持是我们的事情
2. 这个太绝对了， 假设我单个实例能压测到1000 qps， 异步调用， 不一定能消耗到这么快。 同步调用， 明确能收到 429 信号， 为什么要搞异步调用这个未知的
