### ISSUE TITLE
打包的函数代码是否对用户透出

### ISSUE THREAD

**Issue by git-qfzhang** [devsapp/fc#48]
有的用户想在部署前有一步操作，只输出压缩后的代码包，判断该包是否符合预期，若符合预期再进行上传。

所以是否需要增加一个指令，例如 pack 指令，只打包代码包，然后透出给用户，然用户自行判断是否执行后面的 deploy 操作。

**Comment by rsonghuster** [comment]
这个没有啥意义吧， 现在控制台 web ide 就可以直接查看部署后的代码包具体是咋样的， 十分清楚

反正我个人感觉是，线上代码包是咋样， 第一反应是登录fc 控制台直接去查看下
