### ISSUE TITLE
s deploy 针对自定义域名 auto 会 random fail

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#481]
s deploy 针对自定义域名 auto 会 random fail,  需要用户手动重试

-  增加下自动重试

- 检查下代码， 看看有没有其他渠道提高鲁棒性

**Comment by git-qfzhang** [comment]
错误的原因好像是 "check token failed" 或者 "unauthorized token "，具体是哪个记不清了，需要多重试几次

**Comment by wss-git** [comment]
是不是下发域名的时候 cdn没有更新到导致的，可以测试一下

**Comment by wss-git** [comment]
上周梳理了一下 domain 的错误：
- check token failed
  - 原因：下发域名时，校验 token 错误；
  - 场景：同一账号、同一时刻、同一个地域、同一个服务下的函数 同时请求下发域名（应用中心预发经常出现这个问题）
- domain name '*****' has not been resolved to your FC endpoint, the expected endpoint is '****.ap-southeast-1.fc.aliyuncs.com. or ****.ap-southeast-1-internal.fc.aliyuncs.com.'
  - 原因：dns 异常
  - 场景：偶现
