### ISSUE TITLE
在判定使用 local 还是 remote 配置时，将代码/镜像和配置区分开

### ISSUE THREAD

**Issue by hryang** [devsapp/fc#483]
用户经常会同时使用控制台和 s 工具，造成 s 的 local 配置和 remote 不一致。s 今天会提醒用户不一致，让用户来选择。但在实际使用过程中，常常是希望将本地的代码包或者镜像更新到云端，但是配置使用 remote。我们当前的行为是一旦因为配置选择了 remote，代码包或者镜像也不会更新到 remote。这带来了两个问题：
1. 和用户的预期不符。因为用户通常是在本地频繁的修改代码，希望能更新到远端。但是配置很少变。目前工具的行为强迫用户先让 remote 和 local 保持一致。
2. 现在的行为是如果使用 local 配置，会更新代码包或者镜像；如果使用 remote，则不会将 remote 的代码包或者镜像覆盖本地。二者的行为不统一。

希望 s 后续能区分配置和代码包/镜像，即使用户选择了 remote 的配置，但 s deploy 时代码包或者镜像仍然会更新。

**Comment by git-qfzhang** [comment]
在频繁变动代码包/镜像，但是配置不变的前提下，可以使用 `s deploy function --type code` 来只部署代码。

不过目前仅支持只部署代码包，这里对 custom container 的支持的确没做好，这里后续可以在使用 `s deploy function --type code` 只部署代码包/镜像。

这个使用方式应该是能够解决您那边遇到的问题。

**Comment by wss-git** [comment]
关于进部署代码包和配置存在情况：

- 仅需要部署配置 添加参数使用 --type config（后新增 --skip-push 跳过 custom container 强制推送 ）
- 仅需要部署代码 --type code

关于本地和线上部署：
正常部署，会提示用户选择 use-local 或者 use-remote，但是用可以指定 --use-remote 和 use-local 强制使用本地或者线上配置。

如果说用户想要使用 remote 的配置或者代码，可以使用 s sync 指令将线上的配置和代码拉取到某个目录，然后手动替换本地的某些配置或者代码包
