### ISSUE TITLE
Windows下执行cat-dog示例项目报错

### ISSUE THREAD

**Issue by liulang0817** [devsapp/fc#485]
https://github.com/awesome-fc/cat-dog-classify?spm=5176.8663048.0.0.1c2f3edcdx9UZa 该示例在Windows下执行s build --use-docker会报错
![image](https://user-images.githubusercontent.com/38310830/144820312-28faf86f-0e0e-4ccd-be92-0d4e78cd019b.png)

**Comment by rsonghuster** [comment]
<img width="953" alt="image" src="https://user-images.githubusercontent.com/10919599/145714152-8552c231-ac43-42dc-9df2-eaf44236f8d1.png">

我这边的 windows 是可以的， 应该跟机器有关， close
