### ISSUE TITLE
本地调试时监听端口和 s.yaml 中的 caPort 不一致时，实例hang住，无法终止

### ISSUE THREAD

**Issue by hryang** [devsapp/fc#486]
使用 custom runtime/container 时，如果使用 s local start auto 应用启动时的监听端口和 s.yaml 中的 caPort 不一致，那么实例会 hang 住，必须要等待 s.yaml 中设置的超时时间才可以。这里比较好的体验是：
1. 允许用户通过 ctrl-c 终止。
2. 如果用户主动终止或者超时，是否能提醒用户 listen port 和 caPort 要保持一致？

**Comment by heimanba** [comment]
和这个issue 是一样问题
https://github.com/devsapp/fc/issues/380
