### ISSUE TITLE
s remove执行遇到问题

### ISSUE THREAD

**Issue by lowkeyrd** [devsapp/fc#487]
如下图，执行remove时，有两处不符合预期：
1. function已经删除，但还去查询trigger
2. service已删除，但还去查询alias，并且报错

这里应该是有些不干净的处理逻辑

![image](https://user-images.githubusercontent.com/5763215/144830439-a81914f4-0b40-42a6-b3ef-d669f7379802.png)

**Comment by rsonghuster** [comment]
还需要考虑预留或者实例数目限制的配置， 这个值， 按道理应该也要删除掉；  从理论上来说， 应该是后端去做的。 工具这边尝试先删除吧

**Comment by lowkeyrd** [comment]
还要再确认下，remove时是否会删除辅助函数、vpc这些资源

**Comment by lowkeyrd** [comment]
补充下，当s.yaml配置了多个函数并且关联了同一个service，会出现这个问题。
现在fc组件remove的实现只处理s 传过来的service，没有考虑整个应用，提两个建议优化方案：
1. remove时先查看state，判断资源(比如service)是否已经被删除，已删除就直接pass。remove完成后更新state
2. remove时，按资源依赖生成remove plan(记录到state)，按plan执行remove

**Comment by wss-git** [comment]
已经优化
