### ISSUE TITLE
增加部分Version, Alias, 预留能力

### ISSUE THREAD

**Issue by anycodes** [devsapp/fc#49]
# Version

- [x] 查看版本列表：s project version list
- [x] 发布版本：s project version publish -d/--description 描述
- [x] 删除版本：s project version delete -i/--id 版本号

# Alias
- [x] 查看别名列表：s project alias list
- [x] 获取别名详情：s project alias get -n/--name aliasName
- [x] 发布别名：s project alias publish --mversion version版本 --gversion 灰度版本 --weight version权重  -(n/name) aliasName
- [x] 删除别名：s project alias delete -n/--name aliasName

# Provision
- [x] 查看预留列表：s project provision list
- [x] 设置预留：s project provision add -q/--qualifier 版本 -c/--config 配置路径
- [x] 获取预留：s project provision get

**Comment by wss-git** [comment]
https://github.com/devsapp/fc-qualifier/releases/tag/v0.0.1   version 和 alias 地址

**Comment by wss-git** [comment]
> # Version
> * [x]  查看版本列表：s project version list
> * [x]  发布版本：s project version publish -d/--description 描述
> * [x]  删除版本：s project version delete -i/--id 版本号
> 
> # Alias
> * [x]  查看别名列表：s project alias list
> * [x]  获取别名详情：s project alias get -n/--name aliasName
> * [x]  发布别名：s project alias publish --mversion version版本 --gversion 灰度版本 --weight version权重  -(n/name) aliasName
> * [x]  删除别名：s project alias delete -n/--name aliasName
> 
> # Provision
> * [ ]  查看预留列表：s project provision list
> * [ ]  设置预留：s project provision add -q/--qualifier 版本 -c/--config 配置路径
> * [ ]  获取预留：s project provision get

# On-Demand
- [ ] 查看按量资源列表：s project on-demand list
- [ ] 设置按量资源：s project on-demand add -q/--qualifier 版本 -c/--config 配置路径
- [ ] 获取按量资源：s project on-demand get

**Comment by wss-git** [comment]
Provision/On-Demand:

https://github.com/devsapp/provisionAndOnDemand-
