### ISSUE TITLE
s init 模板共享同一个 FC，每次初始化一个别的模板，都会触发 s 检查已有 service 存在，需要选择 local 还是 remote 配置

### ISSUE THREAD

**Issue by hryang** [devsapp/fc#493]

**Comment by hryang** [comment]
如标题所述，s init 不同的模板，期望部署时没有冲突。但是因为共享了同一个 service，每次 s init 新的模板，都会跳出下面的选择。用户是比较懵逼的。
![图片](https://user-images.githubusercontent.com/626967/145171703-64d257ff-c071-4a5f-92a3-6063319703da.png)

建议 s 的模板使用不同的 FC service 名字，不要有冲突。

**Comment by anycodes** [comment]
- s init 模板共享同一个 FC：这个考虑是因为测试案例，不希望给用户创建过多的资源，所以这种demo，希望的是可以收敛起来；
- 每次初始化一个别的模板，都会触发 s 检查已有 service 存在，需要选择 local 还是 remote 配置 ：这个是现在的bug，新版本发布就会修复这个bug

**Comment by hryang** [comment]
新版本啥时候发啊？感觉目前的体验是比较糟糕的。如果新版本包含了太多改动，我们可以为这个 bug fix 单独发一个版本都行。

**Comment by anycodes** [comment]
这两周就发

**Comment by heimanba** [comment]
已经发布
