### ISSUE TITLE
s build custom/java 启动文件丢失

### ISSUE THREAD

**Issue by wss-git** [devsapp/fc#501]

**Comment by rsonghuster** [comment]
s build 针对 custom java 这个 case 比较特殊， 之前 s build 的 maven 行为针对的都是 java runtime 的行为；  这个行为需要改下， 比如在 custom runtime ， 大多都是 springboot 的项目，直接 mvn package 即可 https://github.com/devsapp/start-fc/blob/master/custom-function/java8/fc-custom-java8-http/src/s.yaml#L27-L29

**Comment by rsonghuster** [comment]
build 文档和  custom runtime 的示例里面已经没有  java 相关的东西了， 推荐做法都是 actions 自己去 mvn package
