### ISSUE TITLE
s.yaml 怎么声明多个 function

### ISSUE THREAD

**Issue by elonzh** [devsapp/fc#502]
根据 [Yaml 参考文档](https://github.com/devsapp/fc/blob/main/docs/Others/yaml.md), function 声明是一个对象而不是列表，似乎没有办法在一个 service 内声明多个 function ？

**Comment by anycodes** [comment]
https://github.com/devsapp/fc/blob/jiangyu-docs/docs/zh/tips.md#%E5%A6%82%E4%BD%95%E5%A3%B0%E6%98%8E%E9%83%A8%E7%BD%B2%E5%A4%9A%E4%B8%AA%E5%87%BD%E6%95%B0

**Comment by anycodes** [comment]
参考这个
