### ISSUE TITLE
【1213】关于Dev版本的问题

### ISSUE THREAD

**Issue by anycodes** [devsapp/fc#507]
- [ ] 1. 注意线上线下资源比对时候的默认值问题，例如：
![image](https://user-images.githubusercontent.com/21079031/145741434-811da21e-8d9c-449b-8e6f-a70b24848e63.png)
- [x] 2. 需要提醒清楚是什么发生了变化：
![image](https://user-images.githubusercontent.com/21079031/145741513-2edcd17a-b536-4468-8aa5-0904167ecae3.png)
例如，这里可以提示：

```
Service [web-framework] was changed, please confirm before deployment：
  * You can also specify to use local configuration through --use-local during deployment) 
```

- [x] 3. s plan显示的内容貌似有丢失：
![image](https://user-images.githubusercontent.com/21079031/145741814-ed5893e2-d591-4f30-9ab4-82ef5aba0d71.png)

- [x] 4. 现在部署的时候，每次都会提醒不一致，这个要严格按照我们的预定内容进行：

| 线上服务 | 线上函数 | 本地记录的服务 | 本地记录的函数 | 本地要部署服务 | 本地要部署函数 | 直接部署 | `use-local`              | `use-remote`                     |
| -------- | -------- | -------------- | -------------- | -------- |  -------- |  -------- | ------------------------ | ------------------------------------ |
| 存在     | 存在     | 与线上一致     | 与线上一致     |     -     |      -     | 无交互   | 线上服务与函数将会被更新 | 线上服务与函数不做任何操作           |
| 存在     | 不存在   | 与线上一致     | -              |     -     |    -     | 无交互   | 线上服务与函数将会被更新 | 线上服务不做任何操作，函数将会被创建 |
| 不存在   | 不存在   | -              | -              |  -              |  -              | 无交互   | 线上服务与函数将会被更新 | 线上服务与函数将会被创建             |
| 存在   | 存在   | 与线上不一致   | 与线上不一致   | 与线上一致   | 与线上一致   | 无交互   | 线上服务与函数将会被更新 | 线上服务与函数不做任何操作 |
| 存在   | 存在   | 与线上不一致   | 与线上不一致   | 与线上不一致   | 与线上不一致   | 有交互   | 线上服务与函数将会被更新 | 线上服务与函数不做任何操作 |

说白了，就是线判断上次本地部署是不是和当前线上状态一致，如果不一致，证明这个状态在过程中被通过其他途径修改了；再判断一下线上状态和现在s.yaml是否一致，如果不一致，那就说明了可能会有问题，就要提醒。就这一个场景。
- [x] 5. Help信息貌似有一个明显的空行
![image](https://user-images.githubusercontent.com/21079031/145742775-356dcb4a-c13d-46c4-8c15-d1703a54c04d.png)
- [x] 6. 参数后面的数据类型，shi fou k是否可以直接按照文档现在的形式进行提供？
![image](https://user-images.githubusercontent.com/21079031/145742894-8606fbdd-5c64-4f57-b537-f1aed972b9c4.png)
![image](https://user-images.githubusercontent.com/21079031/145742946-9f9e843c-3adf-4a7a-9e62-f5ddb5eae659.png)
- [x] 7. local start 通过 --custom 指定 auto，貌似不能用，而且提醒也有问题：
![image](https://user-images.githubusercontent.com/21079031/145743125-0055d67a-05d8-4dc4-9f71-7808addf4227.png)
- [x] 8. 帮助信息格式不正确，前面要有$，这个表示的是一个指令，否则你要有多行，用户很难知道，你这个是一个命令多行，还是多个命令
![image](https://user-images.githubusercontent.com/21079031/145743429-900c28b7-8640-464f-b399-41dc17d36209.png)
![image](https://user-images.githubusercontent.com/21079031/145743451-bc403627-02ec-4f66-be2d-1e9eebf7fe22.png)
- [x] 9. inovke命令的帮助信息和帮助文档严重不一致
![image](https://user-images.githubusercontent.com/21079031/145752813-54b39bff-4233-455d-b0c7-24eb428d8427.png)
![image](https://user-images.githubusercontent.com/21079031/145752848-44564831-9d64-408e-86f2-fd4a74342941.png)

- [ ]  10. #511

**Comment by anycodes** [comment]
- [ ] 关于辅助资源创建的说明：新版本辅助资源创建都需要在description中描述清楚，该辅助资源是做什么的，例如：

```
当前资源由Serverless Devs自动创建，用户向NAS【NAS-ID】中上传文件，与函数服务资源【mytestservice】关联。
```

![image](https://user-images.githubusercontent.com/21079031/145772994-b8d78fc9-788e-41f1-b6aa-a47aff9e3512.png)

**Comment by wss-git** [comment]
提示的一些问题，也需要解决：
https://github.com/devsapp/fc/issues/503
https://github.com/devsapp/fc/issues/500
https://github.com/devsapp/fc/issues/499
https://github.com/devsapp/fc/issues/493

**Comment by heimanba** [comment]
还有个需要优化的提示点 #511
