### ISSUE TITLE
s config get -l 官方文档与工具执行不一致

### ISSUE THREAD

**Issue by TigerWj** [devsapp/fc#510]
![image](https://user-images.githubusercontent.com/30013567/146116961-47978b05-680f-498c-80e1-eeb3af1a0f9f.png)

**Comment by TigerWj** [comment]
https://help.aliyun.com/document_detail/295894.html

**Comment by anycodes** [comment]
直接可以用`s config get`，我们这里进行了更新

**Comment by heimanba** [comment]
s config 命令已经更新，官网文档没有跟上。我来跟进下
