### ISSUE TITLE
预留实例创建错误透出

### ISSUE THREAD

**Issue by Ethan92** [devsapp/fc#514]
希望可以把预留实例创建过程的错误透出，方便问题排查

**Comment by rsonghuster** [comment]
> 希望可以把预留实例创建过程的错误透出，方便问题排查

这个有对应的文档， 或者是那个 api 返回的错误， 麻烦说详细点

**Comment by Ethan92** [comment]
getProvisionConfig 和 listProvisionConfig的response中增加了currentError（string）代表预留实例创建过程中遇到的错误

**Comment by wss-git** [comment]
直接透传的参数哈，是可以直接看到的
```` 
$ s provision put --target 1 --qualifier pre

$ s provision list

$ s provision get --qualifier pre
````
