### ISSUE TITLE
层模板

### ISSUE THREAD

**Issue by anycodes** [devsapp/fc#516]
在Devs里面，开一个层的专题，将常用的层放进去，形成一个层的template center。

这一部分大家可以在下面进行部分的讨论。

**Comment by heimanba** [comment]
是要弄一个层的组件模版吗，

**Comment by wss-git** [comment]
https://github.com/devsapp/layer-fc  层的插件

**Comment by heimanba** [comment]
公共层已经在设计中，等实现完成再开新ISSUE进行讨论
