### ISSUE TITLE
NAS组件支持交互式操作

### ISSUE THREAD

**Issue by lowkeyrd** [devsapp/fc#518]
我们NAS组件是纯命令式的使用，我们可以提供交互式的操作，在终端实时访问远程NAS盘，做到类似 https://github.com/HQarroum/inquirer-s3 这样的效果：

https://user-images.githubusercontent.com/5763215/146632529-13d29f5d-c495-43bd-882e-d40868c7f990.mov

**Comment by wss-git** [comment]
是不是我们提供了 实例登陆这个解决了呢

**Comment by wss-git** [comment]
https://github.com/devsapp/fc/issues/609
