### ISSUE TITLE
fun2s 转换 fun 到 s 的yaml， 有关 policy 的部分不正确

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#521]
fun2s 转换 fun 到 s 的yaml， 有关 policy 的部分不正确

ERROR:
MalformedPolicyDocumentError: The policy document is invalid. Statement not found when try to parse from Json.context:{,Version} ...

![image](https://user-images.githubusercontent.com/10919599/146887941-a0756384-ffef-44e1-92f0-24851be1efda.png)

**Comment by heimanba** [comment]
已经发布
