### ISSUE TITLE
s local 调试依赖问题

### ISSUE THREAD

**Issue by heimanba** [devsapp/fc#523]
### 复现步骤
- 自定义依赖包:
![image](https://user-images.githubusercontent.com/5129967/147211451-e1129f3b-3fa3-487a-801f-6567c6247bab.png)

- 先使用s build --use-local
- 执行 s start local指令报错

**Comment by wss-git** [comment]
两个怀疑方向：
1. build 失败了，拉镜像的过程失败了  这块没有优化好，因为如果磁盘满了导致镜像拉取不下来，组件没有显示错误
2. 是不是指令执行错的原因，由于只看到了指令，没有看到更具体的报错信息。本地启动的指令是 `s local start`

**Comment by wss-git** [comment]
未复现
