### ISSUE TITLE
cli-design 体验问题

### ISSUE THREAD

**Issue by heimanba** [devsapp/fc#529]
1. loading没有换行
![image](https://user-images.githubusercontent.com/5129967/147351957-4b97be11-0d52-467a-9228-439e67f6d92a.png)

2. 错误没有显示原因，用户比较懵逼(logConfig: auto)
![image](https://user-images.githubusercontent.com/5129967/147351776-2ef858be-99a1-4300-a4f2-e3e5b080e3fe.png)
3. 执行时间过长，大概需要20S，不太合理
![image](https://user-images.githubusercontent.com/5129967/147351846-2b8aa9bf-6ce0-4cce-a4e4-5c8e55bd76c9.png)

**Comment by rsonghuster** [comment]
这种场景在 logconfig 是 auto 中居多，  sls 那边提供的 create logstore 是异步的， 一致性不能保证， 需要 putlog 一条日志， 才能作为成功创建的标准， 耗费的时间确实比较多

**Comment by heimanba** [comment]
第二点:  logConfig：auto, 最终成功显示一条，失败上限 显示一条。重试间隔时间可能有点短

**Comment by heimanba** [comment]
和这个issue一起看
- [ ] https://github.com/devsapp/fc/issues/553

**Comment by heimanba** [comment]
已经解决，不会多次打印
