### ISSUE TITLE
STS部署好像不work了

### ISSUE THREAD

**Issue by lowkeyrd** [devsapp/fc#536]
使用STS的config，s 的命令不work了。STS是有效的
![image](https://user-images.githubusercontent.com/5763215/147466234-1d0303e6-118f-4d07-a09b-2fd78bd95f6c.png)

**Comment by xsahxl** [comment]
fix: https://github.com/devsapp/fc-common/pull/12/commits/221b43411605b429e15647a750b16ceb30b47325
fix: https://github.com/devsapp/domain/pull/15/commits/2b1000397b6f358ad5965bb8a123a68eb98fbffd
