### ISSUE TITLE
fc-deploy升级后，s deploy对于function的diff感知失效

### ISSUE THREAD

**Issue by lowkeyrd** [devsapp/fc#537]
如图，如果控制台改了函数配置，发现s deploy不会感知到函数存在的diff
![image](https://user-images.githubusercontent.com/5763215/147467452-2f700e56-044e-4696-9a57-7d27507bd206.png)

s deploy不提示diff
![image](https://user-images.githubusercontent.com/5763215/147467954-f251324b-c331-4e8c-9bf9-bde5e5f24a1c.png)

**Comment by heimanba** [comment]
发布fc-deploy新版本，已经修复
