### ISSUE TITLE
【fc-core】s build/local 没有开启 docker 导致的报错

### ISSUE THREAD

**Issue by anycodes** [devsapp/fc#546]
在没开启docker的时候报错信息：
![image](https://user-images.githubusercontent.com/21079031/147625321-678e0c67-02e9-484a-a638-3209892712e0.png)

这里我理解，应该直接error，并提醒用户安装和配置docker、打开docker，例如信息可以是：

```
Failed to start docker. Please ensure that docker is installed and started on your computer
```

**Comment by wss-git** [comment]
https://github.com/devsapp/fc/issues/155  重复

**Comment by wss-git** [comment]
https://github.com/devsapp/fc-local-invoke/pull/42
https://github.com/devsapp/fc-build/pull/26
开发已经完成
