### ISSUE TITLE
s logs 小问题

### ISSUE THREAD

**Issue by heimanba** [devsapp/fc#556]
1. -s 帮助命令简写错误
![image](https://user-images.githubusercontent.com/5129967/147678535-62b23474-5a17-4ac5-91db-004630acee08.png)

2. -end-time ， --start-time  这样顺序是不是 需要先 start-time 再 end-time 这样比较好些
![image](https://user-images.githubusercontent.com/5129967/147678566-209e2444-608d-434b-a683-72c9aac2eb8b.png)

3. 当没有配置 s logConfig 时候，去执行 s logs 命令,比如 s logs -t。退出码和样式不对
![image](https://user-images.githubusercontent.com/5129967/147678812-14fdefe7-3837-4806-ad5a-85e342fedd5f.png)
首先 ，样式应该是 WARNING
![image](https://user-images.githubusercontent.com/5129967/147678908-c35fa328-f18c-4d4c-8b32-5bee1cb10925.png)
这时候 需要 在Devs 工具层需要制定规范捕捉这样的异常。（）

**Comment by wss-git** [comment]
s logs -t => s logs --tail。  help 信息错了哈

**Comment by anycodes** [comment]
如果没有配置logStore，这个是组件层面的执行错误，应该是101退出
