### ISSUE TITLE
无法部署域名

### ISSUE THREAD

**Issue by anycodes** [devsapp/fc#56]
![image](https://user-images.githubusercontent.com/21079031/124547737-2b9e8300-de5f-11eb-99d2-8308992c8602.png)

**Comment by wss-git** [comment]
![image](https://user-images.githubusercontent.com/56686088/124550835-e03aa380-de63-11eb-89c6-d7dee121191a.png)
是不是丢包了，你将缓存删除了再跑一下试试看呢
