### ISSUE TITLE
custom runtime 应该也需要支持 build-link

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#570]
目前 在 python/nodejs/php 的官方 runtime，  已经支持了 buildlink 功能， 但是 custom runtime 没有支持

但是目前 python 和 php 没有支持单实例多并发， custom runtime 是一个重要的承载体

希望有  s build  -d   --use-link

use-link 参数， 可以显示指定 build-link 的行为， 不然 custom runtime 开发比如 pytorch， tensorflow 体验太差， 即使我们已经做了各种源加速

**Comment by rsonghuster** [comment]
或者应该更智能， 比如s build 发现了 package.json， 执行 npm install task 的时候， 应该就自动开启 build-link； 其他同理

**Comment by wss-git** [comment]
后续应该会支持 --use-link， 目前能力已经渐渐产出；等镜像版本升级上去就会支持这个功能

**Comment by anycodes** [comment]
`-h/--hot`这个参数是不是更能表现出热更新的能力

**Comment by wss-git** [comment]
沟通 s build 时候根据 fc-builders 检测机制检测函数的运行时 是否可以热更

**Comment by wss-git** [comment]
fc-local-invoke 已经支持
https://github.com/devsapp/fc-build/pull/27
https://github.com/devsapp/fc-core/pull/6
https://github.com/devsapp/fc-deploy/pull/147

custom runtime 支持 build-link （编译语言 build 之后热更）

**Comment by wss-git** [comment]
已发布
