### ISSUE TITLE
【bug】local invoke 的容器退出后却不会终止当前进程

### ISSUE THREAD

**Issue by heimanba** [devsapp/fc#572]
**Describe the bug**
如题。
可以使用样本工程 https://github.com/DevDengChao/aliyun-fc-issues/tree/master/fc-docker/custom-runtime/1.9.21/unexpected-request-body 进行测试。

**Screenshots**

![image](https://user-images.githubusercontent.com/16363180/145583711-91630371-480d-4b21-bfe4-941e48b142f9.png)

**Additional context**

Microsoft Windows [Version 10.0.19044.1415]
WebStrom 2021.3.1 Preview
Docker version 20.10.11, build dea9396

**Comment by heimanba** [comment]
## 关联issue
https://github.com/Serverless-Devs/Serverless-Devs/issues/362

**Comment by wss-git** [comment]
https://github.com/devsapp/fc-local-invoke/pull/42/commits/d780e3e327c8dd719ec8b7d5e979c13e9c8047c0

梳理一下逻辑，发现在 window 下如果不关闭 stream 就会 block 进程。
