### ISSUE TITLE
关于单个服务下有多个事件函数时 triggers 属性在 s.yaml 中的困惑

### ISSUE THREAD

**Issue by DevDengChao** [devsapp/fc#573]
目前看到的示例大多是一个 service 下面有一个 function, 而且 triggers 属性与 service 和 function 属性属于同一级别 (yaml 中的缩进级别)，此时可以把 triggers 理解为同一个 function 的多种触发方式。

如果项目需要将多个 function 归于一个 service，并在单个 s.yaml 里中进行定义 (eg: monorepo)，那该怎么理解与 service 和 function 同级别的 triggers 呢？ 🤣 

+ https://github.com/devsapp/fc/blob/main/docs/zh/yaml.md#yaml完整配置
+ https://github.com/devsapp/fc/issues/555

**Comment by lowkeyrd** [comment]
目前的yaml规范service、function、trigger是同级的：fc组件只负责一个service下的一个function以及该function下的所有triggers，其实隐式地表达了service->function的的1:N，以及function->trigger的1:N关系。

在一个s.yaml中声明同一个service的多个function，目前的做法是在所有function中都声明一遍service的配置，或者将service的配置声明到vars中，function使用vars(其实就是将service当成全局变量)。

目前主要的歧义点就是service，vars的做法也不能根本地解决service耦合带来的弊端，我提了个方案是希望将fc的service和function功能拆分成不同组件：https://github.com/devsapp/fc/issues/555，应该是比较彻底的解决方案，欢迎一起讨论下
