### ISSUE TITLE
进行中任务在工具中的状态输出优化

### ISSUE THREAD

**Issue by hryang** [devsapp/fc#577]
如下图所示，在等待进行中的任务（“Creating service”）执行时，工具不停的输出表示失败的 ❌，这会让用户非常困扰。因为任何失败都会对新用户产生负面的印象。这里合理的应该是转圈圈的图标，表示进行中任务。最后根据结果输出成功还是失败的图标。
![图片](https://user-images.githubusercontent.com/626967/148314025-22e5c648-5ed5-458d-8aea-2315494c58f1.png)

**Comment by heimanba** [comment]
这里是会因为配置sls日志，一直在重试中，并没有抛出错误，这种重试场景不应该展示给客户，还是显示Creating....中，已经在https://github.com/devsapp/fc/issues/529
跟踪解决。

**Comment by heimanba** [comment]
已修复，重试不会重复输出
