### ISSUE TITLE
端云联调在调试 SpringBoot 应用时，出现 host[http_backend] is not valid 错误

### ISSUE THREAD

**Issue by hryang** [devsapp/fc#578]
![图片](https://user-images.githubusercontent.com/626967/148342837-a318c68e-eadd-4299-885d-67898c31fb4f.png)

如图所示，在使用端云联调调试 SpringBoot 应用时，请求可以被正确路由到本地实例上。但是 SpringBoot 框架抛出 “host[http_backend] is not valid“  错误。

**Comment by rsonghuster** [comment]
已经 fix，远端函数镜像中使用了 nginx 代理， 而  sprinboot 项目， 使用 nginx 代理的时候 upstream 的名字不能有下划线
