### ISSUE TITLE
请提供函数资源的基本操作文档

### ISSUE THREAD

**Issue by Laura-monkey** [devsapp/fc#58]
目前函数资源的基本操作，例如创建函数/服务、更新函数/服务、删除函数/服务等，没有相关说明。可以补充一下。

**Comment by wss-git** [comment]
删除： https://github.com/devsapp/fc/blob/main/docs/Usage/remove.md
创建或者修改函数：https://github.com/devsapp/fc/blob/main/docs/Usage/deploy.md

https://github.com/devsapp/fc/blob/main/docs/readme.md#%E6%96%87%E6%A1%A3%E7%9B%AE%E5%BD%95
