### ISSUE TITLE
custom container  针对 public 镜像， 不应该强制有 push 操作

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#581]
![image](https://user-images.githubusercontent.com/10919599/148362431-37bf3bfd-bff7-4534-99c8-1d53c019a12b.png)

由端云联调发现的一个 fc-deploy 的问题， 端云联调， ts-remote 是我们提供的 public 镜像， 不应该强制有 push 操作， 有一大坨无效输出日志

**Comment by wss-git** [comment]
镜像部署逻辑修改后：
- 部署默认还是 push（之前的交互不变动）
方案一：
- 新增参数 skip-push，跳过 push 镜像的步骤然后部署；优点：变动最小
方案二：
- 部署时使用 --type config ， 进部署配置；有点不用新增新的参数，缺点：和语义不符

**Comment by wss-git** [comment]
经讨论 新增参数 --skip-push 强制跳过push 镜像的操作， 等待 PR 合并发布

**Comment by wss-git** [comment]
已发布
