### ISSUE TITLE
s.yaml 中定义多个项目后，help 等命令内容重复输出，体验很差

### ISSUE THREAD

**Issue by hryang** [devsapp/fc#583]
s.yaml 中定义了多个项目后，用户执行任何一个命令，都会在所有项目上执行一遍。对于 help 这种命令，这种行为其实是非常奇怪的。help 内容会重复输出 n 遍。

对于 help 命令，只需要输出一次就够了。

**Comment by wss-git** [comment]
短期内不会处理这类问题，这个先关掉了；后续可以关注相关讨论 https://github.com/devsapp/fc/issues/555
