### ISSUE TITLE
Unable to access java-8-http-trigger controller locally

### ISSUE THREAD

**Issue by NikolaChen2017** [devsapp/fc#584]
OS: Fedora 35
Had installed docker.
![image](https://user-images.githubusercontent.com/37110441/148419598-fcba18b5-ed7f-4f34-b924-2f63211dedf2.png)

**Comment by NikolaChen2017** [comment]
Suppose docker image have issues?
Invalid maximum heap size

**Comment by rsonghuster** [comment]
export FC_DOCKER_VERSION=1.10.0

We will use 1.10.0 by default in the next version release

**Comment by NikolaChen2017** [comment]
where can i set this attribute?

export FC_DOCKER_VERSION=1.10.0

**Comment by NikolaChen2017** [comment]
where can i set this attribute?

export FC_DOCKER_VERSION=1.10.0

**Comment by heimanba** [comment]
> where can i set this attribute?
> 
> export FC_DOCKER_VERSION=1.10.0

Yes, we will update the official version next week

**Comment by wss-git** [comment]
Published
