### ISSUE TITLE
s 在某个场景会出现  segment fault

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#585]
最新的 s 偶现 segment fault

![image](https://user-images.githubusercontent.com/10919599/148481302-2d23bcf9-2f14-4af3-bd84-1d5e354aeee1.png)

在 fc 自己的 云效 ci 流水线上， 必现：

![image](https://user-images.githubusercontent.com/10919599/148481635-049e1153-93bc-4b8a-93a7-cd09d1eb1b6e.png)

处理：
 云效流水的机器是复用的， 有 cache ...   他会自动针对这目录 /root/workspace 作为工作区间执行清理操作； 我流水线直接把 home 目录设置到这个目录， 这样每次安装 s 以及组件相关的东西， 应该执行完毕也会被清理

但是本质上 s 可能有些 bug 或者组件的 cache 会导致 segment fault

**Comment by heimanba** [comment]
s 工具重构后已经解决掉此问题
