### ISSUE TITLE
s.yaml不支持仅允许内网访问配置

### ISSUE THREAD

**Issue by lowkeyrd** [devsapp/fc#590]
![image](https://user-images.githubusercontent.com/5763215/148865029-edef614a-e0cb-4ad2-b4c1-6ee25bf90c41.png)

![image](https://user-images.githubusercontent.com/5763215/148865094-5e6f7bde-c70d-4b41-840d-de47709bc172.png)

**Comment by anycodes** [comment]
internetAccess + vpcConfig

应该是这两个配置的组合

**Comment by lowkeyrd** [comment]
> 
这两个配置都是出流量，没有入流量的设置。入流量的api目前好像还没对外暴露
