### ISSUE TITLE
custom runtime  bootstrap校验

### ISSUE THREAD

**Issue by heimanba** [devsapp/fc#591]
1. bootstrap 权限校验 （需要有可执行权限）
2. 文本换行符格式校验
![image](https://user-images.githubusercontent.com/5129967/148865764-ea9f501b-d2ec-4d47-893a-e1da6f809212.png)

**Comment by wss-git** [comment]
这个已经录入到了官方群的叮叮机器人，后续用户 at 他就会有这类可能性的提示

**Comment by rsonghuster** [comment]
> 这个已经录入到了官方群的叮叮机器人，后续用户 at 他就会有这类可能性的提示

不要太指望机器人， 假设这个用户没有进入我们的钉钉群呢？ 假设他不知道有这个机器人呢？

比较蛋疼的就是 windows 用户下面的这个问题， 后续可以主力推荐 customruntime config;  但是现在这个支持不太好， 比如 local invoke 就没有支持

**Comment by wss-git** [comment]
检测文件行尾序列 https://github.com/devsapp/fc-core/pull/9

**Comment by wss-git** [comment]
已经在部署和 local 阶段检测，并输出 warn
