### ISSUE TITLE
端云联调出现错误

### ISSUE THREAD

**Issue by wss-git** [devsapp/fc#601]
![image](https://user-images.githubusercontent.com/56686088/149856541-c01edaa7-7753-48e7-bd03-a89090412fd7.png)
端云联调出现这个错误， 应该是ping 的时候， 传一个 x-fc-request-id 这个 header 就行

**Comment by wss-git** [comment]
经测试 python 的 runtime 会出现这个错误。 是 this.runner.exec   curl  127.0.0.1:${caPort} 镜像抛出的一个异常，可以在项目搜索 await this.runner.exec(['curl', 定位到地址

两个思路（都没有能阻止输出）：
1. ['curl', '-s',`127.0.0.1:${caPort}`]    curl 的静默模式
2. container.modem.demuxStream(stream, devnull(), errorStream); 修改为 container.modem.demuxStream(stream, devnull(), devnull());    阻止镜像输出到主进程

**Comment by rsonghuster** [comment]
![image](https://user-images.githubusercontent.com/10919599/150639919-2be1ed22-ac94-43e9-aef7-22664981a4f1.png)

端云联调默认的 fc-docker 版本还没有修正

**Comment by wss-git** [comment]
> ![image](https://user-images.githubusercontent.com/10919599/150639919-2be1ed22-ac94-43e9-aef7-22664981a4f1.png)
> 
> 端云联调默认的 fc-docker 版本还没有修正

已经完成，待上面的问题修复发布

**Comment by git-qfzhang** [comment]
> 经测试 python 的 runtime 会出现这个错误。 是 this.runner.exec curl 127.0.0.1:${caPort} 镜像抛出的一个异常，可以在项目搜索 await this.runner.exec(['curl', 定位到地址
> 
> 两个思路（都没有能阻止输出）：
> 
> 1. ['curl', '-s',`127.0.0.1:${caPort}`]    curl 的静默模式
> 2. container.modem.demuxStream(stream, devnull(), errorStream); 修改为 container.modem.demuxStream(stream, devnull(), devnull());    阻止镜像输出到主进程

这个输出应该不是 curl 的输出，是函数容器中的 server 的输出，nodejs 的 server 不会输出这类信息，但是 python 会输出，这个具体原因未定位到，目前的解法是将探测服务是否启动的方式由 curl 更换为 tcp 层面探测，参考的是 fc-docker 中的做法， mr ：https://github.com/devsapp/fc-proxied-invoke/pull/41

**Comment by wss-git** [comment]
已经发布， 升级 docker 镜像版本到 1.10.1 和 python 报错的问题
