### ISSUE TITLE
export  access 环境变量不能被  s init 读取到

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#603]
export  access 环境变量不能被  s init 读取到
![image](https://user-images.githubusercontent.com/10919599/150095980-f9bf8767-ed51-4d54-98e8-56280018539f.png)

**Comment by xsahxl** [comment]
fix:https://github.com/Serverless-Devs/Serverless-Devs/commit/d89ee8d78a4f20a12633ac611f7ae09418ce7124
