### ISSUE TITLE
help 信息尽量将 ！ 去掉

### ISSUE THREAD

**Issue by xsahxl** [devsapp/fc#604]

**Comment by wss-git** [comment]
因为在命令行中 ！ 是一个运算符。用户如果直接 copy help 就会出现下面这种情况
![image](https://user-images.githubusercontent.com/56686088/150260902-b2ebad40-5c98-479b-b290-482564335fd2.png)

**Comment by wss-git** [comment]
因为在命令行中 ！ 是一个运算符。用户如果直接 copy help 就会出现下面这种情况
![image](https://user-images.githubusercontent.com/56686088/150260902-b2ebad40-5c98-479b-b290-482564335fd2.png)

**Comment by wss-git** [comment]
已完成并发布
