### ISSUE TITLE
Missing invocation type param in help info

### ISSUE THREAD

**Issue by MaskyYoung** [devsapp/fc#605]

**Comment by MaskyYoung** [comment]
missing invocation type param in help info while it's working:
s cli fc invoke --region cn-shanghai --service-name *** --function-name *** --event "" -a default --invocation-type async

**Comment by wss-git** [comment]
help 信息是有的  invocation-type 和 stateful-async-invocation-id 选项的哈
![image](https://user-images.githubusercontent.com/56686088/150475659-c4577934-8f7b-4090-b448-93d5fa9f6f4b.png)

**Comment by wss-git** [comment]
经沟通，需要在 examples 新增一个示例

**Comment by wss-git** [comment]
这个应该已经发布，如果不满足可以 reopen，然后再沟通
