### ISSUE TITLE
fc metrics 指令显示的监控大盘有些指标缺失

### ISSUE THREAD

**Issue by git-qfzhang** [devsapp/fc#606]
缺失的指标请参考控制台的监控大盘指标

**Comment by wss-git** [comment]
修改时可以带上这些  cc https://github.com/devsapp/fc/issues/558：
https://github.com/devsapp/fc/blob/main/docs/zh/command/metrics.md

[请按照文档的提醒进行优化一下](https://user-images.githubusercontent.com/21079031/147724373-94dfdedb-011e-4272-a8d8-c55e62005105.png)

另外希望可以；

输出上面的内容
尝试自动打开浏览器页面（try...catch...）

**Comment by wss-git** [comment]
https://github.com/devsapp/fc/issues/373  还有这个可以参考一下
