### ISSUE TITLE
【体验优化】build  时间太长，没有输出相关信息

### ISSUE THREAD

**Issue by heimanba** [devsapp/fc#611]
### build时候显示每步执行过程
现在build只会有个loading为`builder begin to build`,比如puppeteer的构建过程需要10到20分钟。这时候如果没有执行过程，用户没有耐心等待下去
![image](https://user-images.githubusercontent.com/5129967/150744575-f9ff81a2-6b31-4288-a599-af21c2ed01ee.png)

**Comment by rsonghuster** [comment]
可以和 #610 这个问题放在一起看

**Comment by wss-git** [comment]
看看 ora 的实例是否有输入输出流，如果没有的话这个可能就无法实现了
