### ISSUE TITLE
fc-build 支持 buildkit 能力不足

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#612]
https://github.com/devsapp/fc-build/blob/03e9923f5f3e0db2efe202b19f3f53a44c83f182/src/utils/builder.ts#L101-L123

![image](https://user-images.githubusercontent.com/10919599/150750359-21c74d8a-22de-4bcd-874a-4d628ddfa835.png)

1. 需要 push 参数， 应该是这样

```
execSync(`buildctl build --no-cache \
		--frontend dockerfile.v0 \
		--local context=${dockerFileDir} \
		--local dockerfile=${dockerFileDir} \
		--output type=image,name=${imageName},push=true`, {
	stdio: 'inherit',
});
```

2. host 也需要环境变量支持
3. 要解决push 权限问题， 可以直接模拟 docker login 的效果， 等价下面的行为

```
cat > ~/.docker/config.json <<EOF
{
  "auths": {
    "registry.cn-beijing.aliyuncs.com": {
      "auth": "$AUTH"
    }
  }
}
EOF
```

其中 $AUTH 为 $user:$pwd base64 后的值

**Comment by rsonghuster** [comment]
这个 issue 暂时先让我来解决吧

**Comment by wss-git** [comment]
https://github.com/devsapp/fc/issues/592  

这两说的同一个问题吗？是否需要一起解决呢？

**Comment by wss-git** [comment]
https://github.com/devsapp/fc/issues/361 
![image](https://user-images.githubusercontent.com/56686088/150931694-91b49e27-b022-4e4d-bf00-02e374cd5c09.png)

**Comment by rsonghuster** [comment]
是的

**Comment by rsonghuster** [comment]
对于云效中的 https://github.com/Serverless-Devs/Serverless-Devs/blob/master/docs/zh/cicd.md#%E4%B8%8E%E4%BA%91%E6%95%88%E7%9A%84%E9%9B%86%E6%88%90  这个场景：

需要云效那边改下模板：

- build 过程直接完成 build 和 push

- deploy 的时候， skip-push

**Comment by wss-git** [comment]
https://github.com/devsapp/fc-build/pull/37   在云效预发测试 dev 已经通过，等他们发布之后就可以直接发布

**Comment by wss-git** [comment]
已发布
