### ISSUE TITLE
去除 instanceSoftConcurrency 设置, 或者完善文档描述

### ISSUE THREAD

**Issue by iugo** [devsapp/fc#619]
目前发版出现如下问题:

```
📑 Config check:
Online status => Target Config
  description: "" => "This is default function description by fc-deploy component"
- instanceSoftConcurrency: 0
```

需要手动选择本地.

远端为什么有 instanceSoftConcurrency 设置, 是误检查还是?

如果是必要设置, 期望完善文档 https://github.com/devsapp/fc/blob/main/docs/zh/yaml.md

如果是不必要的设置, 期望去除该检查.

(部署的函数为自定义运行时)

**Comment by anycodes** [comment]
初步判断，是一个默认值的问题，我们这里尽快处理一下。

**Comment by wss-git** [comment]
https://github.com/devsapp/fc-plan/pull/7

**Comment by wss-git** [comment]
已忽略检测 instanceSoftConcurrency
