### ISSUE TITLE
Nasconfig auto 的一个 bug

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#620]
![image](https://user-images.githubusercontent.com/10919599/151481950-bb3b2e9e-0c1c-4a1e-b2c0-2799eb605c53.png)

![image](https://user-images.githubusercontent.com/10919599/151482044-3a5327f1-f405-4278-a88b-b0604cd776ac.png)

nasconfig: auto,   s deploy 以后， nas 挂载点不是预期的

**Comment by rsonghuster** [comment]
执行了 s remove， 然后重新 s deploy 就 OK了； 但是上面出现那种不对齐的情况， 我理解应该需要解决的。 和预期不一致， s nas 怎么看都是对的， 一旦调用函数， 就出现挂载nas失败

**Comment by wss-git** [comment]
已修改为从线上获取配置，不再从缓存获取
