### ISSUE TITLE
【fc-core】 本地build时候判断编程语言不正确

### ISSUE THREAD

**Issue by heimanba** [devsapp/fc#628]
## 本地build校验不正确
不需要本地的语言版本和yaml中配置的runtime 的版本一致。因为大部分语言有向下兼容特性。除非像`python3`和`python2` 这样的大版本的更新

#### nodejs 
都向前兼容，比如yaml中配置的是 nodejs 14，本地只要大于nodejs14即可

#### python
python 2和python3不兼容，但是相同大版本可以兼容，比如yaml配置是python3,本地可以是`python3.6` ,`python3.9`等任意版本

#### java
java版本也是向下兼容的， `Java8` 兼容`java7`以及`Java6`

## 代码路径 
fc-core/src/common.ts checkLanguage方法

**Comment by wss-git** [comment]
仅需要兼容 nodejs 已发布
