### ISSUE TITLE
nas 可以考虑增加 ui 体验

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#635]
https://github.com/devsapp/start-nas-ui

比如 s nas ui 这种指令， 直接给用户一个 web UI 管理 NAS 文件和文件夹

**Comment by wss-git** [comment]
这个是不是直接推荐那个组件就可以了，内置到组件中有些麻烦

**Comment by rsonghuster** [comment]
第一版， 可以考虑这么做，但是命令行要有提示让用户知道吧

**Comment by rsonghuster** [comment]
直接和 nas 那边合作
