### ISSUE TITLE
为调用函数增加打印request id 和 event

### ISSUE THREAD

**Issue by VBill** [devsapp/fc#637]
如题，希望为 s cli fc invoke，以及 s cli fc-api invokeFunction 增加开关，从而能打印 request id 和 s工具传给函数的 event，方便调试。

**Comment by wss-git** [comment]
![image](https://user-images.githubusercontent.com/56686088/154426251-ce2afa29-673e-40e3-a8da-17a0cd52cd49.png)
经沟通 s cli fc invoke  --debug 模式能够支撑此需求
