### ISSUE TITLE
nas 辅助函数能收敛到一个 service 吗

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#638]
![image](https://user-images.githubusercontent.com/10919599/154419874-c8f08599-be1b-45eb-9d04-9e82bac95f62.png)

nas 辅助函数能收敛到一个 service 吗

**Comment by wss-git** [comment]
目前来看不行，原因是：

主函数的配置如下，假如 nas 不存在 /test 这个目录，那么此时这个主函数的服务下所有的函数都不能被访问。
````
nasConfig:
  nasDir: /test
  fcDir: /mnt/auto
````
_FC_NAS_***ensure-nas-dir-exit-service 这辅助服务会绑定主函数nas 的根目录，然后创建 test 这个目录
_FC_NAS_*** 这个辅助函数和主函数的 vpc/nas/role 完全一致，然后正常使用指令来操作nas
