### ISSUE TITLE
s sync的时候添加默认密钥信息

### ISSUE THREAD

**Issue by anycodes** [devsapp/fc#64]
在执行s sync的时候，需要把密钥信息也添加上。这个要看用户指定的密钥信息是什么，对应的填写到Yaml中

**Comment by wss-git** [comment]
https://github.com/devsapp/fc-sync/commit/762cd673358892377c7c374691351211dbeda308

已经添加

**Comment by wss-git** [comment]
https://github.com/devsapp/fc-sync/releases/tag/0.0.7
