### ISSUE TITLE
nas 辅助函数能设置大点的内存吗

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#640]
nas 辅助函数能设置大点的内存吗？ 感觉针对 wordpress 这种 php 工程， 执行下 rm-rf 要等很久， 很费劲

**Comment by wss-git** [comment]
这个可以在控制台直接修改的哈，只要不修改服务的一些配置 就不会强制覆盖

**Comment by rsonghuster** [comment]
> 这个可以在控制台直接修改的哈，只要不修改服务的一些配置 就不会强制覆盖

这个是我们自己知道的，但是用户咋知道呢？ 为什么不默认搞大点， 这个本来就是 serverless 的， 不会花费很多钱吧

**Comment by wss-git** [comment]
函数默认升级到 1536 MB, 也可以通过环境变量 NAS_HELPER_SERVERVICE_MEMORY_SIZE 来控制大小

**Comment by rsonghuster** [comment]
如讨论所示， 可以考虑提供两种内存规格的函数， 当使用 upload 这种命令， 是并发多个函数实例同时处理， 可以考虑小内存；  比如 s nas command 这种命令， 提供内存规格大的函数， 提高 ls  rm 的体验， 不然针对 wordpress 这种工程在 nas 上的管理， 命令反馈太慢了
