### ISSUE TITLE
【文档】s nas upload上传依赖，提示用户如何添加环境变量

### ISSUE THREAD

**Issue by heimanba** [devsapp/fc#648]
s nas 上传node_modules代码包，没有执行s build，没有提示用户添加环境变量，代码不生效

**Comment by anycodes** [comment]
s build 应该是手动执行的吧？是否提醒增加环境变量，应该是有没有执行build做提醒吧？如果用户没做s build，系统没办法确定是否要加环境变量

**Comment by heimanba** [comment]
没有执行s build, 但是确实有这样的场景：在nodejs中很多的包是不需要s build，更习惯使用自己执行npm install，但是我在使用nas上传的时候，需要做node_module的寻址。这时候我并不知道添加环境变量这个工作。所以是不是满足这样的条件
1. 通过nas上传过包
2. 没有执行s build
这时候在部署`s deploy`后，**提示用户 需要加上环境变量**

**Comment by heimanba** [comment]
讨论啦下，产品化方案不太好做， 可以现在文档体现。
