### ISSUE TITLE
版本/别名智能提示

### ISSUE THREAD

**Issue by git-qfzhang** [devsapp/fc#65]
发布别名/删除版本/删除别名时，若没有指定别名或者版本，需要组件去 get 线上已有的别名或者版本，供用户选择后再进行后续操作。这样用户就不需要去主动去查询有哪些已有的别名/版本。

**Comment by wss-git** [comment]
删除的大致流程，所以 删除版本/删除别名 不提供选择
![yuque_diagram](https://user-images.githubusercontent.com/56686088/127250707-9f98b1c4-fc6d-4a73-8410-e4f7350002bf.jpg)
