### ISSUE TITLE
s build -d nodejs 版本问题

### ISSUE THREAD

**Issue by heimanba** [devsapp/fc#651]
1. s build -d 可以使用自定义的nodejs runtime 进行安装
2. s build -d 安装nodejs 的时候，应该拷贝package-lock.json 进行安装比较合适

**Comment by wss-git** [comment]
结论
问题一：
实现思路1（优先尝试），先将 code 目录先硬链到缓存（原因是速度快，同步code和缓存的变动），然后再下载依赖
实现思路2，先将 code 目录 copy 到缓存，然后再下载依赖

问题二：
package-lock.json 不能 copy，因为可能会声明非 linux 的依赖包

**Comment by DevDengChao** [comment]
如果 fc 的 docker image 能根据用户定义的环境变量去安装指定的运行时会不会更好一些 ?
这样的话, 用户就只需要将预期的 (与开发环境一致的) 运行时版本声明到 s.yaml 的环境变量中, 就能使用一致的运行时进行本地的构建和云端的运行了.

聆听建议: [建议 Custom Runtime 支持基于环境变量安装指定版本的运行环境功能](https://connect.console.aliyun.com/connect/detail/377968)

**Comment by wss-git** [comment]
> 根据用户定义的环境变量去安装指定的运行时会

经过测试和验证，这个build的能力是没有问题的；是用法的问题。build 时需要将环境包放在 code 目录下，然后将环境变量配置正确

**Comment by wss-git** [comment]
> Reference in

这个已经有相关的同学去评估，后面在 #668 跟踪
