### ISSUE TITLE
s local start 针对 custom runtime config 的一个异常bug

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#652]
s local start 针对 custom runtime config 的一个异常bug

#### 复现方法
1. s init fc-custom-java8-http -d fc-custom-java8-http
2. s.yaml 的 caPort 和 resource 都改成 8080
![image](https://user-images.githubusercontent.com/10919599/156096518-c3be34fe-4da6-412f-8367-b1f199c914e6.png)

3.  在 code 目录， 执行 mvn package
4.  s local start, 必现如下报错

<img width="1454" alt="image" src="https://user-images.githubusercontent.com/10919599/156096635-4fb9be60-0bf8-40f4-99e2-602c48adef6c.png">

**Comment by wss-git** [comment]
如果设置了 8080，s local start 会启动一个端口 8081，而 8081 是被其他软件长期占用的一个端口，所以调试的时候需要手动指定暴露的端口，例如：`s local start --server-port 9090`

**Comment by wss-git** [comment]
这个是 custom 启动设计有关，每次启动都是一个固定端口【 caPort + 1 】

**Comment by rsonghuster** [comment]
最好的做法， 应该是持续 +1， 知道找到一个可用的端口

**Comment by wss-git** [comment]
之前这么做过但是被推翻了（做了一半被搁浅了），因为用户已经已知了一个端口，不利于 postman 和 脚本调试
