### ISSUE TITLE
nas 辅助函数上传/删除大文件时候超时

### ISSUE THREAD

**Issue by heimanba** [devsapp/fc#655]
现在默认的时间为`600s`,比较容易超时。超时时间可以设置长些

![image](https://user-images.githubusercontent.com/5129967/156277074-83285c8e-599d-4d58-be13-7eece8a5fa66.png)

**Comment by wss-git** [comment]
https://github.com/devsapp/nas/pull/31  时间升级到 1800s

**Comment by rsonghuster** [comment]
> [devsapp/nas#31](https://github.com/devsapp/nas/pull/31) 时间升级到 1800s

改成了性能型实例？
