### ISSUE TITLE
nodejs s local invoke 后引用不到层里面的模块

### ISSUE THREAD

**Issue by zou-yu** [devsapp/fc#660]
直接 invoke 可以引用到层的模块，local invoke 不可以

**Comment by zou-yu** [comment]
s proxied invoke 也是会这样哦，是需要把层的东西下到本地吗

**Comment by wss-git** [comment]
local invoke 不支持加载远端环境，所以不支持层，只能下载到本地 然后可以部署的时候使用 .fcignore 忽略这个文件或者文件夹

**Comment by wss-git** [comment]
proxied invoke 这个仅仅是打通网络环境，但是执行环境还是本地 所以也不支持层

https://github.com/devsapp/fc/blob/main/docs/zh/command/proxied.md

**Comment by zou-yu** [comment]
把层放到本地搞定了，谢谢
