### ISSUE TITLE
s remote invoke 远程调试无法建立会话

### ISSUE THREAD

**Issue by zou-yu** [devsapp/fc#662]
<img width="798" alt="image" src="https://user-images.githubusercontent.com/26666752/156860637-38a60e91-ee28-4ca4-a8a5-76f59edaad86.png">
traceId: a45e60e4721d1646441632764
requestId: 5DB55296-C3FD-55A4-9F8B-3506137D5D4E

**Comment by wss-git** [comment]
抱歉，这个目前有一些集群还不支持。我们已经对文档做了一些隐藏的处理，您可以尝试[实例登陆](https://github.com/devsapp/fc/blob/main/docs/zh/command/instance.md)和[端云联调](https://github.com/devsapp/fc/blob/main/docs/zh/command/proxied.md)
