### ISSUE TITLE
s proxied setup 后，只能 s proxied invoke 一次，第二次 s proxied invoke 会报错

### ISSUE THREAD

**Issue by zou-yu** [devsapp/fc#664]
1. s proxied setup --config vscode --debug-port 4001
2. 开启 vscode 调试
3. s proxied invoke --event "{}" ## 第一次 invoke 是 OK 的
4. s proxied invoke --event "{}" ## 第二次 invoke 会报错
```
FC Invoke Result:
{
  errorMessage: 'Process exited unexpectedly before completing request (duration: 1003ms, maxMemoryUsage: 0.00MB)'
}


End of method: proxied
```
如果想再次调试，只能 CTRL C 之后重新 s proxied setup了，也就是说每次 s proxied setup 只能调试一次

**Comment by rsonghuster** [comment]
Process exited unexpectedly before completing request  这个很有可能是您本地执行函数函数逻辑， 把本地执行环境中 runtime 的 http server 搞挂了，导致第二次 s proxied invoke， 线上流量打回到本地的时候， 本地的 runtime，不能接受请求了

建议您最好还是先把这个搞挂 runtime 的原因找出来， 看看是不是 oom 或者什么其他原因触发了 os.exit

**Comment by rsonghuster** [comment]
![image](https://user-images.githubusercontent.com/10919599/159240103-7e92a63c-6b64-4f56-bbec-acc7c36c3bd4.png)

预留调度模式从 V1 灰度到 V2,   v2 第一次预留调用， 可能会切换一次预留实例， 这个影响联调

终态是预留调度 V2 本身解决这个， 暂时 work around 方案如上图

**Comment by wss-git** [comment]
已经做了处理， 先关闭了哈。如果还有问题重新提一个 issue 或者 reopen

**Comment by rsonghuster** [comment]
目前已经默认全部是 V2 模式了，顺序改成这样  put ondemand config -> invoke（预期出现429） -> put provision -> debug， 这个可以解决主要问题， 其他可能依然会出现问题的场景：

用户的配置需要是这个：
<img width="534" alt="image" src="https://user-images.githubusercontent.com/10919599/190541083-44d3c97c-feec-493c-80a8-6601b27f9a3d.png">

目前默认已经是这个了， 但是有少数账号这个值是 default
