### ISSUE TITLE
如果 fc 的 docker image 能根据用户定义的环境变量去安装指定的运行时会不会更好一些 ?

### ISSUE THREAD

**Issue by wss-git** [devsapp/fc#668]
如果 fc 的 docker image 能根据用户定义的环境变量去安装指定的运行时会不会更好一些 ?
这样的话, 用户就只需要将预期的 (与开发环境一致的) 运行时版本声明到 s.yaml 的环境变量中, 就能使用一致的运行时进行本地的构建和云端的运行了.

聆听建议: [建议 Custom Runtime 支持基于环境变量安装指定版本的运行环境功能](https://connect.console.aliyun.com/connect/detail/377968)

_Originally posted by @DevDengChao in https://github.com/devsapp/fc/issues/651#issuecomment-1054204250_

**Comment by DevDengChao** [comment]
期待 QwQ

**Comment by wss-git** [comment]
参考 https://github.com/Serverless-Devs/Serverless-Devs/discussions/434   除了加速和提示都已经支持
