### ISSUE TITLE
nas init 指令产物 nas upload 的用不到了

### ISSUE THREAD

**Issue by wss-git** [devsapp/fc#671]
#### 背景

nas init 指令之后，对 nas 的设计经过了几次改造
改造1. deploy 过程会对 nas dir 进行尝试创建
改造2. deploy 时 nas auto 的配置优先使用主函数的线上配置
改造3. nas 指令配置不再从缓存获取配置，而是从线上的主函数获取配置（nas init 的 bug）

#### nas init 的能力
nas的创建 nas dir 进行尝试创建，辅助函数的部署 

nas init 是不是可以下掉了，因为他的能力都在 deploy 中做掉了

**Comment by wss-git** [comment]
nas 的操作建议都在 post-deploy 中做

**Comment by anycodes** [comment]
不要突然下掉命令。兼顾一下老版本。别把人家自动化的弄挂了。

**Comment by wss-git** [comment]
nas init 一作为废弃掉能力，但是不会删除。issue先关闭掉了
