### ISSUE TITLE
s build --use-docker 支持自定义build脚本

### ISSUE THREAD

**Issue by lowkeyrd** [devsapp/fc#675]
场景：Mac 用户，Node Runtime，需要通过 npm install 安装 node_modules ，并且需要通过 npm run build 产出构建物。
使用 s 工具：不支持自定义命令，nodejs只执行npm install

需求：支持用户自定义命令或者自定义脚本，在docker环境中执行自定义的build逻辑

**Comment by wss-git** [comment]
已发布：可以通过 --command 或者 s build --script-file="./install.sh"
