### ISSUE TITLE
关于 build 能力，急需升级

### ISSUE THREAD

**Issue by anycodes** [devsapp/fc#681]
思路：**https://github.com/Serverless-Devs/Serverless-Devs/discussions/434**

今天在做一个AI项目，需要安装torch，大概800M，由于build镜像中默认是阿里源，且阿里源的速度并不是很快，导致完全无法安装，浪费了几个小时。后来实在受不了了，改成了进入实例，用速度相对更快的清华源进行安装，最终成功。所以，上面的升级思路中，提供多种build方案是非常有必要的，希望尽快支持。

**Comment by anycodes** [comment]
另外，build出错，貌似都是没有message？这个没有messag很不友好

![image](https://user-images.githubusercontent.com/21079031/159131398-3d4d86eb-acc3-4953-8ec3-25943dbfe044.png)

**Comment by rsonghuster** [comment]
这个如果 pip 做了跟 apt-get.list 一样的 cache 加速， 应该会缓解出现 pip 源限流， 因为你本地 cache了， 限流的原因， 你每次 s build 到来一次， 而且每次等待的时间很长。。。

**Comment by wss-git** [comment]
已发布，可以支持 --custom-arg 来解决了
