### ISSUE TITLE
如何确定NAS地址？

### ISSUE THREAD

**Issue by anycodes** [devsapp/fc#684]
自己在控制台创建了一个nas，然后想要通过s工具进行绑定，突然发现不知道去哪里获取nas地址：

![image](https://user-images.githubusercontent.com/21079031/159131631-7966ccfe-53a9-46eb-9bae-996276239cec.png)

**Comment by anycodes** [comment]
后来自己通过抓包获取到，但是我觉得这个不太合理。

**Comment by rsonghuster** [comment]
挂载使用户那里就有挂载点吧

**Comment by anycodes** [comment]
![image](https://user-images.githubusercontent.com/21079031/167762347-9ce3d6ba-c949-429b-980c-77fc6d7be0d0.png)

这个鬼东西竟然是url的logo，我吐了啊
