### ISSUE TITLE
codeUri 是否指定多个路径？

### ISSUE THREAD

**Issue by heimanba** [devsapp/fc#698]

**Comment by anycodes** [comment]
codeUri指定多个路径的目的是什么？是不是会出现覆盖的问题？

**Comment by heimanba** [comment]
比如在plugin的场景下，我的需要将静态文件的代码上传上去的同时还需要将server.js的文件上传上去，这时候他们的路径肯定不在一个地方。这时候我们只能比较hack的方式在部署的时候，将静态网站的代码和server.js copy到同一个地方。如果codeurl能够指定多个路径进行合并 就完美了

**Comment by heimanba** [comment]
这个设计也比较hack暂时关闭掉
