### ISSUE TITLE
s deploy的时候需要注意

### ISSUE THREAD

**Issue by anycodes** [devsapp/fc#699]
1. deploy的时候，这里Target config改成Target status：
![image](https://user-images.githubusercontent.com/21079031/160762089-8fe3e37d-faee-4034-9384-2d81cf8ea45a.png)
2. 当用户执行s deploy --type code，只提醒代码的异动就好了，不需要提醒其他的异动。同理，如果是只部署了trigger，理论上函数和服务的异动亦无需提醒，以此类推

**Comment by wss-git** [comment]
已经修复
