### ISSUE TITLE
自定义镜像  s deploy 会默认生成 public 的 acr 仓库

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#700]
自定义镜像  s deploy 会默认生成 public 的 acr 仓库

![image](https://user-images.githubusercontent.com/10919599/160784529-aaf04f8f-307a-4f61-95b9-833d2ef00613.png)

**Comment by wss-git** [comment]
这个需要再看一下代码，是希望生成私有的？

**Comment by wss-git** [comment]
已发布
