### ISSUE TITLE
S info 线上函数不存在的时候，应该更友好的提示

### ISSUE THREAD

**Issue by heimanba** [devsapp/fc#710]
![image](https://user-images.githubusercontent.com/5129967/162187626-0c4e710d-5fae-4e64-b8d7-10e189e752b8.png)

应该更加友好的提示，而不是报错提醒哈

> s remove 也是同样的问题
![image](https://user-images.githubusercontent.com/5129967/162188439-2763fdf1-b27c-49ba-964e-b5a364d7c2f3.png)

![image](https://user-images.githubusercontent.com/5129967/163144014-867f2d2b-8dcc-4dbf-b812-3b9adc8d3d6b.png)

**Comment by wss-git** [comment]
梳理了一下，这个优化不太好做。影响有点大：fc 系列几乎都依赖它，如果修改了异常逻辑可能会造成其他影响；最关键的应用中心也依赖它。所以这个暂时先不改动
