### ISSUE TITLE
S 支持快速创建 Nodejs17 等基于层的 Custom Runtime

### ISSUE THREAD

**Issue by loganhz** [devsapp/fc#711]
现在控制台上已经可以开箱即用的创建 node17 等 Custom Runtime 了。

需要工具也对齐一下。用户希望可以不在控制台上上操作，只用 S 工具也能做到同样的效果。

原理就是使用 Layer 的能力，

1. 使用我们的 OSS 创建 Layer，如果 Layer 已经存在无需创建。目前前端是创建了以 _fc_auto_created 结尾的各种 Layer。（我们的 OSS 里已经有很多 nodejs/python 的版本了，和控制台对齐就ok）
2. 把相关 layer 中的 bin 加到 PATH 环境的前面，例如 `/opt/node-v17.8.0-linux-x64/bin`

![image](https://user-images.githubusercontent.com/21168270/162409293-e1d4bdeb-973e-4da8-a1fa-34b5e69dab0f.png)

**Comment by heimanba** [comment]
fc-layer组件已经支持
