### ISSUE TITLE
nas 的 check dir 辅助函数可以删除

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#719]
用户指定nas目录不存在时自动创建（白寂）：神龙已具备该能力，待确认，ecs上能力补齐

这个功能即将发布上线， s 工具在这块的辅助 service 和 函数可以去除， 提高s deploy 的执行效率

**Comment by heimanba** [comment]
👍赞啊

**Comment by wss-git** [comment]
https://github.com/devsapp/nas/pull/34/commits/264fecdd8d06e124433f1bc76af9504fa64da011 done

**Comment by wss-git** [comment]
已发布
