### ISSUE TITLE
commandParse 方法解析的结果异常

### ISSUE THREAD

**Issue by wss-git** [devsapp/fc#723]
复现 case：
````
s build --custom-env='{"pythonVersion": "python3"}' --custom-args='-i http://test.com' # 预期

s build --custom-env '{"pythonVersion": "python3"}' --custom-args '-i http://test.com' # 非预期
````
![image](https://user-images.githubusercontent.com/56686088/163953951-3a17c8f1-c9ce-41b2-8690-94c65c8bbed3.png)
![image](https://user-images.githubusercontent.com/56686088/163954161-5755e253-4714-4fac-a3ca-f9c924ff7e32.png)

应该是 `-`  带来的一个解析问题

**Comment by wss-git** [comment]
s build --use-docker --custom-env '{"pythonVersion": "python3"}' --custom-args "-i http://test.com"

custom-env: '{"pythonVersion": "python3"}'
custom-args: true
i: http://test.com



s build --use-docker --custom-env='{"pythonVersion": "python3"}' --custom-args="-i http://test.com"

custom-env: '{"pythonVersion": "python3"}'
custom-args: "-i http://test.com"

**Comment by heimanba** [comment]
增加 `{stopEarly: true}` 参数
https://github.com/substack/minimist

**Comment by wss-git** [comment]
不支持这么复杂的 case
