### ISSUE TITLE
s invoke 支持http异步调用

### ISSUE THREAD

**Issue by heimanba** [devsapp/fc#725]
需要支持HTTP触发器 `s invoke invocation-type async`， 现在只支持事件触发器类型

只需要在`header`头加上 `"X-Fc-Invocation-Type":"Async"`
https://help.aliyun.com/document_detail/71229.html#h3-url-2

**Comment by heimanba** [comment]
同时HTTP异步的默认 X-Fc-Log-Type 头为 None

"headers": {
    "X-Fc-Invocation-Type": "Async",
    "X-Fc-Log-Type": "None"
  }

**Comment by wss-git** [comment]
已支持
