### ISSUE TITLE
s local invoke 和 s local start 后续需要换成 root

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#726]
s local invoke 和 s local start 后续需要换成 root， 比如现在 custom runtime 已经是 root 启动了， 线上没有问题， local start 和 local invoke 有问题， 比如 custom runtime 启动 nginx 会有权限不能启动的问题

# 详情进展：

## custom runtime
- 不配置 nas， 默认使用 root
- 配置nas, 使用 nas 的 config， 同时 nas 的 config 可以是 root

## custom container
- dockerfile为准， 默认是root, 即如果 dockerfile 里面设置了其他非 root user, 但是 nas config 设置了 0 0 ， 就是还是以非 root user 运行

## 官方runtime
- 不配置 nas, 默认是随机用户 10001-10999 ===》 这个下个月支持默认是 root
- 配置了 nas， 使用 nas 的 config， 同时 nas 的 config 可以是 root

**Comment by wss-git** [comment]
https://github.com/devsapp/fc-local-invoke/pull/59

**Comment by wss-git** [comment]
已发布
