### ISSUE TITLE
build 体验优化细节

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#727]
build 体验优化细节：
1.  s-install apt 的时候， 有无效的空目录 tmp， 应该删除
<img width="947" alt="image" src="https://user-images.githubusercontent.com/10919599/165092443-91ab67b9-f27f-487c-abf9-080de1b0e7d1.png">

2.  builder 过程最好显示下进度， 不然有多个lib 安装， 一直转圈有点让人捉急

![image](https://user-images.githubusercontent.com/10919599/165092611-d713a7c1-a336-4c76-a4ad-32d65bcd9bfc.png)

**Comment by wss-git** [comment]
已发布
