### ISSUE TITLE
云效里面使用 s 工具的文档要更加细致点

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#729]
云效里面使用 s 工具的文档要更加细致点， 不然根本不知道要选择

构建里面的  ServerlessDevs 模板

**Comment by wss-git** [comment]
https://docs.serverless-devs.com/serverless-devs/cicd#%E4%B8%8E%E4%BA%91%E6%95%88%E7%9A%84%E9%9B%86%E6%88%90
