### ISSUE TITLE
s build  命令重构后 issue 汇总

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#730]
s build  命令重构后， 相关的文档也需要更新

https://github.com/Serverless-Devs/Serverless-Devs/discussions/434

**Comment by rsonghuster** [comment]
#728 

#727

**Comment by rsonghuster** [comment]
#681

**Comment by rsonghuster** [comment]
#610

**Comment by rsonghuster** [comment]
还有一个事情， apt-get.list 会强制走 docker,   这个是不应该的，  --use-local 也应该是可以的

![image](https://user-images.githubusercontent.com/10919599/165452698-ae39672a-ce22-4b0d-9c00-e82910323e59.png)


比如我在 sandbox 内执行 s-install 是没有问题的：

<img width="1487" alt="image" src="https://user-images.githubusercontent.com/10919599/165452628-f04260a0-8ab9-4154-8c15-bfd02b9dd68d.png">

**Comment by wss-git** [comment]
已经优化，测试中
