### ISSUE TITLE
s invoke 日志显示异常

### ISSUE THREAD

**Issue by lowkeyrd** [devsapp/fc#736]
s invoke 终端显示的日志有问题，控制台正常
工具日志：
![image](https://user-images.githubusercontent.com/5763215/166941951-6bacf9d8-ef4d-4b49-b667-83f9d50b3b58.png)

控制台日志：
![image](https://user-images.githubusercontent.com/5763215/166943265-1d92bab9-80ba-4ef0-b341-7141266aa120.png)

**Comment by wss-git** [comment]
一直在复现类似问题，先 close 掉。如果后面复现麻烦 reopen 或者重新提一个 issue
