### ISSUE TITLE
s instance list，展现信息时，使用的是 s 模块名，而不是 FC 函数的名字。

### ISSUE THREAD

**Issue by hryang** [devsapp/fc#737]
如下图所示，s instance list，展现的信息是 s 的模块名，而不是 FC 的函数名。在 s.ymal 中，模块名（s service 的名字）是 vscode-server，函数名是 webide-server，这里希望 s instance list 输出的信息不是 vscode-server，而是 webide-server。因为实例是属于某个函数的。用户直观的认识是在 FC 函数下查看多少个实例。
![图片](https://user-images.githubusercontent.com/626967/167740579-b699b469-3352-4a05-974f-fb4d608caabb.png)

**Comment by wss-git** [comment]
![image](https://user-images.githubusercontent.com/56686088/176583866-2e6bc3dd-5818-47ba-92c4-0ac4b17f6a17.png)
已支持
