### ISSUE TITLE
s 在没有指定 component 时错误信息优化

### ISSUE THREAD

**Issue by hryang** [devsapp/fc#738]
我故意把 comment: fc 注释掉，s 报如下错误信息：

s deploy
✖ Message:

ERROR:

**Please check the value of source in loadComponent function.**

TraceId:     0a4b9259c0bb1652234469226
Environment: @serverless-devs/s: 2.1.0, core: 0.1.35, s-home: /Users/hryang/.s, darwin-arm64, node-v16.15.0
Documents:   https://www.serverless-devs.com
Discussions: https://github.com/Serverless-Devs/Serverless-Devs/discussions
Issues:      https://github.com/Serverless-Devs/Serverless-Devs/issues

Please copy traceId: 0a4b9259c0bb1652234469226 and join Dingding group: 33947367 for consultation.
You can run 's clean --all' to clean Serverless devs.

load Component function 是内部实现错误，用户不懂。应该明确告知用户没有找到 component 配置项，如何修复。

**Comment by heimanba** [comment]
@serverless-devs/s: 2.1.1 已修复
