### ISSUE TITLE
logs 组件要进行一波优化

### ISSUE THREAD

**Issue by anycodes** [devsapp/fc#739]
1. 目前来看，我在使用s logs的时候，它不仅仅会获得当前函数的，他还会读到其他函数的，这个是不合理的。
2. 貌似我们的logs的展示形式和线上的有比较大的区别，这个要看一下如何优化一下，最好可以和控制台的格式保持一致。

**Comment by wss-git** [comment]
已尽量和控制台保持一致并发布
