### ISSUE TITLE
s instance exec 的信息显示被截断了

### ISSUE THREAD

**Issue by hryang** [devsapp/fc#743]
如图所示，ps aux 显示的信息不完整，被截断了。
![图片](https://user-images.githubusercontent.com/626967/168032905-5209e0f5-0128-489b-a19e-f16bac971f79.png)

**Comment by wss-git** [comment]
![image](https://user-images.githubusercontent.com/56686088/168513584-ee85118e-7a52-4ff5-a4ac-ce61f821a1bc.png)
![image](https://user-images.githubusercontent.com/56686088/168513598-e82740d7-5ace-4dac-86c0-d94a4ed8b8fb.png)
请问使用的什么系统和终端呢？ 我尝试了 mac 的 zsh 和 bash 均没有复现

**Comment by wss-git** [comment]
![image](https://user-images.githubusercontent.com/56686088/176584023-c55f931d-99ac-40c6-8a93-16a300028322.png)
未复现
