### ISSUE TITLE
nas auto出现非预期交互

### ISSUE THREAD

**Issue by lowkeyrd** [devsapp/fc#745]
使用模板创建应用，nas用的auto，但是部署却出现交互让选择vpc。

![image](https://user-images.githubusercontent.com/5763215/168079456-2079dfdc-d9c0-413f-a522-d3cf0f8315b3.png)

备注：应用第一次部署失败了，原因是Nas可用状态判断超时，重试后出现的上述问题
![image](https://user-images.githubusercontent.com/5763215/168081145-fa5baf9c-6f25-4a10-8174-d8434ddb5593.png)

**Comment by wss-git** [comment]
交互设计：存在多个符合绑定服务的 vpc，让用户选择使用哪个 vpc。

可能产生多个 vpc 原因：
- 同时间段并发创建了符合规则的 vpc
- 用户手动创建

**Comment by wss-git** [comment]
已发布
