### ISSUE TITLE
s 工具不能发布超过 50 MB 的 layer

### ISSUE THREAD

**Issue by hryang** [devsapp/fc#747]
s layer publish 时，遇到如下错误：

POST /layers/openvscode-server/versions failed with 400. requestid: 8f1d8f68-f63f-46f8-aaa0-8878b91247bc, message: Code size exceeds the maximum allowed length (max: 52428800, actual: '59248015').

控制台是可以发布 layer 的，s 工具的能力应该和控制台保持一致。

**Comment by anycodes** [comment]
这个是代码包大小超过了吧，这个应该是接口报的错。

**Comment by anycodes** [comment]
我理解控制台理论用的也是这个接口？还是说有啥其他的接口可供使用》现在layer大小的限制50M吧

**Comment by hryang** [comment]
之前咱们做过一个事情，首先把代码包上传到一个控制台自己的 oss bucket 中，这样就绕过了 50 MB 的限制。layer 和代码包一样，应该也复用这个逻辑。

**Comment by wss-git** [comment]
> 之前咱们做过一个事情，首先把代码包上传到一个控制台自己的 oss bucket 中，这样就绕过了 50 MB 的限制。layer 和代码包一样，应该也复用这个逻辑。

这个需要找相关的同学确认一下接口，我研究了一下 sdk 的大代码包上传，还是存在一些服务的特殊信息在里面的

**Comment by wss-git** [comment]
已发布
