### ISSUE TITLE
domain路径配置支持增量配置

### ISSUE THREAD

**Issue by anycodes** [devsapp/fc#749]
目前domain是全量配置，应该增加一个配置是增量配置

**Comment by lowkeyrd** [comment]
https://github.com/devsapp/fc/issues/733

**Comment by wss-git** [comment]
可以参考这个[文档](http://doc.doc.1899690531354629.cn-hangzhou.fc.devsapp.net/%E4%BA%A7%E5%93%81%E5%AE%9E%E8%B7%B5/%E5%87%BD%E6%95%B0%E8%AE%A1%E7%AE%97%E5%9F%9F%E5%90%8D%E5%AE%9E%E8%B7%B5/)
