### ISSUE TITLE
rollback  回滚插件

### ISSUE THREAD

**Issue by heimanba** [devsapp/fc#759]

**Comment by heimanba** [comment]
希望在出现问题时候，能够支持一键回滚的能力。

**Comment by wss-git** [comment]
可以不是插件，做在组件里面，新增能力：
`s alias publish --alias-name aliasName --version-id latest /( HEAD^ 线上必须已经存在 alias )/ version-id`
`s alias rollback --alias-name aliasName --version-id HEAD^/version-id `

**Comment by wss-git** [comment]
以支持
