### ISSUE TITLE
端云联调热更新代码， 有一个不影响流程的错误

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#76]
![image](https://user-images.githubusercontent.com/10919599/125281124-6cf3ce80-e348-11eb-945c-6b96ed122f7a.png)

1. 无关的错误就不要打出了
2. 中途需要告诉用户需要等待

**Comment by git-qfzhang** [comment]
端云联调 0.0.4 已经修复此问题。https://github.com/devsapp/fc-tunnel-invoke/releases/tag/0.0.4
