### ISSUE TITLE
s.yaml提供预留配置

### ISSUE THREAD

**Issue by lowkeyrd** [devsapp/fc#796]
来自客户的输入：
![image](https://user-images.githubusercontent.com/5763215/181139529-8613322d-4059-45e3-b58a-f778b6905653.png)
![image](https://user-images.githubusercontent.com/5763215/181139632-ead11c09-3853-4f84-8702-ec3a57f96d41.png)

从配置便捷性上来讲，命令的方式配置预留确实不太方便，是否可以提供个插件，通过声明的方式来支持预留？

**Comment by wss-git** [comment]
已实现：https://github.com/devsapp/provision-fc

**Comment by lowkeyrd** [comment]
看了下当前的实现，插件必须要指定serviceName、functionName，这个不满足插件定义。插件的作用是给组件打补丁，这个插件最常见的是结合fc组件来使用，所以不应该透出serviceName、functionName。即使透出，这两个参数也不应该是必须的
