### ISSUE TITLE
s local start 一个纯faas 服务无法固定端口

### ISSUE THREAD

**Issue by stalker-silence** [devsapp/fc#804]
为了便于本地调试希望s local start 能够固定启动host、port

**Comment by wss-git** [comment]
比如我调试的接口固定是： http://my.console.aliyun.com:8000/

1. 绑定本地的 host
```
127.0.0.1 my.console.aliyun.com
```
2. 运行指令
```
s api local start --server-port 8000
```
3. 访问地址
![image](https://user-images.githubusercontent.com/56686088/183841791-c261bad2-4a0b-4392-b94b-177508190d27.png)

参考文档：https://docs.serverless-devs.com/fc/command/local#local-start-%E5%91%BD%E4%BB%A4
