### ISSUE TITLE
s publish layer 如果这个 layer 的 checksum 没有发生改变， 就不强制修改这个 layer 了

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#807]
s publish layer 能不能支持这个功能， 如果这个 layer 的 checksum 没有发生改变， 就不强制修改这个 layer 了，这种情况 layer 升级版本没有意义

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/10919599/183892681-85562f56-2bce-4b1d-a246-55294726a531.png">

**Comment by wss-git** [comment]
已发布
