### ISSUE TITLE
s 工具不支持企业版镜像仓库部署

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#816]
s 工具不支持企业版镜像仓库部署

1. 如果在本地 s 工具操作， 需要企业版实例开通公网访问
2. 在1 满足的条件下， 可以探索下， 企业版 acr 实例的体验优化

**Comment by wss-git** [comment]
问题补充：
1. 企业版实例的ID一般是 cri-开头的，crr是repo id
2. 企业镜像只能在同一个主账号下使用，不能跨账号使用

**Comment by wss-git** [comment]
问题补充：
1. 企业版实例的ID一般是 cri-开头的，crr是repo id
2. 企业镜像只能在同一个主账号下使用，不能跨账号使用

**Comment by rsonghuster** [comment]
<img width="673" alt="image" src="https://user-images.githubusercontent.com/10919599/196076050-00aefc30-9d63-4a5e-b436-11399be0618a.png">

**Comment by wss-git** [comment]
https://help.aliyun.com/document_detail/145324.html

**Comment by lowkeyrd** [comment]
总结下目前ACR的需求
1. s.yaml支持acree
2. s.yaml中的镜像地址如果是vpc的，则应用中心在s build时自动替换成公网地址，通过公网来上传镜像。部署时还是用vpc地址

**Comment by lowkeyrd** [comment]
再补充一个需求：自定义镜像有加速转换的功能，CustomContainerConfig有个accelerationInfo属性用于返回加速状态。期望deploy时一直等到accelerationInfo变成ready才算完成

**Comment by heimanba** [comment]
> 

这个能力要做到fc-deploy里面吧，相当于对镜像部署的能力增强哈

**Comment by wss-git** [comment]
1. accelerationInfo.status  的终态有哪些
2. 是否有最大时间：5 min
3. 所有镜像函数

**Comment by lowkeyrd** [comment]
> Failed、Preparing、Ready

**Comment by wss-git** [comment]
> 总结下目前ACR的需求
> 
> 1. s.yaml支持acree
> 2. s.yaml中的镜像地址如果是vpc的，则应用中心在s build时自动替换成公网地址，通过公网来上传镜像。部署时还是用vpc地址

这个功能已经发布，新的需求在 #858 跟进
