### ISSUE TITLE
需要支持Custom health check

### ISSUE THREAD

**Issue by VBill** [devsapp/fc#834]
如题，API文档已经支持这个功能。

create/update/get/list function 返回函数信息需要增加custom health check 属性。
https://help.aliyun.com/document_detail/415747.html
https://help.aliyun.com/document_detail/415749.html
https://help.aliyun.com/document_detail/415750.html
https://help.aliyun.com/document_detail/415752.html

custom health check 结构体定义。
https://help.aliyun.com/document_detail/451288.html

**Comment by wss-git** [comment]
已发布
