### ISSUE TITLE
端云联调功能完善

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#835]
针对 custom runtime 端云联调功能，有如下完整的优化需求：

### 1. 支持 custom runtime config

https://github.com/devsapp/fc/issues/831
https://github.com/devsapp/fc/issues/832

### 2.  端云联调启动一个预留实例不符合预期

顺序改成这样 put ondemand config -> invoke（预期必定出现429） -> put provision -> debug， 这个可以解决主要问题

>   注意中间调用 invoke 步骤中， 一定要区分是 event 函数还是 http 函数， 从而一定要出现预期的 429

**Comment by wss-git** [comment]
已支持
