### ISSUE TITLE
preStop 支持

### ISSUE THREAD

**Issue by ALIFYB** [devsapp/fc#839]
s cli fc api StopStatefulAsyncInvocation

**Comment by anycodes** [comment]
可以直接提pr：https://github.com/devsapp/fc-api-component

对应版本的API，维护在对应的json中：

![image](https://user-images.githubusercontent.com/21079031/190989388-349512af-d28b-46cb-ae1c-88d75197ca3f.png)

**Comment by wss-git** [comment]
应该是版本不对，20160815 应该没有这个接口
````
s cli fc-default set api-default-version 20210416

s cli fc api StopStatefulAsyncInvocation -h 
````
