### ISSUE TITLE
端云联调： 辅助函数如何支持oss 触发器

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#89]
假设是如下场景， 有一个函数， 有一个 oss 触发器， 触发规则前缀是/a, 后缀是空， s 工具创建端云联调辅助函数的时候， 辅助函数可能因为 oss 的触发规则， 导致不能在辅助函数上创建 oss 触发器， 这个时候应该如何处理？

辅助函数创建成功， 吞掉不能创建触发器的错误， 提示用户可以临时将 oss 触发器指向辅助函数？

**Comment by anycodes** [comment]
https://github.com/xinwuyun/cfc

**Comment by git-qfzhang** [comment]
辅助函数因为 oss 触发器的原因，创建失败了，此时执行如下步骤：

1. 询问用户是否删除线上目标函数对应的 oss 触发器，如果是，则尝试为用户删除此触发器，否则退出，提示用户手动删除对应的 oss 触发器。提示后执行 cleanup 操作并退出。
2. 如果尝试删除目标函数的 oss 触发器失败的话，那么需要提示用户手动删除对应的 oss 触发器。提示后执行 cleanup 操作并退出。

**Comment by git-qfzhang** [comment]
Fix： https://github.com/devsapp/fc-proxied-invoke/pull/28
