### ISSUE TITLE
部分window 机型执行 execSync('docker info --format "{{json .}}"') 失败

### ISSUE THREAD

**Issue by wss-git** [devsapp/fc#896]
问题描述：
1. 没有安装 docker
2. 安装了 docker 但是子进程确实无法调用。

临时解决方式：
方案一：遇到window 直接跳过检测
方案二：抛出异常不阻塞运行，抛出一个 error message，继续尝试运行

PS：最终还是需要定位到为什么子进程无法调用到docker 信息。
子进程没有继承配置正确环境信息？
子进程没有调用权限？

**Comment by heimanba** [comment]
> 问题描述：
> 
> 1. 没有安装 docker
> 2. 安装了 docker 但是子进程确实无法调用。
> 
> 临时解决方式： 方案一：遇到window 直接跳过检测 方案二：抛出异常不阻塞运行，抛出一个 error message，继续尝试运行
> 
> PS：最终还是需要定位到为什么子进程无法调用到docker 信息。 子进程没有继承配置正确环境信息？ 子进程没有调用权限？

方案二可以作为保底哈，可提供一个warning的信息，用于排查需求

**Comment by wss-git** [comment]
后面这种前置检查不再阻塞程序运行，而是通过warn形式输出
