### ISSUE TITLE
使用 48M 的 zip 包创建 layer， 返回 limit 超过限制报错

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#913]
POST /layers/webide-server-dev/versions failed with 400. requestid: 1230383e-c7b4-4b8a-adef-cdfb8c68603b, message: payload size exceeds maximum allowed size (104857600 bytes).

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/10919599/210477486-70050ce9-0943-4fad-a468-f4e65a162b8e.png">

工具这边：如果小于 50M 就是通过 base64 上传，否则的话走的这个流程： 先去请求后端拿到 CodeSizeLimit 的大小，如果没有超限制就会上传到临时的 oss，然后创建 layer。但是看起来前面都走过去了 但是最后又给拦截了

控制台那边都是走 oss， 就没有问题了

建议搞一个环境变量（用户自己可以自由设置），这个环境变量default值， 个人觉的可以是20M就可以考虑走oss了

**Comment by heimanba** [comment]
已经修复

https://github.com/devsapp/fc-layer/pull/17
