### ISSUE TITLE
s创建和更新 service 的 api 接口应该有能力校验 vpc 配置是否和挂载点匹配

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#923]
![image](https://user-images.githubusercontent.com/10919599/216313293-980c46f0-a7a5-48b4-91e3-855fe1e0a9a6.png)

用户第一次使用 nas 不熟悉， 以为 nas 的挂载点是不会变化的， 因为 vpc config 填写的是 2， 但是挂载点写的是 1， 然后直接 s deploy 部署成功， 但是函数执行的时候， 会报错， 出现 nas 挂载不成功， 甚至用户函数没有收集到日志

控制台已经做好了这个体验， 当选择了 2 的 vpc 的时候， 挂载点只能下拉 2 的， 不可能选中1

s 工具同理， FC 后端系统无法做， 因为没有用户的 AK

**Comment by wss-git** [comment]
已发布
