### ISSUE TITLE
s 工具支持为自定义域名开启 waf

### ISSUE THREAD

**Issue by heimanba** [devsapp/fc#926]
【需求描述】：目前函数计算支持为自定义域名开启 waf，s工具也需要做对应的支持

文档：
![image](https://user-images.githubusercontent.com/5129967/217127288-a011878c-561a-4513-9eb1-34b09b369f57.png)

https://help.aliyun.com/document_detail/477345.html
API 文档：
![image](https://user-images.githubusercontent.com/5129967/217127325-e6a999da-2776-4759-8a25-8c4fb3e394ac.png)

https://help.aliyun.com/document_detail/415735.html

数据结构：https://help.aliyun.com/document_detail/478687.htm?spm=a2c4g.11186623.0.0.68c92e314b4RID

**Comment by wss-git** [comment]
https://github.com/devsapp/fc-domain/pull/27
https://github.com/devsapp/fc-plan/pull/25
https://github.com/devsapp/fc/pull/940

**Comment by wss-git** [comment]
已发布
