### ISSUE TITLE
可以开源 fc-proxied-invoke 组件的源码吗？

### ISSUE THREAD

**Issue by pilaoda** [devsapp/fc#934]
遇到问题想自己调试下然后提个Pull request，发现找不到这个组件的ts源码。

**Comment by wss-git** [comment]
可以看看是不是这个仓库哈

https://github.com/devsapp/fc-proxied-invoke

**Comment by pilaoda** [comment]
> 可以看看是不是这个仓库哈
> 
> https://github.com/devsapp/fc-proxied-invoke

Page not found.

没有公开吗？

**Comment by heimanba** [comment]
> 

已经公开哈
