### ISSUE TITLE
deploy 不支持打包符号链接

### ISSUE THREAD

**Issue by pilaoda** [devsapp/fc#938]
有部分代码与其他项目共享，做了symbol link，但是deploy上去丢失了

**Comment by heimanba** [comment]
symbol link 支持不了哈，本质是zip行为，可以试试硬链接

**Comment by wss-git** [comment]
软链接的坑还是很多的，比如发布（核心其实是 zip 操作）、跨平台下载（主要是 window）和 docker bind 操作等等，都会在一些特定的 case 存在问题。不太好支持哈，建议尝试硬链接哈
