### ISSUE TITLE
fc-build 在 fc-backend 的情况下， 需要把 python3.10 也考虑进来

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#939]
fc-build 在 fc-backend 的情况下， 需要把 python3.10 也考虑进来

https://github.com/devsapp/fc-build/blob/cc18d850a2e0fffce7050531eb81604dc9aa3f72/src/utils/constant.ts#L58-L74

应用中心构建镜像增加了 py3.10， 待升级
![image](https://user-images.githubusercontent.com/10919599/220887867-beda168e-2d4f-4746-971d-e3dfe5dbeaab.png)

nodejs runtime 的自动切换也考虑下吧

**Comment by wss-git** [comment]
已发布
