### ISSUE TITLE
支持pnpm 安装依赖

### ISSUE THREAD

**Issue by heimanba** [devsapp/fc#950]

**Comment by JasonLamv-t** [comment]
有更多描述吗？

**Comment by heimanba** [comment]
希望在应用中心支持pnpm install等能力



---原始邮件---
发件人: "Jason ***@***.***&gt;
发送时间: 2023年3月22日(周三) 凌晨4:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [devsapp/fc] 支持pnpm 安装依赖 (Issue #950)




 
有更多描述吗？

**Comment by JasonLamv-t** [comment]
是指 s init 时检测到项目内包含 package.json 以及 lock 文件时提示安装依赖并执行吗？
