### ISSUE TITLE
自定义域名可以不强制要求填写 tlsConfig 么？

### ISSUE THREAD

**Issue by OhYee** [devsapp/fc#951]
在 deploy 函数时，如果带上 `customDomain` 并且不带 `tlsConfig` 会提示存在删除证书的 diff

可以考虑这里不填默认用线上的配置么？不然就要 yaml 带着证书走了。

![image](https://user-images.githubusercontent.com/13498329/224658419-dbafce60-a594-4503-9a1b-cb4ef30dc00f.png)

----

另外 `certId` 可以考虑下配置为 `auto` 时，拉一下阿里云证书的列表，根据 `sans` 以及过期时间匹配一个最合适的证书出来

类似这样
```javascript
function getLatestMatchedCert(
  /** @type {cas.ListUserCertificateOrderResponseBodyCertificateOrderList[]} */ certs,
  /** @type {string} */ targetDomain
) {
  return [...certs]
    .sort((a, b) => (a.endDate > b.endDate ? -1 : 1))
    .find((cert) =>
      cert.sans
        .split(',')
        .find((san) =>
          san.includes('*.')
            ? san.replace('*.', '') ===
              targetDomain.split('.').slice(1).join('.')
            : san === targetDomain
        )
    );
}
```

**Comment by wss-git** [comment]
需要 @heimanba 评估一下，因为里面存在交互

**Comment by heimanba** [comment]
第一个问题：会破坏整体的Devs的设计，遵循 `Single source of truth` 原则,如果域名这么负责，建议不在YAML填写，直接在 控制台配置哈。
