### ISSUE TITLE
nas组件支持自动开通nas

### ISSUE THREAD

**Issue by lowkeyrd** [devsapp/fc#978]
现在大模型的应用模板NAS是刚需，新用户无论通过本地还是云端部署都会遇到Nas未开通导致失败问题，为了体验的顺畅，希望在部署时支持自动开通NAS
https://help.aliyun.com/document_detail/185438.html?spm=a2c4g.185437.0.0.71995d7aRBwDZc

**Comment by wss-git** [comment]
已发布
