### ISSUE TITLE
复制GPU函数时，s.yaml缺少gpuMemorySize字段

### ISSUE THREAD

**Issue by robinsonnie** [devsapp/fc#987]
https://docs.serverless-devs.com/fc-faq/%E4%BD%BF%E7%94%A8s%E5%B7%A5%E5%85%B7%E8%BF%9B%E8%A1%8C%E5%85%8B%E9%9A%86%E5%87%BD%E6%95%B0

如果是GPU函数，导出的s.yaml中缺少gpuMemorySize字段，s deploy时会报错

**Comment by wss-git** [comment]
已修复
