### ISSUE TITLE
docs/zh/yaml/triggers.md#Http触发器 缺少 OPTIONS 请求方式

### ISSUE THREAD

**Issue by DevDengChao** [devsapp/fc#992]
![image](https://github.com/devsapp/fc/assets/16363180/a52f4b4c-7a96-433d-8bea-ec55e7c3aa44)

![image](https://github.com/devsapp/fc/assets/16363180/2a9c652c-ae59-45eb-9fa6-3f5f67452aea)

**Comment by heimanba** [comment]
fixed
